"""Tests for security/api_key_auth.py.

Generated by cohezion.tools.test_generator.
Covers APIKeyValidator, get_validator, reset_validator.
"""

from __future__ import annotations

import os
from unittest.mock import patch

import pytest

from cohezion.security.api_key_auth import APIKeyValidator, get_validator, reset_validator


class TestGetValidator:
    """[P0] Unit tests for get_validator function."""

    def test_get_validator_creates_instance(self):
        """[P0] Should create and return APIKeyValidator instance."""
        reset_validator()  # Start fresh

        with patch.dict(os.environ, {"MCP_API_KEY": "test-key-123"}):
            validator = get_validator()

        assert isinstance(validator, APIKeyValidator)
        assert validator.api_key == "test-key-123"

    def test_get_validator_returns_singleton(self):
        """[P0] Should return same instance on multiple calls."""
        reset_validator()

        with patch.dict(os.environ, {"MCP_API_KEY": "test-key"}):
            validator1 = get_validator()
            validator2 = get_validator()

        assert validator1 is validator2

    def test_get_validator_uses_env_var(self):
        """[P0] Should read API key from environment."""
        reset_validator()

        with patch.dict(os.environ, {"MCP_API_KEY": "env-key"}):
            validator = get_validator()

        assert validator.api_key == "env-key"

    def test_get_validator_custom_env_key(self):
        """[P1] Should accept custom environment variable name."""
        reset_validator()

        with patch.dict(os.environ, {"CUSTOM_KEY": "custom-value"}):
            validator = get_validator(env_key="CUSTOM_KEY")

        assert validator.api_key == "custom-value"


class TestResetValidator:
    """[P0] Unit tests for reset_validator function."""

    def test_reset_validator_clears_instance(self):
        """[P0] Should reset global validator instance."""
        # Create a validator
        with patch.dict(os.environ, {"MCP_API_KEY": "key"}):
            get_validator()

        # Reset
        reset_validator()

        # Next call should create new instance
        with patch.dict(os.environ, {"MCP_API_KEY": "new-key"}):
            validator = get_validator()
            assert validator.api_key == "new-key"

    def test_reset_validator_returns_none(self):
        """[P1] Should return None."""
        result = reset_validator()
        assert result is None


class TestAPIKeyValidator:
    """[P0] Unit tests for APIKeyValidator class."""

    def test_initialization_with_key(self):
        """[P0] Should initialize with API key."""
        with patch.dict(os.environ, {"MCP_API_KEY": "test-api-key"}):
            validator = APIKeyValidator()

        assert validator.api_key == "test-api-key"

    def test_initialization_without_key(self):
        """[P0] Should handle missing API key gracefully."""
        with patch.dict(os.environ, {}, clear=True):
            validator = APIKeyValidator()

        assert validator.api_key is None

    def test_initialization_custom_env_key(self):
        """[P1] Should read from custom environment variable."""
        with patch.dict(os.environ, {"CUSTOM_API_KEY": "custom-value"}):
            validator = APIKeyValidator(env_key="CUSTOM_API_KEY")

        assert validator.api_key == "custom-value"

    def test_validate_with_valid_key(self):
        """[P0] Should validate correct API key."""
        with patch.dict(os.environ, {"MCP_API_KEY": "secret-key"}):
            validator = APIKeyValidator()

        result = validator.validate("secret-key")

        assert result is True

    def test_validate_with_invalid_key(self):
        """[P0] Should reject invalid API key."""
        with patch.dict(os.environ, {"MCP_API_KEY": "secret-key"}):
            validator = APIKeyValidator()

        result = validator.validate("wrong-key")

        assert result is False

    def test_validate_with_missing_key(self):
        """[P0] Should reject missing API key."""
        with patch.dict(os.environ, {"MCP_API_KEY": "secret-key"}):
            validator = APIKeyValidator()

        result = validator.validate(None)

        assert result is False

    def test_validate_with_no_api_key_configured(self):
        """[P0] Should allow all requests when no API key configured."""
        with patch.dict(os.environ, {}, clear=True):
            validator = APIKeyValidator()

        result = validator.validate("any-key")

        assert result is True

    def test_validate_uses_constant_time_comparison(self):
        """[P1] Should use constant-time comparison to prevent timing attacks."""
        with patch.dict(os.environ, {"MCP_API_KEY": "secret"}):
            validator = APIKeyValidator()

        # Should not raise and should be consistent
        result1 = validator.validate("secret")
        result2 = validator.validate("secret")

        assert result1 is True
        assert result2 is True
        assert result1 == result2

    def test_validate_case_sensitive(self):
        """[P1] Should be case-sensitive."""
        with patch.dict(os.environ, {"MCP_API_KEY": "SecretKey"}):
            validator = APIKeyValidator()

        result = validator.validate("secretkey")

        assert result is False


class TestAPIKeyValidatorIntegration:
    """[P1] Integration tests for API key validation."""

    @pytest.mark.fast
    def test_full_validation_workflow(self):
        """[P0] Should demonstrate complete validation workflow."""
        reset_validator()

        # Set up API key
        with patch.dict(os.environ, {"MCP_API_KEY": "production-key"}):
            validator = get_validator()

            # Valid key
            assert validator.validate("production-key") is True

            # Invalid key
            assert validator.validate("hacker-key") is False

            # Missing key
            assert validator.validate(None) is False

    @pytest.mark.fast
    def test_validator_persists_across_calls(self):
        """[P1] Should maintain singleton behavior."""
        reset_validator()

        with patch.dict(os.environ, {"MCP_API_KEY": "persistent-key"}):
            v1 = get_validator()
            v2 = get_validator()

            assert v1 is v2
            assert v1.api_key == "persistent-key"

    @pytest.mark.fast
    def test_reset_allows_reconfiguration(self):
        """[P1] Should allow reconfiguration after reset."""
        reset_validator()

        # First configuration
        with patch.dict(os.environ, {"MCP_API_KEY": "key1"}):
            v1 = get_validator()
            assert v1.api_key == "key1"

        # Reset
        reset_validator()

        # Second configuration
        with patch.dict(os.environ, {"MCP_API_KEY": "key2"}):
            v2 = get_validator()
            assert v2.api_key == "key2"

        # Should be different instances
        assert v1 is not v2
