FROM python:3.11-slim

WORKDIR /app

COPY . /app

# Install dependencies if any (none for this challenge)
# pip install -r requirements.txt

ENV PORT=8080

CMD ["python", "tests/submission_tests.py"]
