"""Dielectric field model — Biefield-Brown force mapped to U(1) gauge theory.

The Biefield-Brown effect (Biefield 1928, Brown 1929) describes electrohydrodynamic
(EHD) thrust generated by asymmetric capacitor configurations in dielectric media.
In the EHD picture, a strong E-field ionizes molecules near the sharp electrode;
ion-neutral collisions transfer momentum, producing net thrust without moving parts.

This module bridges the physical effect to Cohezion's gauge framework:
    - permittivity_tensor: anisotropic dielectric response (3×3)
    - biefield_brown_force(): EHD thrust vector from field asymmetry
    - to_gauge_connection(): maps the permittivity deviation to a U(1) GaugeConnection

The U(1) mapping: U(1) ⊂ SO(3) is the rotation about the z-axis (L_Z generator).
Permittivity deviation from vacuum (ε_r = 1) drives the gauge potential in this
single-generator subgroup, consistent with electromagnetic U(1) symmetry.

HIHO gauge condition: at ε_r = 1 (vacuum), the connection is flat (A = 0).
Dielectric loading (ε_r > 1) excites the gauge field proportionally to ε_r - 1.

References:
    - Brown, T.T. (1929). "A Method of and an Apparatus for Generating a High Potential"
      GB Patent 300,311
    - Christenson, E.A. & Moller, P.S. (1967). "Ion Neutral Propulsion in Air"
      AIAA Journal 5(10)
    - Nakahara (2003): Geometry, Topology and Physics — U(1) as electromagnetic gauge
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

import numpy as np

from cohezion.physics.gauge_theory import GaugeConnection


logger = logging.getLogger(__name__)

# U(1) ⊂ SO(3): L_Z is the generator of rotations about the z-axis.
# DielectricField uses this single generator to avoid coupling to spatial SO(3) dofs.
_U1_GENERATOR_INDEX = 2  # L_Z index within SO3_GENERATORS


@dataclass
class DielectricField:
    """Anisotropic dielectric field with EHD thrust and U(1) gauge bridge.

    Parameters
    ----------
    permittivity_tensor : np.ndarray
        3×3 relative permittivity tensor ε_r. Diagonal = isotropic medium.
        Off-diagonal entries capture anisotropy (e.g., liquid crystal alignment).
    electrode_separation : float
        Distance between sharp and blunt electrodes in metres (default 0.01 m).
    voltage : float
        Applied voltage in Volts (default 10_000 V). Sets EHD thrust scale.
    fabric_name : str
        Gauge fabric label. Defaults to "Field" (hardware/resource fabric in
        Cohezion's four-fabric model, coupling g₂ = 0.7).
    """

    permittivity_tensor: np.ndarray = field(default_factory=lambda: np.eye(3, dtype=float))
    electrode_separation: float = 1e-2
    voltage: float = 1e4
    fabric_name: str = "Field"

    def __post_init__(self) -> None:
        self.permittivity_tensor = np.asarray(self.permittivity_tensor, dtype=float)
        if self.permittivity_tensor.shape != (3, 3):
            raise ValueError("permittivity_tensor must be 3×3")

    @property
    def mean_permittivity(self) -> float:
        """Scalar effective permittivity: trace(ε_r) / 3."""
        return float(np.trace(self.permittivity_tensor)) / 3.0

    def biefield_brown_force(self) -> np.ndarray:
        """Compute EHD thrust vector (N) from field asymmetry.

        Simplified EHD scaling (Christenson & Moller 1967):
            F = ε₀ · ε_eff · (V / d)² · A_eff

        where A_eff = electrode area proxy (1 cm²) and the direction is set
        by the principal eigenvector of the permittivity tensor (thrust follows
        the direction of highest dielectric loading).

        Returns
        -------
        np.ndarray
            Shape (3,) force vector in Newtons.
        """
        eps0 = 8.854e-12  # F/m
        e_field = self.voltage / max(self.electrode_separation, 1e-9)
        A_eff = 1e-4  # 1 cm² effective area

        magnitude = eps0 * self.mean_permittivity * e_field**2 * A_eff

        # Thrust direction: principal eigenvector (largest eigenvalue)
        eigenvalues, eigenvectors = np.linalg.eigh(self.permittivity_tensor)
        thrust_dir = eigenvectors[:, np.argmax(eigenvalues)]
        return magnitude * thrust_dir

    def to_gauge_connection(self) -> GaugeConnection:
        """Map permittivity deviation to a U(1) GaugeConnection.

        U(1) ⊂ SO(3): only the L_Z generator is excited. The connection
        coefficient A^z_μ = (ε_r_μμ - 1) for each diagonal direction μ.

        At vacuum (ε_r = I), the connection is flat. Dielectric loading
        ε_r > 1 excites the gauge field proportionally to ε_r - 1.

        Returns
        -------
        GaugeConnection
            SO(3) connection with only the L_Z row populated (U(1) embedding).
        """
        conn = GaugeConnection(fabric_name=self.fabric_name)
        # Build 3×3 potential: only row _U1_GENERATOR_INDEX (L_Z) is non-zero
        A = np.zeros((3, 3))
        diag_eps = np.diag(self.permittivity_tensor)  # (3,) diagonal
        A[_U1_GENERATOR_INDEX, :] = diag_eps - 1.0  # deviation from vacuum
        conn.set_potential(A)
        logger.debug(
            "DielectricField → GaugeConnection[%s]: U(1) potential norm=%.4f",
            self.fabric_name,
            float(np.linalg.norm(A)),
        )
        return conn
