import logging

from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

from cohezion.universe.triune_manifold import TriuneState


logger = logging.getLogger(__name__)


class ObsidianMemoryMCP:
    """
    Client for interacting with the Obsidian Knowledge Vault via MCP.
    """

    def __init__(
        self, server_url: str = "stdio://cloud-vault-mcp", vault_base_path: str = "trajectories"
    ):
        """
        Initializes the MCP client.

        Args:
            server_url: The connection URL for the MCP server.
            vault_base_path: The directory within the vault to store summaries.
        """
        self.server_url = server_url
        self.vault_base_path = vault_base_path

    async def store_state_summary(
        self, trajectory_id: str, state: TriuneState, coherence: float
    ) -> str:
        """
        Formats and stores a highly semantic summary of the triune state to Obsidian.

        Args:
            trajectory_id: Unique identifier for the trajectory.
            state: The TriuneState object.
            coherence: The calculated coherence score.

        Returns:
            str: The response from the MCP server.
        """
        path = f"{self.vault_base_path}/{trajectory_id}.md"

        content = f"""# Trajectory Summary: {trajectory_id}

## Triune Manifold State
- **Coherence**: {coherence:.4f}
- **Stability Point**: 0.5 (HIHO)

### Dimensional Vectors (Summary)
- **Doer (12D)**: {state.doer.tolist()[:3]}... (norm: {state.doer.norm():.4f})
- **Thinker (512D)**: [Vector latent space] (norm: {state.thinker.norm():.4f})
- **Knower (2048D)**: [Semantic intent layer] (norm: {state.knower.norm():.4f})

## Narrative Journey
The agent transitioned through this state with a coherence of {coherence:.4f}.
The manifold restoring force was {(0.5 - coherence):.4f}.

---
*Generated by Cohezion Triune Engine*
"""

        # In a real engine, we might reuse a persistent session.
        # For this scaffold, we demonstrate the tool call.

        # Parse stdio params from server_url for demonstration
        # stdio://path/to/script -> parameters
        import os
        import sys

        server_params = StdioServerParameters(
            command=sys.executable,
            args=["-m", "cohezion.mcp.servers.vault.server"],  # Example
            env=os.environ.copy(),
        )

        async with stdio_client(server_params) as (read, write):
            async with ClientSession(read, write) as session:
                await session.initialize()
                result = await session.call_tool("vault_write", {"path": path, "content": content})
                return str(result)
