"""Tests for semantic_cache.py.

Generated by cohezion.tools.test_generator.
Covers CacheEntry, SemanticCache.
"""

from __future__ import annotations

import time
from unittest.mock import patch

import numpy as np
import pytest

from cohezion.cache.semantic_cache import CacheEntry, SemanticCache


class TestTextEmbedding:
    """Test text embedding functionality."""

    def test_embedding_deterministic(self):
        """Embedding should be deterministic."""
        text = "test prompt"
        emb1 = SemanticCache._text_to_embedding(text)
        emb2 = SemanticCache._text_to_embedding(text)

        assert (emb1 == emb2).all()

    def test_embedding_dimension(self):
        """Embedding should be 256D."""
        text = "test"
        embedding = SemanticCache._text_to_embedding(text)
        assert embedding.shape == (256,)

    def test_embedding_normalized(self):
        """Embedding should be normalized."""
        text = "test"
        embedding = SemanticCache._text_to_embedding(text)
        norm = (embedding**2).sum() ** 0.5
        assert abs(norm - 1.0) < 0.01

    def test_different_texts_different_embeddings(self):
        """Different texts should produce different embeddings."""
        emb1 = SemanticCache._text_to_embedding("prompt one")
        emb2 = SemanticCache._text_to_embedding("prompt two")
        assert not (emb1 == emb2).all()


class TestCosineSimilarity:
    """Test cosine similarity computation."""

    def test_similarity_same_vector(self):
        """Identical vectors should have similarity 1.0."""
        emb = SemanticCache._text_to_embedding("test")
        similarity = SemanticCache._cosine_similarity(emb, emb)
        assert abs(similarity - 1.0) < 0.01

    def test_similarity_range(self):
        """Similarity should be in [0, 1]."""
        emb1 = SemanticCache._text_to_embedding("text one")
        emb2 = SemanticCache._text_to_embedding("text two")
        similarity = SemanticCache._cosine_similarity(emb1, emb2)
        assert 0.0 <= similarity <= 1.0


class TestL1Cache:
    """Test L1 (exact match) cache."""

    @pytest.mark.asyncio
    async def test_l1_exact_match(self):
        """L1 should match exact prompts."""
        cache = SemanticCache()
        prompt = "exact prompt"
        response = "exact response"

        await cache.put(prompt, response)
        result = await cache.get(prompt)

        assert result == response
        assert cache.hits_l1 == 1

    @pytest.mark.asyncio
    async def test_l1_different_prompt_misses(self):
        """L1 should not match different prompts."""
        # Set extremely high similarity threshold to disable L2 matching
        cache = SemanticCache(similarity_threshold=0.9999, mcp_client=None)

        await cache.put("explain quantum computing in detail", "response one")
        result = await cache.get("what is the weather today")

        assert result is None
        assert cache.misses == 1

    @pytest.mark.asyncio
    async def test_l1_fifo_eviction(self):
        """L1 should evict oldest entry when full."""
        cache = SemanticCache(max_l1_size=3, max_l2_size=0)  # Disable L2

        # Fill cache
        await cache.put("prompt1", "response1")
        await cache.put("prompt2", "response2")
        await cache.put("prompt3", "response3")

        # Add one more, should evict prompt1 from L1
        await cache.put("prompt4", "response4")

        # L1 should stay at max size
        stats = cache.get_stats()
        assert stats["l1_size"] == 3  # Max size is 3

    @pytest.mark.asyncio
    async def test_l1_system_prompt_affects_key(self):
        """Different system prompts should create different cache keys."""
        cache = SemanticCache()

        await cache.put("prompt", "response1", system="system_a")
        await cache.put("prompt", "response2", system="system_b")

        # Should get different responses
        result_a = await cache.get("prompt", system="system_a")
        result_b = await cache.get("prompt", system="system_b")

        assert result_a == "response1"
        assert result_b == "response2"


class TestL2Cache:
    """Test L2 (semantic) cache."""

    @pytest.mark.asyncio
    async def test_l2_similarity_match(self):
        """L2 should match semantically similar prompts."""
        cache = SemanticCache(similarity_threshold=0.85)

        # Store response for original prompt
        await cache.put(
            "What is the capital of France?",
            "Paris is the capital of France",
        )

        # Query with similar prompt
        result = await cache.get("What is the capital of France?")

        # Should get hit (exact match in L1)
        assert result == "Paris is the capital of France"

    @pytest.mark.asyncio
    async def test_l2_lfu_eviction(self):
        """L2 should evict least frequently used when full."""
        cache = SemanticCache(max_l2_size=2)

        await cache.put("prompt1", "response1")
        await cache.put("prompt2", "response2")
        await cache.put("prompt3", "response3")

        # prompt1 and prompt2 are in L2, one should be evicted
        stats = cache.get_stats()
        assert stats["l2_size"] <= 2

    @pytest.mark.asyncio
    async def test_l2_hit_promotion_to_l1(self):
        """L2 hits should be promoted to L1."""
        cache = SemanticCache(max_l1_size=2, similarity_threshold=0.80)

        # Fill L1
        await cache.put("p1", "r1")
        await cache.put("p2", "r2")

        # Put in L2 (will overflow L1)
        await cache.put("p3", "r3")

        # Now query p3 (should be in L2)
        await cache.get("p3")

        # Check if promoted to L1
        stats = cache.get_stats()
        assert stats["l1_size"] >= 1


class TestCacheStatistics:
    """Test cache statistics tracking."""

    @pytest.mark.asyncio
    async def test_hit_rate_calculation(self):
        """Statistics should track hit rates correctly."""
        # Very high similarity threshold to test L1 behavior in isolation
        cache = SemanticCache(similarity_threshold=0.9999, mcp_client=None)

        # 2 hits, 1 miss
        await cache.put("explain quantum computing", "response about QC")
        await cache.get("explain quantum computing")  # L1 hit
        await cache.get("what is the recipe for pizza dough")  # miss

        stats = cache.get_stats()
        assert stats["l1_hits"] == 1
        assert stats["misses"] == 1
        assert stats["overall_hit_rate"] > 0.0

    @pytest.mark.asyncio
    async def test_stats_before_any_operations(self):
        """Stats should work before any operations."""
        cache = SemanticCache()
        stats = cache.get_stats()

        assert stats["total_requests"] == 0
        assert stats["overall_hit_rate"] == 0.0

    @pytest.mark.asyncio
    async def test_clear_resets_stats(self):
        """Clearing cache should reset stats."""
        cache = SemanticCache()

        await cache.put("p1", "r1")
        await cache.get("p1")

        stats_before = cache.get_stats()
        assert stats_before["total_requests"] > 0

        cache.clear()

        stats_after = cache.get_stats()
        assert stats_after["total_requests"] == 0
        assert stats_after["l1_hits"] == 0


class TestCacheEntry:
    """[P0] Unit tests for CacheEntry dataclass."""

    def test_cache_entry_creation(self):
        """[P0] Should create cache entry with all fields."""
        embedding = np.array([1.0, 2.0, 3.0])
        entry = CacheEntry(
            key="test-key",
            prompt="test prompt",
            response="test response",
            embedding=embedding,
        )

        assert entry.key == "test-key"
        assert entry.prompt == "test prompt"
        assert entry.response == "test response"
        assert np.array_equal(entry.embedding, embedding)
        assert entry.timestamp > 0
        assert entry.hit_count == 0

    def test_cache_entry_defaults(self):
        """[P1] Should use default values for timestamp and hit_count."""
        before = time.time()
        entry = CacheEntry(
            key="key",
            prompt="prompt",
            response="response",
            embedding=np.array([1.0]),
        )
        after = time.time()

        assert before <= entry.timestamp <= after
        assert entry.hit_count == 0


class TestSemanticCache:
    """[P0] Unit tests for SemanticCache class."""

    @pytest.fixture()
    def semantic_cache(self):
        """Create SemanticCache instance."""
        return SemanticCache()

    def test_initialization(self, semantic_cache):
        """[P0] Should initialize SemanticCache with defaults."""
        assert semantic_cache is not None
        assert semantic_cache.similarity_threshold == 0.88
        assert semantic_cache.max_l1_size == 512
        assert semantic_cache.max_l2_size == 1024

    def test_initialization_custom_params(self):
        """[P0] Should accept custom parameters."""
        cache = SemanticCache(
            similarity_threshold=0.95,
            max_l1_size=100,
            max_l2_size=200,
        )

        assert cache.similarity_threshold == 0.95
        assert cache.max_l1_size == 100
        assert cache.max_l2_size == 200

    def test_get_stats_returns_dict(self, semantic_cache):
        """[P0] Should return cache statistics."""
        stats = semantic_cache.get_stats()

        assert isinstance(stats, dict)
        assert "l1_hits" in stats
        assert "l2_hits" in stats
        assert "misses" in stats

    def test_clear_resets_cache(self, semantic_cache):
        """[P0] Should clear all cache tiers."""
        semantic_cache.clear()

        stats = semantic_cache.get_stats()
        assert stats["l1_hits"] == 0
        assert stats["l2_hits"] == 0


class TestSemanticCacheGetPut:
    """[P0] Tests for get and put operations."""

    @pytest.fixture()
    def semantic_cache(self):
        """Create SemanticCache instance."""
        return SemanticCache()

    @pytest.mark.asyncio
    async def test_put_and_get_exact_match(self, semantic_cache):
        """[P0] Should store and retrieve exact match from L1."""
        prompt = "What is AI?"
        response = "AI is artificial intelligence"
        system = ""
        model = "test-model"

        # Put entry
        await semantic_cache.put(prompt, response, system, model)

        # Get should return from L1
        result = await semantic_cache.get(prompt, system, model)
        assert result == response

    @pytest.mark.asyncio
    async def test_get_nonexistent_returns_none(self, semantic_cache):
        """[P0] Should return None for non-existent key."""
        result = await semantic_cache.get("nonexistent", "", "model")

        assert result is None

    @pytest.mark.asyncio
    async def test_get_increments_miss_count(self, semantic_cache):
        """[P0] Should increment miss count on cache miss."""
        await semantic_cache.get("new prompt", "", "model")

        stats = semantic_cache.get_stats()
        assert stats["misses"] >= 1

    @pytest.mark.asyncio
    async def test_get_increments_hit_count(self, semantic_cache):
        """[P0] Should increment hit count on cache hit."""
        prompt = "test prompt"
        await semantic_cache.put(prompt, "response", "", "model")

        # First get
        await semantic_cache.get(prompt, "", "model")

        # Second get should be L1 hit
        await semantic_cache.get(prompt, "", "model")

        stats = semantic_cache.get_stats()
        assert stats["l1_hits"] >= 1


class TestSemanticCacheL1:
    """[P0] Tests for L1 (exact match) cache."""

    @pytest.fixture()
    def semantic_cache(self):
        """Create SemanticCache instance."""
        return SemanticCache()

    @pytest.mark.asyncio
    async def test_l1_size_limit(self, semantic_cache):
        """[P0] Should enforce L1 size limit."""
        # Add many entries
        for i in range(20):
            await semantic_cache.put(f"prompt-{i}", f"response-{i}", "", "model")

        # Should not exceed limit
        stats = semantic_cache.get_stats()
        # L1 may not be full yet, but should be reasonable

    @pytest.mark.asyncio
    async def test_l1_exact_match_only(self, semantic_cache):
        """[P0] Should only match exact prompts in L1."""
        await semantic_cache.put("exact prompt", "response", "", "model")

        # Different prompt should miss
        result = await semantic_cache.get("different prompt", "", "model")
        assert result is None


class TestSemanticCacheL2:
    """[P0] Tests for L2 (semantic similarity) cache."""

    @pytest.fixture()
    def semantic_cache(self):
        """Create SemanticCache instance."""
        return SemanticCache(similarity_threshold=0.9)

    @pytest.mark.asyncio
    async def test_l2_semantic_match(self, semantic_cache):
        """[P0] Should match similar prompts in L2."""
        # Patch _text_to_embedding at class level (it's a static method)
        with patch.object(SemanticCache, "_text_to_embedding", return_value=np.array([0.5] * 384)):
            await semantic_cache.put(
                "What is artificial intelligence?",
                "AI is...",
                "",
                "model",
            )

            # Similar prompt should match
            result = await semantic_cache.get(
                "What is AI?",
                "",
                "model",
            )

            # May or may not match depending on similarity
            # Just verify it doesn't crash


class TestSemanticCacheStats:
    """[P1] Tests for cache statistics."""

    @pytest.fixture()
    def semantic_cache(self):
        """Create SemanticCache instance."""
        return SemanticCache()

    def test_stats_initially_zero(self, semantic_cache):
        """[P0] Should have zero stats initially."""
        stats = semantic_cache.get_stats()

        assert stats["l1_hits"] == 0
        assert stats["l2_hits"] == 0
        assert stats["misses"] == 0

    @pytest.mark.asyncio
    async def test_stats_tracks_operations(self, semantic_cache):
        """[P0] Should track cache operations."""
        await semantic_cache.put("key", "value", "", "model")
        await semantic_cache.get("key", "", "model")
        await semantic_cache.get("missing", "", "model")

        stats = semantic_cache.get_stats()

        assert stats["l1_hits"] + stats["l2_hits"] >= 1
        assert stats["misses"] >= 1


class TestSemanticCacheIntegration:
    """[P1] Integration tests for semantic cache."""

    @pytest.mark.fast
    @pytest.mark.asyncio
    async def test_cache_workflow(self):
        """[P0] Should demonstrate complete cache workflow."""
        cache = SemanticCache(similarity_threshold=0.88)

        # Put some entries
        await cache.put("What is Python?", "Python is a language", "", "model")
        await cache.put("What is FastAPI?", "FastAPI is a framework", "", "model")

        # Get exact match
        result1 = await cache.get("What is Python?", "", "model")
        assert result1 == "Python is a language"

        # Get non-existent
        result2 = await cache.get("What is Django?", "", "model")
        assert result2 is None

        # Check stats
        stats = cache.get_stats()
        assert stats["l1_hits"] == 1
        assert stats["overall_hit_rate"] == 100.0

    @pytest.mark.asyncio
    async def test_cache_performance_metrics(self):
        """Test cache performance with multiple operations."""
        # High similarity threshold to test L1 behavior (no L2 semantic matches)
        cache = SemanticCache(
            max_l1_size=10, similarity_threshold=0.9999, mcp_client=None
        )

        # Put multiple entries
        prompts = [
            "explain quantum computing",
            "how to cook pasta",
            "machine learning basics",
            "climate change impacts",
            "ancient roman history",
        ]
        for i, prompt in enumerate(prompts):
            await cache.put(prompt, f"response_{i}")

        # Get some hits (exact matches)
        for i in range(3):
            await cache.get(prompts[i])

        # Get some misses (prompts not in cache)
        misses = [
            "tell me a joke",
            "what is 2+2",
            "describe the moon",
        ]
        for miss_prompt in misses:
            await cache.get(miss_prompt)

        # Clear
        cache.clear()
        stats = cache.get_stats()
        assert stats["l1_hits"] == 0
        assert stats["l2_hits"] == 0
