"""Tests for semantic_cache.py.

Generated by cohezion.tools.test_generator.
Covers CacheEntry, SemanticCache.
Updated: added TestAccessEntropy (AE1-AE5) for access_entropy() diagnostic.
"""

from __future__ import annotations

import sys
import time
from unittest.mock import MagicMock, patch

import numpy as np
import pytest

from cohezion.cache.semantic_cache import CacheEntry, SemanticCache


_ST_IS_REAL = not (
    "sentence_transformers" in sys.modules
    and sys.modules["sentence_transformers"].SentenceTransformer is MagicMock
)
requires_real_st = pytest.mark.skipif(
    not _ST_IS_REAL, reason="sentence_transformers is mocked (hardware compatibility)"
)


class TestCacheEntry:
    """[P0] Unit tests for CacheEntry dataclass."""

    def test_cache_entry_creation(self):
        """[P0] Should create cache entry with all fields."""
        embedding = np.array([1.0, 2.0, 3.0])
        entry = CacheEntry(
            key="test-key",
            prompt="test prompt",
            response="test response",
            embedding=embedding,
        )

        assert entry.key == "test-key"
        assert entry.prompt == "test prompt"
        assert entry.response == "test response"
        assert np.array_equal(entry.embedding, embedding)
        assert entry.timestamp > 0
        assert entry.hit_count == 0

    def test_cache_entry_defaults(self):
        """[P1] Should use default values for timestamp and hit_count."""
        before = time.time()
        entry = CacheEntry(
            key="key",
            prompt="prompt",
            response="response",
            embedding=np.array([1.0]),
        )
        after = time.time()

        assert before <= entry.timestamp <= after
        assert entry.hit_count == 0


class TestSemanticCache:
    """[P0] Unit tests for SemanticCache class."""

    @pytest.fixture()
    def semantic_cache(self):
        """Create SemanticCache instance."""
        return SemanticCache()

    def test_initialization(self, semantic_cache):
        """[P0] Should initialize SemanticCache with defaults."""
        assert semantic_cache is not None
        assert semantic_cache.similarity_threshold == 0.75
        assert semantic_cache.max_l1_size == 512
        assert semantic_cache.max_l2_size == 1024

    def test_initialization_custom_params(self):
        """[P0] Should accept custom parameters."""
        cache = SemanticCache(
            similarity_threshold=0.95,
            max_l1_size=100,
            max_l2_size=200,
        )

        assert cache.similarity_threshold == 0.95
        assert cache.max_l1_size == 100
        assert cache.max_l2_size == 200

    def test_get_stats_returns_dict(self, semantic_cache):
        """[P0] Should return cache statistics."""
        stats = semantic_cache.get_stats()

        assert isinstance(stats, dict)
        assert "l1_hits" in stats
        assert "l2_hits" in stats
        assert "misses" in stats

    def test_clear_resets_cache(self, semantic_cache):
        """[P0] Should clear all cache tiers."""
        semantic_cache.clear()

        stats = semantic_cache.get_stats()
        assert stats["l1_hits"] == 0
        assert stats["l2_hits"] == 0


class TestSemanticCacheGetPut:
    """[P0] Tests for get and put operations."""

    @pytest.fixture()
    def semantic_cache(self):
        """Create SemanticCache instance."""
        return SemanticCache()

    @pytest.mark.asyncio
    async def test_put_and_get_exact_match(self, semantic_cache):
        """[P0] Should store and retrieve exact match from L1."""
        prompt = "What is AI?"
        response = "AI is artificial intelligence"
        system = ""
        model = "test-model"

        # Put entry
        await semantic_cache.put(prompt, response, system, model)

        # Get should return from L1
        result = await semantic_cache.get(prompt, system, model)
        assert result == response

    @pytest.mark.asyncio
    async def test_get_nonexistent_returns_none(self, semantic_cache):
        """[P0] Should return None for non-existent key."""
        result = await semantic_cache.get("nonexistent", "", "model")

        assert result is None

    @pytest.mark.asyncio
    async def test_get_increments_miss_count(self, semantic_cache):
        """[P0] Should increment miss count on cache miss."""
        await semantic_cache.get("new prompt", "", "model")

        stats = semantic_cache.get_stats()
        assert stats["misses"] >= 1

    @pytest.mark.asyncio
    async def test_get_increments_hit_count(self, semantic_cache):
        """[P0] Should increment hit count on cache hit."""
        prompt = "test prompt"
        await semantic_cache.put(prompt, "response", "", "model")

        # First get
        await semantic_cache.get(prompt, "", "model")

        # Second get should be L1 hit
        await semantic_cache.get(prompt, "", "model")

        stats = semantic_cache.get_stats()
        assert stats["l1_hits"] >= 1


class TestSemanticCacheL1:
    """[P0] Tests for L1 (exact match) cache."""

    @pytest.fixture()
    def semantic_cache(self):
        """Create SemanticCache instance with high threshold to test L1-only behavior."""
        return SemanticCache(similarity_threshold=0.95)

    @pytest.mark.asyncio
    async def test_l1_size_limit(self, semantic_cache):
        """[P0] Should enforce L1 size limit."""
        # Add many entries
        for i in range(20):
            await semantic_cache.put(f"prompt-{i}", f"response-{i}", "", "model")

        # Should not exceed limit
        semantic_cache.get_stats()
        # L1 may not be full yet, but should be reasonable

    @pytest.mark.asyncio
    async def test_l1_exact_match_only(self, semantic_cache):
        """[P0] Should only match exact prompts in L1."""
        await semantic_cache.put("exact prompt", "response", "", "model")

        # Different prompt should miss
        result = await semantic_cache.get("different prompt", "", "model")
        assert result is None


class TestSemanticCacheL2:
    """[P0] Tests for L2 (semantic similarity) cache."""

    @pytest.fixture()
    def semantic_cache(self):
        """Create SemanticCache instance."""
        return SemanticCache(similarity_threshold=0.9)

    @pytest.mark.asyncio
    async def test_l2_semantic_match(self, semantic_cache):
        """[P0] Should match similar prompts in L2."""
        # Patch _text_to_embedding at class level (it's a static method)
        with patch.object(SemanticCache, "_text_to_embedding", return_value=np.array([0.5] * 384)):
            await semantic_cache.put(
                "What is artificial intelligence?",
                "AI is...",
                "",
                "model",
            )

            # Similar prompt should match
            await semantic_cache.get(
                "What is AI?",
                "",
                "model",
            )

            # May or may not match depending on similarity
            # Just verify it doesn't crash


class TestSemanticCacheStats:
    """[P1] Tests for cache statistics."""

    @pytest.fixture()
    def semantic_cache(self):
        """Create SemanticCache instance."""
        return SemanticCache()

    def test_stats_initially_zero(self, semantic_cache):
        """[P0] Should have zero stats initially."""
        stats = semantic_cache.get_stats()

        assert stats["l1_hits"] == 0
        assert stats["l2_hits"] == 0
        assert stats["misses"] == 0

    @pytest.mark.asyncio
    async def test_stats_tracks_operations(self, semantic_cache):
        """[P0] Should track cache operations."""
        await semantic_cache.put("key", "value", "", "model")
        await semantic_cache.get("key", "", "model")
        await semantic_cache.get("missing", "", "model")

        stats = semantic_cache.get_stats()

        assert stats["l1_hits"] + stats["l2_hits"] >= 1
        assert stats["misses"] >= 1


class TestSemanticCacheIntegration:
    """[P1] Integration tests for semantic cache."""

    @pytest.mark.fast
    @pytest.mark.asyncio
    @requires_real_st
    async def test_cache_workflow(self):
        """[P0] Should demonstrate complete cache workflow."""
        cache = SemanticCache(similarity_threshold=0.88)

        # Put some entries
        await cache.put("What is Python?", "Python is a language", "", "model")
        await cache.put("What is FastAPI?", "FastAPI is a framework", "", "model")

        # Get exact match
        result1 = await cache.get("What is Python?", "", "model")
        assert result1 == "Python is a language"

        # Get non-existent
        result2 = await cache.get("What is Django?", "", "model")
        assert result2 is None

        # Check stats
        stats = cache.get_stats()
        assert stats["l1_hits"] + stats["l2_hits"] >= 1
        assert stats["misses"] >= 1

        # Clear
        cache.clear()
        stats = cache.get_stats()
        assert stats["l1_hits"] == 0
        assert stats["l2_hits"] == 0


# ---------------------------------------------------------------------------
# Access Entropy diagnostic (AE1–AE5, 2026-07-04)
# ---------------------------------------------------------------------------


class TestAccessEntropy:
    """access_entropy() diagnostic — Shannon entropy of rolling access window.

    Distinguishes entropy-driven miss rates (high H → diverse workload, natural)
    from threshold misconfiguration (low H → repetitive workload, misses = alert).

    AE1: returns 0.0 when window has <2 entries
    AE2: DISCRIMINATING — low entropy for repetitive access pattern (same key always)
    AE3: DISCRIMINATING — high entropy for fully-diverse access pattern (all unique keys)
    AE4: get_stats() includes 'access_entropy' and 'combined_hit_rate' keys
    AE5: clear() resets the access window (entropy returns to 0.0)
    """

    def _make_cache(self) -> SemanticCache:
        return SemanticCache.__new__(SemanticCache)

    def _inject_window(self, cache: SemanticCache, keys: list) -> None:
        """Directly populate the access window without calling get()."""
        from collections import deque

        cache._access_window = deque(keys, maxlen=256)

    # ── AE1 ──────────────────────────────────────────────────────────────

    def test_ae1_empty_window_returns_zero(self) -> None:
        """AE1: fewer than 2 entries → 0.0 (not meaningful yet)."""
        cache = SemanticCache()
        assert cache.access_entropy() == pytest.approx(0.0)

        # Inject a single key — still < 2 entries
        cache._access_window.append("abc")
        assert cache.access_entropy() == pytest.approx(0.0)

    # ── AE2 discriminating — low entropy ─────────────────────────────────

    def test_ae2_repetitive_access_gives_low_entropy(self) -> None:
        """AE2 discriminating: same key repeated → entropy near 0.0.

        Wrong impl returning constant 0.5 would FAIL (doesn't discriminate).
        Wrong impl always returning 1.0 would FAIL (can't distinguish extremes).
        """
        cache = SemanticCache()
        # All 20 accesses are the same key
        self._inject_window(cache, ["aaaa1111"] * 20)
        entropy = cache.access_entropy()
        # H = 0 (all mass on one key), normalized = 0 / log2(20) = 0
        assert entropy == pytest.approx(0.0, abs=1e-9), (
            f"Repetitive access must give entropy≈0, got {entropy:.4f}"
        )

    # ── AE3 discriminating — high entropy ────────────────────────────────

    def test_ae3_diverse_access_gives_high_entropy(self) -> None:
        """AE3 discriminating: all unique keys → entropy near 1.0.

        Wrong impl returning constant 0.0 would FAIL.
        Wrong impl returning 0.5 always would FAIL (below 0.9).
        """
        cache = SemanticCache()
        # 32 unique keys → uniform distribution → H = log2(32) = 5 bits
        unique_keys = [f"key{i:04d}" for i in range(32)]
        self._inject_window(cache, unique_keys)
        entropy = cache.access_entropy()
        # H / log2(32) = 5/5 = 1.0 exactly for uniform distribution
        assert entropy > 0.9, (
            f"Fully diverse access must give entropy > 0.9, got {entropy:.4f}"
        )

    def test_ae3_entropy_strictly_higher_for_diverse_vs_repetitive(self) -> None:
        """AE3 discriminating (relative): diverse > repetitive (same window size).

        This is the core discriminating invariant — an impl returning a constant
        for both would FAIL.
        """
        cache = SemanticCache()
        # Repetitive: 2 keys alternating
        self._inject_window(cache, ["aaa"] * 50 + ["bbb"] * 50)
        low_entropy = cache.access_entropy()

        # Diverse: 100 unique keys
        unique_keys = [f"k{i:05d}" for i in range(100)]
        self._inject_window(cache, unique_keys)
        high_entropy = cache.access_entropy()

        assert high_entropy > low_entropy, (
            f"Diverse entropy {high_entropy:.4f} must exceed repetitive {low_entropy:.4f}"
        )

    # ── AE4 get_stats() integration ──────────────────────────────────────

    def test_ae4_get_stats_includes_required_keys(self) -> None:
        """AE4: get_stats() must include 'access_entropy' and 'combined_hit_rate'."""
        cache = SemanticCache()
        stats = cache.get_stats()
        assert "access_entropy" in stats, (
            "get_stats() must include 'access_entropy' for DegradationDetector integration"
        )
        assert "combined_hit_rate" in stats, (
            "get_stats() must include 'combined_hit_rate' (fraction, not %) for DegradationDetector"
        )

    def test_ae4_combined_hit_rate_is_fraction_not_percent(self) -> None:
        """AE4: combined_hit_rate must be [0,1] not [0,100]."""
        cache = SemanticCache()
        stats = cache.get_stats()
        # With no requests, combined_hit_rate should be 0.0 not NaN or 100.0
        assert 0.0 <= stats["combined_hit_rate"] <= 1.0, (
            f"combined_hit_rate must be a fraction [0,1], got {stats['combined_hit_rate']}"
        )

    # ── AE5 clear() resets window ────────────────────────────────────────

    def test_ae5_clear_resets_access_window(self) -> None:
        """AE5: clear() empties the access window so entropy returns to 0.0."""
        cache = SemanticCache()
        self._inject_window(cache, ["x"] * 30 + ["y"] * 30)
        assert cache.access_entropy() > 0.0  # precondition: window has data

        cache.clear()
        assert cache.access_entropy() == pytest.approx(0.0), (
            "After clear(), access window must be empty → entropy must be 0.0"
        )
