"""Tests for swarm/smart_router.py.

Generated by TEA testarch-automate workflow.
Covers SmartRouter, ModelProfile, TaskType, ModelCapability, RoutingDecision.
"""

from __future__ import annotations

import pytest

from cohezion.swarm.smart_router import (
    LOCAL_MODELS,
    TASK_REQUIREMENTS,
    AgentAction,
    ModelCapability,
    ModelProfile,
    RoutingDecision,
    SmartRouter,
    TaskType,
)


class TestTaskType:
    """[P1] Unit tests for TaskType enum."""

    def test_task_types_exist(self):
        """[P0] Should have all task types defined."""
        assert TaskType.ANALYSIS.value == "analysis"
        assert TaskType.SYNTHESIS.value == "synthesis"
        assert TaskType.CREATIVE.value == "creative"
        assert TaskType.CODING.value == "coding"
        assert TaskType.FACTUAL.value == "factual"
        assert TaskType.DEBATE.value == "debate"
        assert TaskType.SUMMARY.value == "summary"


class TestModelCapability:
    """[P1] Unit tests for ModelCapability enum."""

    def test_capabilities_exist(self):
        """[P0] Should have all capabilities defined."""
        assert ModelCapability.FAST.value == "fast"
        assert ModelCapability.ACCURATE.value == "accurate"
        assert ModelCapability.CREATIVE.value == "creative"
        assert ModelCapability.LARGE_CONTEXT.value == "large_context"
        assert ModelCapability.CODING.value == "coding"


class TestModelProfile:
    """[P0] Unit tests for ModelProfile dataclass."""

    def test_profile_creation(self):
        """[P0] Should create model profile."""
        profile = ModelProfile(
            name="test-model",
            capabilities=[ModelCapability.FAST],
            context_length=4096,
            speed_tier=1,
            quality_tier=3,
        )

        assert profile.name == "test-model"
        assert profile.capabilities == [ModelCapability.FAST]
        assert profile.context_length == 4096
        assert profile.speed_tier == 1
        assert profile.quality_tier == 3

    def test_efficiency_score(self):
        """[P0] Should calculate efficiency score."""
        profile = ModelProfile(
            name="test-model",
            capabilities=[ModelCapability.FAST],
            context_length=4096,
            speed_tier=2,
            quality_tier=4,
        )

        # efficiency = quality / speed
        assert profile.efficiency_score == pytest.approx(2.0)

    def test_high_efficiency(self):
        """[P1] Should have high efficiency for fast, quality models."""
        fast_quality = ModelProfile(
            name="fast-quality",
            capabilities=[ModelCapability.FAST, ModelCapability.ACCURATE],
            context_length=8192,
            speed_tier=1,
            quality_tier=5,
        )

        assert fast_quality.efficiency_score == pytest.approx(5.0)


class TestLocalModels:
    """[P0] Unit tests for LOCAL_MODELS constant."""

    def test_models_defined(self):
        """[P0] Should have local models defined."""
        assert len(LOCAL_MODELS) > 0

    def test_qwen_models_exist(self):
        """[P0] Should have Qwen models."""
        assert "qwen3-coder-next:q8_0" in LOCAL_MODELS
        assert "qwen3-coder:30b" in LOCAL_MODELS

    def test_phi_models_exist(self):
        """[P0] Should have Phi models."""
        assert "phi4:latest" in LOCAL_MODELS
        assert "phi4-256k:latest" in LOCAL_MODELS

    def test_models_have_capabilities(self):
        """[P0] All models should have capabilities."""
        for _name, profile in LOCAL_MODELS.items():
            assert len(profile.capabilities) > 0
            assert profile.context_length > 0


class TestTaskRequirements:
    """[P0] Unit tests for TASK_REQUIREMENTS mapping."""

    def test_analysis_requires_accurate(self):
        """[P0] Analysis tasks require accurate capability."""
        assert ModelCapability.ACCURATE in TASK_REQUIREMENTS[TaskType.ANALYSIS]

    def test_coding_requires_coding(self):
        """[P0] Coding tasks require coding capability."""
        assert ModelCapability.CODING in TASK_REQUIREMENTS[TaskType.CODING]

    def test_synthesis_requires_large_context(self):
        """[P0] Synthesis tasks require large context."""
        assert ModelCapability.LARGE_CONTEXT in TASK_REQUIREMENTS[TaskType.SYNTHESIS]

    def test_summary_requires_fast(self):
        """[P0] Summary tasks require fast capability."""
        assert ModelCapability.FAST in TASK_REQUIREMENTS[TaskType.SUMMARY]


class TestSmartRouterInitialization:
    """[P0] Unit tests for SmartRouter initialization."""

    def test_router_initialization(self):
        """[P0] Should initialize router."""
        router = SmartRouter()

        assert router is not None
        assert router.ollama_host == "http://localhost:13305"
        assert router.strategy == "efficiency"
        assert router.log_actions is True

    def test_router_with_custom_strategy(self):
        """[P0] Should accept custom strategy."""
        router = SmartRouter(strategy="quality")

        assert router.strategy == "quality"

    def test_router_with_custom_host(self):
        """[P0] Should accept custom host."""
        router = SmartRouter(ollama_host="http://custom:11434")

        assert router.ollama_host == "http://custom:11434"

    def test_router_action_log_dir(self):
        """[P0] Should have action log directory."""
        router = SmartRouter()

        assert router.action_log_dir.exists()


class TestSmartRouterClassifyTask:
    """[P0] Unit tests for task classification."""

    def test_classify_coding_task(self):
        """[P0] Should classify coding tasks."""
        router = SmartRouter()

        task_type = router.classify_task("Write a Python function to sort data")

        assert task_type == TaskType.CODING

    def test_classify_analysis_task(self):
        """[P0] Should classify analysis tasks."""
        router = SmartRouter()

        task_type = router.classify_task("Analyze the performance of this code")

        assert task_type == TaskType.ANALYSIS

    def test_classify_factual_task(self):
        """[P0] Should classify factual tasks."""
        router = SmartRouter()

        task_type = router.classify_task("What is the fact about this?")

        assert task_type == TaskType.FACTUAL

    def test_classify_summary_task(self):
        """[P0] Should classify summary tasks."""
        router = SmartRouter()

        task_type = router.classify_task("Summarize this document")

        assert task_type == TaskType.SUMMARY

    def test_classify_creative_task(self):
        """[P0] Should classify creative tasks."""
        router = SmartRouter()

        task_type = router.classify_task("Write a poem about the stars")

        assert task_type == TaskType.CREATIVE

    def test_classify_debate_task(self):
        """[P0] Should classify debate tasks."""
        router = SmartRouter()

        task_type = router.classify_task("Debate the pros and cons of AI")

        assert task_type == TaskType.DEBATE

    def test_classify_default_to_analysis(self):
        """[P1] Should default to analysis for unknown tasks."""
        router = SmartRouter()

        task_type = router.classify_task("Some random text")

        assert task_type == TaskType.ANALYSIS


class TestRoutingDecision:
    """[P0] Unit tests for RoutingDecision dataclass."""

    def test_decision_creation(self):
        """[P0] Should create routing decision."""
        decision = RoutingDecision(
            task_type=TaskType.CODING,
            selected_model="qwen3-coder:30b",
            reasoning="Best match for coding task",
            fallback_models=["qwen3-coder:14b"],
            confidence=0.95,
        )

        assert decision.task_type == TaskType.CODING
        assert decision.selected_model == "qwen3-coder:30b"
        assert decision.reasoning == "Best match for coding task"
        assert decision.fallback_models == ["qwen3-coder:14b"]
        assert decision.confidence == 0.95

    def test_decision_is_dict_serializable(self):
        """[P1] Should be serializable."""
        from dataclasses import asdict

        decision = RoutingDecision(
            task_type=TaskType.ANALYSIS,
            selected_model="phi4:latest",
            reasoning="Accurate model",
            fallback_models=[],
            confidence=0.8,
        )

        data = asdict(decision)

        assert data["selected_model"] == "phi4:latest"
        assert data["confidence"] == 0.8


class TestAgentAction:
    """[P1] Unit tests for AgentAction dataclass."""

    def test_action_creation(self):
        """[P0] Should create agent action."""
        action = AgentAction(
            timestamp="2024-01-01T00:00:00",
            agent_type="coding",
            model="qwen3-coder:30b",
            task_type="coding",
            input_tokens=100,
            output_tokens=50,
            duration_ms=500.0,
            success=True,
        )

        assert action.agent_type == "coding"
        assert action.model == "qwen3-coder:30b"
        assert action.success is True

    def test_action_to_dict(self):
        """[P1] Should convert to dict."""
        action = AgentAction(
            timestamp="2024-01-01T00:00:00",
            agent_type="analysis",
            model="phi4:latest",
            task_type="analysis",
            input_tokens=200,
            output_tokens=100,
            duration_ms=1000.0,
            success=True,
            metadata={"task_id": "123"},
        )

        data = action.to_dict()

        assert data["agent_type"] == "analysis"
        assert data["metadata"]["task_id"] == "123"


class TestSmartRouterRoute:
    """[P0] Unit tests for route method."""

    def test_route_returns_decision(self):
        """[P0] Should return routing decision."""
        router = SmartRouter()
        # Add some available models
        router.available_models = {
            "qwen3-coder:30b": LOCAL_MODELS["qwen3-coder:30b"],
        }

        decision = router.route(TaskType.CODING)

        assert isinstance(decision, RoutingDecision)
        assert decision.task_type == TaskType.CODING
        assert decision.selected_model is not None

    def test_route_with_no_models_uses_fallback(self):
        """[P0] Should use fallback when no models available."""
        router = SmartRouter()
        # No available models

        decision = router.route(TaskType.CODING)

        assert isinstance(decision, RoutingDecision)
        assert "fallback" in decision.reasoning.lower()

    def test_route_with_efficiency_strategy(self):
        """[P1] Should use efficiency strategy."""
        router = SmartRouter(strategy="efficiency")
        router.available_models = {
            "qwen3-coder:30b": LOCAL_MODELS["qwen3-coder:30b"],
            "phi4:latest": LOCAL_MODELS["phi4:latest"],
        }

        decision = router.route(TaskType.CODING)

        assert isinstance(decision, RoutingDecision)

    def test_route_with_quality_strategy(self):
        """[P1] Should use quality strategy."""
        router = SmartRouter(strategy="quality")
        router.available_models = {
            "qwen3-coder:30b": LOCAL_MODELS["qwen3-coder:30b"],
            "phi4:latest": LOCAL_MODELS["phi4:latest"],
        }

        decision = router.route(TaskType.ANALYSIS)

        assert isinstance(decision, RoutingDecision)

    def test_route_with_speed_strategy(self):
        """[P1] Should use speed strategy."""
        router = SmartRouter(strategy="speed")
        router.available_models = {
            "qwen3-coder:30b": LOCAL_MODELS["qwen3-coder:30b"],
            "phi3:mini": LOCAL_MODELS["phi3:mini"],
        }

        decision = router.route(TaskType.SUMMARY)

        assert isinstance(decision, RoutingDecision)


class TestSmartRouterActionLogging:
    """[P1] Unit tests for action logging."""

    def test_action_log_created(self):
        """[P1] Should have action log list."""
        router = SmartRouter()

        assert isinstance(router.action_log, list)

    def test_router_can_log_actions(self):
        """[P1] Should be able to log actions."""
        router = SmartRouter()
        router.log_actions = True

        # Just verify the flag is set
        assert router.log_actions is True


class TestSmartRouterGetRouter:
    """[P0] Unit tests for get_router factory."""

    @pytest.mark.asyncio
    async def test_get_router_returns_instance(self):
        """[P0] Should return SmartRouter instance."""
        from cohezion.swarm.smart_router import get_router

        router = await get_router()

        assert isinstance(router, SmartRouter)


class TestSmartRouterIntegration:
    """[P1] Integration tests for SmartRouter."""

    @pytest.mark.fast
    def test_end_to_end_routing(self):
        """[P0] Should demonstrate complete routing workflow."""
        router = SmartRouter()

        # Add some available models
        router.available_models = {
            "qwen3-coder:30b": LOCAL_MODELS["qwen3-coder:30b"],
            "phi4:latest": LOCAL_MODELS["phi4:latest"],
        }

        # Classify task
        task_text = "Write a Python function to calculate factorial"
        task_type = router.classify_task(task_text)
        assert task_type == TaskType.CODING

        # Route task
        decision = router.route(task_type)
        assert isinstance(decision, RoutingDecision)
        assert decision.task_type == TaskType.CODING
        assert decision.confidence > 0

    @pytest.mark.fast
    def test_routing_with_different_tasks(self):
        """[P1] Should route different tasks appropriately."""
        router = SmartRouter()
        router.available_models = {
            "qwen3-coder:30b": LOCAL_MODELS["qwen3-coder:30b"],
            "phi4:latest": LOCAL_MODELS["phi4:latest"],
            "deepseek-r1:7b": LOCAL_MODELS["deepseek-r1:7b"],
        }

        # Test different task types
        tasks = [
            ("Write code", TaskType.CODING),
            ("Analyze data", TaskType.ANALYSIS),
            ("What is the fact about this", TaskType.FACTUAL),
            ("Summarize this", TaskType.SUMMARY),
        ]

        for text, expected_type in tasks:
            classified = router.classify_task(text)
            assert classified == expected_type

            decision = router.route(classified)
            assert isinstance(decision, RoutingDecision)

    @pytest.mark.fast
    def test_model_scoring_by_strategy(self):
        """[P1] Should score models according to strategy."""
        router = SmartRouter(strategy="quality")
        router.available_models = {
            "qwen3-coder:30b": LOCAL_MODELS["qwen3-coder:30b"],  # quality_tier=4
            "phi3:mini": LOCAL_MODELS["phi3:mini"],  # quality_tier=2
        }

        decision = router.route(TaskType.ANALYSIS)

        # Should select higher quality model
        assert decision.selected_model in router.available_models
