"""Tests for universe/sandbox.py.

Generated by TEA testarch-automate workflow.
Covers ContainerizedUniverse and SandboxResult.
"""

from __future__ import annotations

from unittest.mock import MagicMock, patch

import pytest

from cohezion.universe.sandbox import (
    ContainerizedUniverse,
    SandboxResult,
)


class TestSandboxResult:
    """[P1] Unit tests for SandboxResult dataclass."""

    def test_result_creation(self):
        """[P0] Should create result with required fields."""
        result = SandboxResult(
            success=True,
            exit_code=0,
            stdout="output",
            stderr="",
            duration=1.5,
        )

        assert result.success is True
        assert result.exit_code == 0
        assert result.stdout == "output"
        assert result.stderr == ""
        assert result.duration == 1.5
        assert result.output_files is None

    def test_result_with_output_files(self):
        """[P1] Should accept output files."""
        result = SandboxResult(
            success=True,
            exit_code=0,
            stdout="output",
            stderr="",
            duration=1.5,
            output_files={"file.txt": b"content"},
        )

        assert result.output_files == {"file.txt": b"content"}


class TestContainerizedUniverseInitialization:
    """[P0] Unit tests for ContainerizedUniverse initialization."""

    @pytest.fixture()
    def mock_docker_client(self):
        """Create mock Docker client."""
        with patch("cohezion.universe.sandbox.docker.from_env") as mock_from_env:
            mock_client = MagicMock()
            mock_from_env.return_value = mock_client
            yield mock_client

    def test_default_initialization(self, mock_docker_client):
        """[P0] Should initialize with default parameters."""
        universe = ContainerizedUniverse()

        assert universe.image_name == "python:3.11-slim"
        assert universe.memory_limit == "512m"
        assert universe.cpu_quota == 50000
        assert universe.timeout_seconds == 300
        assert universe.network_mode == "bridge"

    def test_custom_initialization(self, mock_docker_client):
        """[P0] Should accept custom parameters."""
        universe = ContainerizedUniverse(
            image_name="custom:tag",
            memory_limit="1g",
            cpu_quota=100000,
            timeout_seconds=600,
            network_mode="host",
        )

        assert universe.image_name == "custom:tag"
        assert universe.memory_limit == "1g"
        assert universe.cpu_quota == 100000
        assert universe.timeout_seconds == 600
        assert universe.network_mode == "host"

    def test_initialization_with_profile(self, mock_docker_client):
        """[P0] Should accept sandbox profile."""
        mock_profile = MagicMock()
        mock_profile.to_docker_memory_str.return_value = "256m"
        mock_profile.cpu_quota_percent = 25  # 25% of one core
        mock_profile.timeout_seconds = 120
        mock_profile.network_enabled = False

        with patch("cohezion.universe.sandbox_profiles.SandboxProfile") as mock_profile_class:
            mock_profile_class.return_value = mock_profile
            mock_profile.__class__ = mock_profile_class

            universe = ContainerizedUniverse(profile=mock_profile)

            assert universe.memory_limit == "256m"
            assert universe.cpu_quota == 25000  # 25% * 1000
            assert universe.timeout_seconds == 120
            assert universe.network_mode == "none"

    def test_docker_connection_failure(self):
        """[P0] Should raise error when Docker unavailable."""
        with patch(
            "cohezion.universe.sandbox.docker.from_env", side_effect=Exception("Docker not found")
        ):
            with pytest.raises(RuntimeError) as exc_info:
                ContainerizedUniverse()

            assert "Docker is required" in str(exc_info.value)


class TestContainerizedUniverseExecution:
    """[P0] Unit tests for ContainerizedUniverse code execution."""

    @pytest.fixture()
    def mock_container(self):
        """Create mock Docker container."""
        container = MagicMock()
        container.id = "abc123"
        container.wait.return_value = {"StatusCode": 0}
        container.logs.return_value = b"stdout output"
        return container

    @pytest.fixture()
    def mock_docker_client(self, mock_container):
        """Create mock Docker client with container."""
        with patch("cohezion.universe.sandbox.docker.from_env") as mock_from_env:
            mock_client = MagicMock()
            mock_client.containers.create.return_value = mock_container
            mock_from_env.return_value = mock_client
            yield mock_client

    def test_execute_code_success(self, mock_docker_client, mock_container):
        """[P0] Should execute code successfully."""
        universe = ContainerizedUniverse()
        mock_container.wait.return_value = {"StatusCode": 0}
        mock_container.logs.side_effect = [b"stdout output", b"stderr output"]

        result = universe._sync_execute("print('hello')")

        assert isinstance(result, SandboxResult)
        assert result.success is True
        assert result.exit_code == 0
        assert result.stdout == "stdout output"
        assert result.stderr == "stderr output"

    def test_execute_code_failure(self, mock_docker_client, mock_container):
        """[P0] Should handle execution failure."""
        universe = ContainerizedUniverse()
        mock_container.wait.return_value = {"StatusCode": 1}
        mock_container.logs.side_effect = [b"", b"Error occurred"]

        result = universe._sync_execute("exit(1)")

        assert result.success is False
        assert result.exit_code == 1

    def test_execute_code_with_files(self, mock_docker_client, mock_container):
        """[P0] Should include additional files."""
        universe = ContainerizedUniverse()
        mock_container.wait.return_value = {"StatusCode": 0}
        mock_container.logs.side_effect = [b"", b""]

        files = {"data.txt": "sample data", "script.py": "# script"}
        universe._sync_execute("print('hello')", files=files)

        # Verify container was created
        mock_docker_client.containers.create.assert_called_once()

    def test_execute_code_with_environment(self, mock_docker_client, mock_container):
        """[P0] Should set environment variables."""
        universe = ContainerizedUniverse()
        mock_container.wait.return_value = {"StatusCode": 0}
        mock_container.logs.side_effect = [b"", b""]

        env = {"VAR1": "value1", "VAR2": "value2"}
        universe._sync_execute("print('hello')", env=env)

        # Check container creation includes environment
        call_kwargs = mock_docker_client.containers.create.call_args[1]
        assert call_kwargs["environment"] == env

    def test_execute_code_without_network(self, mock_docker_client, mock_container):
        """[P0] Should disable network when specified."""
        universe = ContainerizedUniverse(network_mode="none")
        mock_container.wait.return_value = {"StatusCode": 0}
        mock_container.logs.side_effect = [b"", b""]

        universe._sync_execute("print('hello')")

        # Check network mode was set
        call_kwargs = mock_docker_client.containers.create.call_args[1]
        assert call_kwargs.get("network_mode") == "none"


class TestContainerizedUniverseResourceLimits:
    """[P0] Unit tests for resource limiting."""

    @pytest.fixture()
    def mock_docker_client(self):
        """Create mock Docker client."""
        with patch("cohezion.universe.sandbox.docker.from_env") as mock_from_env:
            mock_client = MagicMock()
            mock_from_env.return_value = mock_client
            yield mock_client

    @pytest.fixture()
    def mock_container(self, mock_docker_client):
        """Create mock container."""
        container = MagicMock()
        container.wait.return_value = {"StatusCode": 0}
        container.logs.side_effect = [b"", b""]
        mock_docker_client.containers.create.return_value = container
        return container

    def test_memory_limit_applied(self, mock_docker_client, mock_container):
        """[P0] Should apply memory limit to container."""
        universe = ContainerizedUniverse(memory_limit="256m")
        universe._sync_execute("print('hello')")

        call_kwargs = mock_docker_client.containers.create.call_args[1]
        assert call_kwargs["mem_limit"] == "256m"

    def test_cpu_quota_applied(self, mock_docker_client, mock_container):
        """[P0] Should apply CPU quota to container."""
        universe = ContainerizedUniverse(cpu_quota=25000)  # 25%
        universe._sync_execute("print('hello')")

        call_kwargs = mock_docker_client.containers.create.call_args[1]
        assert call_kwargs["cpu_quota"] == 25000

    def test_working_directory_set(self, mock_docker_client, mock_container):
        """[P0] Should set working directory."""
        universe = ContainerizedUniverse()
        universe._sync_execute("print('hello')")

        call_kwargs = mock_docker_client.containers.create.call_args[1]
        assert call_kwargs["working_dir"] == "/app"

    def test_command_set(self, mock_docker_client, mock_container):
        """[P0] Should set container command."""
        universe = ContainerizedUniverse()
        universe._sync_execute("print('hello')")

        mock_docker_client.containers.create.call_args[0]
        call_kwargs = mock_docker_client.containers.create.call_args[1]
        assert call_kwargs["command"] == "python main.py"


class TestContainerizedUniverseErrorHandling:
    """[P0] Unit tests for error handling."""

    @pytest.fixture()
    def mock_docker_client(self):
        """Create mock Docker client."""
        with patch("cohezion.universe.sandbox.docker.from_env") as mock_from_env:
            mock_client = MagicMock()
            mock_from_env.return_value = mock_client
            yield mock_client

    def test_execution_exception_handled(self, mock_docker_client):
        """[P0] Should handle execution exceptions gracefully."""
        mock_docker_client.containers.create.side_effect = Exception("Docker error")

        universe = ContainerizedUniverse()
        result = universe._sync_execute("print('hello')")

        assert result.success is False
        assert result.exit_code == -1
        assert "Docker error" in result.stderr

    def test_container_always_removed(self, mock_docker_client):
        """[P0] Should always remove container after execution."""
        mock_container = MagicMock()
        mock_docker_client.containers.create.return_value = mock_container

        universe = ContainerizedUniverse()
        universe._sync_execute("print('hello')")

        # Verify remove was called
        mock_container.remove.assert_called_once_with(force=True)

    def test_container_removed_on_failure(self, mock_docker_client):
        """[P0] Should remove container even on failure."""
        mock_container = MagicMock()
        mock_container.wait.return_value = {"StatusCode": 1}
        mock_container.logs.side_effect = [b"", b"Error"]
        mock_docker_client.containers.create.return_value = mock_container

        universe = ContainerizedUniverse()
        universe._sync_execute("exit(1)")

        # Container should still be removed
        mock_container.remove.assert_called_once_with(force=True)

    def test_container_removal_error_handled(self, mock_docker_client):
        """[P1] Should handle container removal errors gracefully."""
        mock_container = MagicMock()
        mock_container.wait.return_value = {"StatusCode": 0}
        mock_container.logs.side_effect = [b"", b""]
        mock_container.remove.side_effect = Exception("Removal failed")
        mock_docker_client.containers.create.return_value = mock_container

        universe = ContainerizedUniverse()
        # Should not raise
        result = universe._sync_execute("print('hello')")

        assert result.success is True


class TestContainerizedUniverseOutputExtraction:
    """[P0] Unit tests for output file extraction."""

    @pytest.fixture()
    def mock_docker_client(self):
        """Create mock Docker client."""
        with patch("cohezion.universe.sandbox.docker.from_env") as mock_from_env:
            mock_client = MagicMock()
            mock_from_env.return_value = mock_client
            yield mock_client

    def test_extract_output_files_success(self, mock_docker_client):
        """[P0] Should extract output files from container."""
        import io
        import tarfile

        universe = ContainerizedUniverse()

        # Create mock container with output files
        mock_container = MagicMock()

        # Create tar archive with files
        file_obj = io.BytesIO()
        with tarfile.open(fileobj=file_obj, mode="w") as tar:
            # Add files with output/ prefix
            for name, content in [("file1.txt", b"content1"), ("file2.txt", b"content2")]:
                tarinfo = tarfile.TarInfo(f"output/{name}")
                tarinfo.size = len(content)
                tar.addfile(tarinfo, io.BytesIO(content))

        file_obj.seek(0)
        mock_container.get_archive.return_value = ([file_obj.read()], None)

        output_files = universe._extract_output_files(mock_container)

        assert output_files is not None
        assert "file1.txt" in output_files
        assert "file2.txt" in output_files
        assert output_files["file1.txt"] == b"content1"

    def test_extract_output_files_handles_no_output(self, mock_docker_client):
        """[P0] Should handle missing output directory gracefully."""
        mock_container = MagicMock()
        mock_container.get_archive.side_effect = Exception("No such file")

        universe = ContainerizedUniverse()
        output_files = universe._extract_output_files(mock_container)

        assert output_files is None

    def test_extract_output_files_empty_directory(self, mock_docker_client):
        """[P1] Should handle empty output directory."""
        import io
        import tarfile

        universe = ContainerizedUniverse()
        mock_container = MagicMock()

        # Create empty tar
        file_obj = io.BytesIO()
        with tarfile.open(fileobj=file_obj, mode="w"):
            pass

        file_obj.seek(0)
        mock_container.get_archive.return_value = ([file_obj.read()], None)

        output_files = universe._extract_output_files(mock_container)

        # Should return None for empty directory
        assert output_files is None


class TestContainerizedUniverseImageManagement:
    """[P1] Unit tests for Docker image management."""

    @pytest.fixture()
    def mock_docker_client(self):
        """Create mock Docker client."""
        with patch("cohezion.universe.sandbox.docker.from_env") as mock_from_env:
            mock_client = MagicMock()
            mock_from_env.return_value = mock_client
            yield mock_client

    def test_prepare_container_image_exists(self, mock_docker_client):
        """[P1] Should not pull if image exists."""
        universe = ContainerizedUniverse()

        # Image exists
        mock_docker_client.images.get.return_value = MagicMock()

        universe._prepare_container()

        # Should not call pull
        mock_docker_client.images.pull.assert_not_called()

    def test_prepare_container_pulls_missing_image(self, mock_docker_client):
        """[P1] Should pull image if not found."""
        universe = ContainerizedUniverse()

        # Image does not exist
        import docker.errors

        mock_docker_client.images.get.side_effect = docker.errors.ImageNotFound("not found")

        universe._prepare_container()

        # Should call pull
        mock_docker_client.images.pull.assert_called_once_with("python:3.11-slim")


class TestAsyncExecution:
    """[P0] Unit tests for async execution."""

    @pytest.fixture()
    def mock_docker_client(self):
        """Create mock Docker client."""
        with patch("cohezion.universe.sandbox.docker.from_env") as mock_from_env:
            mock_client = MagicMock()
            mock_from_env.return_value = mock_client
            yield mock_client

    @pytest.fixture()
    def mock_container(self, mock_docker_client):
        """Create mock container."""
        container = MagicMock()
        container.wait.return_value = {"StatusCode": 0}
        container.logs.side_effect = [b"", b""]
        mock_docker_client.containers.create.return_value = container
        return container

    @pytest.mark.asyncio
    async def test_execute_code_async(self, mock_docker_client, mock_container):
        """[P0] Should support async execution."""
        universe = ContainerizedUniverse()

        result = await universe.execute_code("print('hello')")

        assert isinstance(result, SandboxResult)
        assert result.success is True

    @pytest.mark.asyncio
    async def test_execute_code_async_with_files(self, mock_docker_client, mock_container):
        """[P0] Should pass files through async interface."""
        universe = ContainerizedUniverse()

        files = {"data.txt": "content"}
        result = await universe.execute_code("print('hello')", files=files)

        assert result.success is True


class TestSandboxIntegration:
    """[P1] Integration tests for sandbox functionality."""

    @pytest.mark.fast
    def test_full_execution_workflow(self):
        """[P1] Should demonstrate complete execution workflow."""
        with patch("cohezion.universe.sandbox.docker.from_env") as mock_from_env:
            # Setup mocks
            mock_client = MagicMock()
            mock_container = MagicMock()
            mock_container.wait.return_value = {"StatusCode": 0}
            mock_container.logs.side_effect = [b"Hello World", b""]
            mock_client.containers.create.return_value = mock_container
            mock_client.images.get.return_value = MagicMock()
            mock_from_env.return_value = mock_client

            # Execute
            universe = ContainerizedUniverse()
            result = universe._sync_execute("print('Hello World')")

            # Verify
            assert result.success is True
            assert result.exit_code == 0
            assert result.stdout == "Hello World"
            assert "Hello World" in result.stdout

            # Verify cleanup
            mock_container.remove.assert_called_once_with(force=True)

    @pytest.mark.fast
    def test_resource_limits_applied(self):
        """[P1] Should apply all resource limits."""
        with patch("cohezion.universe.sandbox.docker.from_env") as mock_from_env:
            mock_client = MagicMock()
            mock_container = MagicMock()
            mock_container.wait.return_value = {"StatusCode": 0}
            mock_container.logs.side_effect = [b"", b""]
            mock_client.containers.create.return_value = mock_container
            mock_from_env.return_value = mock_client

            universe = ContainerizedUniverse(
                memory_limit="128m",
                cpu_quota=25000,
                timeout_seconds=60,
                network_mode="none",
            )

            universe._sync_execute("print('test')")

            # Verify resource limits
            call_kwargs = mock_client.containers.create.call_args[1]
            assert call_kwargs["mem_limit"] == "128m"
            assert call_kwargs["cpu_quota"] == 25000
            assert call_kwargs["network_mode"] == "none"
