"""Tests for universe/schema.py.

Generated by TEA testarch-automate workflow.
Covers SurrealDB schema definitions and migrations.
"""

from __future__ import annotations

import pytest

from cohezion.universe.schema import (
    LOCAL_SCHEMA,
    MIGRATIONS,
    UNIVERSE_SCHEMA,
)


class TestUniverseSchema:
    """[P0] Unit tests for UNIVERSE_SCHEMA."""

    def test_schema_is_string(self):
        """[P0] Should be a string."""
        assert isinstance(UNIVERSE_SCHEMA, str)
        assert len(UNIVERSE_SCHEMA) > 0

    def test_schema_contains_table_definitions(self):
        """[P0] Should define universe_journey table."""
        assert "DEFINE TABLE universe_journey" in UNIVERSE_SCHEMA

    def test_schema_contains_axiomatic_state_table(self):
        """[P0] Should define axiomatic_state table."""
        assert "DEFINE TABLE axiomatic_state" in UNIVERSE_SCHEMA

    def test_schema_contains_latent_state_table(self):
        """[P0] Should define latent_state table."""
        assert "DEFINE TABLE latent_state" in UNIVERSE_SCHEMA

    def test_schema_contains_trajectory_table(self):
        """[P0] Should define trajectory_point table."""
        assert "DEFINE TABLE trajectory_point" in UNIVERSE_SCHEMA

    def test_schema_contains_coherence_table(self):
        """[P0] Should define coherence_measurement table."""
        assert "DEFINE TABLE coherence_measurement" in UNIVERSE_SCHEMA

    def test_schema_contains_precipitation_table(self):
        """[P0] Should define precipitation table."""
        assert "DEFINE TABLE precipitation" in UNIVERSE_SCHEMA

    def test_schema_contains_knowledge_table(self):
        """[P0] Should define knowledge_extract table."""
        assert "DEFINE TABLE knowledge_extract" in UNIVERSE_SCHEMA

    def test_schema_contains_reward_table(self):
        """[P0] Should define reward_ledger table."""
        assert "DEFINE TABLE reward_ledger" in UNIVERSE_SCHEMA

    def test_schema_contains_achievement_table(self):
        """[P0] Should define achievement table."""
        assert "DEFINE TABLE achievement" in UNIVERSE_SCHEMA

    def test_schema_contains_evolution_table(self):
        """[P0] Should define evolution_event table."""
        assert "DEFINE TABLE evolution_event" in UNIVERSE_SCHEMA

    def test_schema_contains_generated_artifact_table(self):
        """[P0] Should define generated_artifact table."""
        assert "DEFINE TABLE generated_artifact" in UNIVERSE_SCHEMA

    def test_schema_contains_indexes(self):
        """[P0] Should define indexes on tables."""
        assert "DEFINE INDEX" in UNIVERSE_SCHEMA
        assert "idx_journey_agent" in UNIVERSE_SCHEMA
        assert "idx_journey_status" in UNIVERSE_SCHEMA

    def test_schema_contains_vector_indexes(self):
        """[P0] Should define vector indexes for embeddings."""
        assert "TYPE VECTOR DIMENSION 2048" in UNIVERSE_SCHEMA
        assert "DIST COSINE" in UNIVERSE_SCHEMA

    def test_schema_contains_functions(self):
        """[P0] Should define SurrealDB functions."""
        assert "DEFINE FUNCTION" in UNIVERSE_SCHEMA
        assert "fn::calculate_coherence" in UNIVERSE_SCHEMA
        assert "fn::find_similar_journeys" in UNIVERSE_SCHEMA

    def test_schema_all_tables_scrmless(self):
        """[P1] All tables should be SCHEMALESS."""
        # Count SCHEMALESS definitions
        schemaless_count = UNIVERSE_SCHEMA.count("SCHEMALESS")
        assert schemaless_count >= 11  # All 11 tables

    def test_schema_has_proper_structure(self):
        """[P1] Should have proper SurrealQL structure."""
        lines = UNIVERSE_SCHEMA.split("\n")

        # Should have comments
        assert any(line.strip().startswith("--") for line in lines)

        # Should have semicolons (SurrealQL statement terminators)
        assert ";" in UNIVERSE_SCHEMA


class TestMigrations:
    """[P0] Unit tests for MIGRATIONS dictionary."""

    def test_migrations_is_dict(self):
        """[P0] Should be a dictionary."""
        assert isinstance(MIGRATIONS, dict)

    def test_migrations_has_universe_journey(self):
        """[P0] Should have universe_journey migration."""
        assert "001_universe_journey" in MIGRATIONS

    def test_migrations_has_axiomatic_state(self):
        """[P0] Should have axiomatic_state migration."""
        assert "002_axiomatic_state" in MIGRATIONS

    def test_migrations_has_latent_state(self):
        """[P0] Should have latent_state migration."""
        assert "003_latent_state" in MIGRATIONS

    def test_migrations_has_trajectory(self):
        """[P0] Should have trajectory migration."""
        assert "004_trajectory" in MIGRATIONS

    def test_migrations_has_coherence(self):
        """[P0] Should have coherence migration."""
        assert "005_coherence" in MIGRATIONS

    def test_migrations_has_precipitation(self):
        """[P0] Should have precipitation migration."""
        assert "006_precipitation" in MIGRATIONS

    def test_migrations_has_knowledge(self):
        """[P0] Should have knowledge migration."""
        assert "007_knowledge" in MIGRATIONS

    def test_migrations_has_rewards(self):
        """[P0] Should have rewards migration."""
        assert "008_rewards" in MIGRATIONS

    def test_migrations_has_achievements(self):
        """[P0] Should have achievements migration."""
        assert "009_achievements" in MIGRATIONS

    def test_migrations_has_evolution(self):
        """[P0] Should have evolution migration."""
        assert "010_evolution" in MIGRATIONS

    def test_migrations_are_ordered(self):
        """[P0] Should be in sequential order."""
        keys = list(MIGRATIONS.keys())
        assert len(keys) == 10

        # Check numeric ordering
        for i, key in enumerate(keys, 1):
            assert key.startswith(f"{i:03d}_")

    def test_migrations_are_strings(self):
        """[P1] All migrations should be strings."""
        for migration in MIGRATIONS.values():
            assert isinstance(migration, str)
            assert len(migration) > 0

    def test_migrations_contain_define_table(self):
        """[P1] All migrations should define tables."""
        for name, migration in MIGRATIONS.items():
            assert "DEFINE TABLE" in migration, f"Migration {name} missing DEFINE TABLE"

    def test_migrations_contain_indexes(self):
        """[P1] All migrations should define indexes."""
        for name, migration in MIGRATIONS.items():
            assert "DEFINE INDEX" in migration, f"Migration {name} missing DEFINE INDEX"

    def test_migrations_consistent_with_full_schema(self):
        """[P1] Migrations should be consistent with full schema."""
        # Extract table names from full schema
        import re

        table_names = re.findall(r"DEFINE TABLE (\w+)", UNIVERSE_SCHEMA)
        migration_tables = []

        for migration in MIGRATIONS.values():
            tables = re.findall(r"DEFINE TABLE (\w+)", migration)
            migration_tables.extend(tables)

        # All migration tables should be in full schema
        for table in migration_tables:
            assert table in table_names, f"Table {table} in migration but not in full schema"


class TestLocalSchema:
    """[P0] Unit tests for LOCAL_SCHEMA (SQLite fallback)."""

    def test_local_schema_is_string(self):
        """[P0] Should be a string."""
        assert isinstance(LOCAL_SCHEMA, str)
        assert len(LOCAL_SCHEMA) > 0

    def test_local_schema_has_sqlite_syntax(self):
        """[P0] Should use SQLite syntax."""
        assert "CREATE TABLE IF NOT EXISTS" in LOCAL_SCHEMA

    def test_local_schema_has_universe_journey(self):
        """[P0] Should have universe_journey table."""
        assert "CREATE TABLE IF NOT EXISTS universe_journey" in LOCAL_SCHEMA

    def test_local_schema_has_axiomatic_state(self):
        """[P0] Should have axiomatic_state table."""
        assert "CREATE TABLE IF NOT EXISTS axiomatic_state" in LOCAL_SCHEMA

    def test_local_schema_has_latent_state(self):
        """[P0] Should have latent_state table."""
        assert "CREATE TABLE IF NOT EXISTS latent_state" in LOCAL_SCHEMA

    def test_local_schema_has_reward_ledger(self):
        """[P0] Should have reward_ledger table."""
        assert "CREATE TABLE IF NOT EXISTS reward_ledger" in LOCAL_SCHEMA

    def test_local_schema_has_achievement(self):
        """[P0] Should have achievement table."""
        assert "CREATE TABLE IF NOT EXISTS achievement" in LOCAL_SCHEMA

    def test_local_schema_has_indexes(self):
        """[P0] Should create indexes."""
        assert "CREATE INDEX IF NOT EXISTS" in LOCAL_SCHEMA
        assert "idx_journey_agent" in LOCAL_SCHEMA

    def test_local_schema_has_foreign_keys(self):
        """[P1] Should have foreign key references."""
        assert "REFERENCES" in LOCAL_SCHEMA
        assert "REFERENCES universe_journey" in LOCAL_SCHEMA

    def test_local_schema_has_primary_keys(self):
        """[P1] Should define primary keys."""
        assert "PRIMARY KEY" in LOCAL_SCHEMA

    def test_local_schema_uses_json_for_metadata(self):
        """[P1] Should store metadata as JSON."""
        assert "metadata TEXT -- JSON blob" in LOCAL_SCHEMA

    def test_local_schema_has_timestamps(self):
        """[P1] Should have timestamp columns."""
        assert "TIMESTAMP" in LOCAL_SCHEMA
        assert "DEFAULT CURRENT_TIMESTAMP" in LOCAL_SCHEMA


class TestSchemaCoverage:
    """[P1] Integration tests for schema completeness."""

    def test_schema_covers_all_tables(self):
        """[P1] Schema should define all required tables."""
        required_tables = [
            "universe_journey",
            "axiomatic_state",
            "latent_state",
            "trajectory_point",
            "coherence_measurement",
            "precipitation",
            "knowledge_extract",
            "reward_ledger",
            "achievement",
            "evolution_event",
            "generated_artifact",
        ]

        for table in required_tables:
            assert f"DEFINE TABLE {table}" in UNIVERSE_SCHEMA, f"Missing table: {table}"

    def test_local_schema_covers_core_tables(self):
        """[P1] Local schema should cover core tables."""
        core_tables = [
            "universe_journey",
            "axiomatic_state",
            "latent_state",
            "reward_ledger",
            "achievement",
        ]

        for table in core_tables:
            assert f"CREATE TABLE IF NOT EXISTS {table}" in LOCAL_SCHEMA

    def test_axiomatic_state_has_12d_fields(self):
        """[P0] Axiomatic state should have 12D fields."""
        # Check local schema
        assert "spatial_x REAL" in LOCAL_SCHEMA
        assert "spatial_y REAL" in LOCAL_SCHEMA
        assert "spatial_z REAL" in LOCAL_SCHEMA
        assert "temporal REAL" in LOCAL_SCHEMA
        assert "physics REAL" in LOCAL_SCHEMA
        assert "biology REAL" in LOCAL_SCHEMA
        assert "logic REAL" in LOCAL_SCHEMA
        assert "quantum REAL" in LOCAL_SCHEMA
        assert "field REAL" in LOCAL_SCHEMA
        assert "control REAL" in LOCAL_SCHEMA
        assert "novelty REAL" in LOCAL_SCHEMA
        assert "precipitation REAL" in LOCAL_SCHEMA

    def test_latent_state_has_embedding(self):
        """[P0] Latent state should have embedding field."""
        assert "embedding TEXT, -- JSON array of 512 floats" in LOCAL_SCHEMA


class TestSchemaIntegration:
    """[P1] Integration tests for schema usage patterns."""

    @pytest.mark.fast
    def test_schema_can_be_parsed(self):
        """[P1] Schema should be valid SurrealQL."""
        # Basic validation - check for balanced braces
        open_count = UNIVERSE_SCHEMA.count("{")
        close_count = UNIVERSE_SCHEMA.count("}")
        assert open_count == close_count, "Unbalanced braces in schema"

    @pytest.mark.fast
    def test_migrations_are_independent(self):
        """[P1] Each migration should be self-contained."""
        for name, migration in MIGRATIONS.items():
            # Each migration should create its own table
            assert migration.count("DEFINE TABLE") == 1, f"Migration {name} has multiple tables"

    @pytest.mark.fast
    def test_schema_coherence_function(self):
        """[P0] Coherence function should use vector similarity."""
        assert "vector::similarity::cosine" in UNIVERSE_SCHEMA

    @pytest.mark.fast
    def test_schema_similar_journeys_function(self):
        """[P0] Similar journeys function should use vector search."""
        assert "<|8|>" in UNIVERSE_SCHEMA  # SurrealDB vector search syntax

    @pytest.mark.fast
    def test_schema_and_migrations_alignment(self):
        """[P1] Schema and migrations should align."""
        # Full schema should contain all migration table definitions
        for _name, migration in MIGRATIONS.items():
            # Extract table name
            import re

            match = re.search(r"DEFINE TABLE (\w+)", migration)
            if match:
                table_name = match.group(1)
                # Should exist in full schema
                assert f"DEFINE TABLE {table_name}" in UNIVERSE_SCHEMA


class TestSchemaDocumentation:
    """[P1] Tests for schema documentation."""

    def test_universe_schema_has_docstring(self):
        """[P0] Module should have docstring."""
        from cohezion.universe import schema

        assert schema.__doc__ is not None
        assert "SurrealDB" in schema.__doc__

    def test_schema_has_comments(self):
        """[P1] Schema should have comments."""
        assert "--" in UNIVERSE_SCHEMA
        # Check for specific table comments
        assert "Core journey tracking" in UNIVERSE_SCHEMA
        assert "12D Axiomatic State" in UNIVERSE_SCHEMA

    def test_migrations_have_comments(self):
        """[P1] Migrations should have comments."""
        for name, _migration in MIGRATIONS.items():
            # Most migrations have a descriptive name
            parts = name.split("_")
            assert len(parts) >= 2  # e.g., "001_universe_journey"
