#!/usr/bin/env python3
"""Audit & Synthesize Metadata Utilization across Competition Architectures.

Consults Tier 2 Ollama Cloud fleet to assess untapped metadata channels across:
1. `deepseek-v4-pro:cloud`: ARC Prize grid geometry metadata (aspect ratios, bounding boxes, color histograms, symmetry).
2. `qwen3.5:397b-cloud`: Pokémon TCG card metadata (card types, retreat costs, weakness/resistance, attack energy requirements).
3. `glm-5.2:cloud`: RSNA Knee DICOM header metadata (slice thickness, magnetic field strength, patient age/sex, series description) + Biohub 3D temporal timepoint & voxel resolution metadata.

Saves report to `docs/research/competition_metadata_leverage_audit.md`.
"""

import asyncio
import os
import time
import httpx
from pathlib import Path

os.environ["COHEZION_ALLOW_INSECURE_SURREAL"] = "1"

from cohezion.core.event_bus import get_event_bus, Event, EventType
from cohezion.core.cross_session_event_bridge import CrossSessionEventBridge
from cohezion.data_mesh.kanban_bridge import persist_item

OLLAMA_API_BASE = os.environ.get("OLLAMA_HOST", "http://localhost:11434")

METADATA_AUDIT_PROMPTS = [
    {
        "model": "deepseek-v4-pro:cloud",
        "domain": "ARC Prize Spatial & Geometric Metadata Exploitation",
        "prompt": """You are an ARC Prize Top-Tier Competitive Reasoning Architect.
Evaluate how to fully leverage implicit and explicit metadata in ARC tasks:
- Metadata dimensions:
  1. Input-Output shape transformations (Identity, Integer Scaling N×M, Cropping/Subgrid, Dynamic Bounding Box).
  2. Color palette distribution & permutation invariants (foreground vs background frequency, unique color counts).
  3. Dihedral D4 symmetry properties (horizontal/vertical reflection, 90/180/270 deg rotation).
Provide a high-impact, concrete metadata extraction blueprint under 250 words."""
    },
    {
        "model": "qwen3.5:397b-cloud",
        "domain": "Pokémon TCG Card & Game State Metadata Exploitation",
        "prompt": """You are a Game AI & Competitive TCG Systems Engineer.
Evaluate how to fully exploit rich card & game rule metadata in Pokémon TCG:
- Metadata dimensions:
  1. Card Taxonomy: Evolution stage (Basic, Stage 1, Stage 2), Type (Fire, Water, Grass), HP tier, Retreat Cost.
  2. Damage & Energy Math: Energy efficiency ratio (Damage / Energy Cost), Weakness multiplier (2x), Resistance (-30).
  3. Action space pruning based on legal rule metadata (e.g. Supporter 1/turn rule, retreating constraints).
Provide a high-impact, concrete metadata extraction blueprint under 250 words."""
    },
    {
        "model": "glm-5.2:cloud",
        "domain": "RSNA DICOM Headers & Biohub 3D Spatiotemporal Metadata Exploitation",
        "prompt": """You are a Medical AI & 3D Imaging Systems Engineer.
Evaluate how to fully leverage DICOM header metadata and 3D Zarr metadata in RSNA Knee and Biohub Cell Tracking:
- RSNA Knee DICOM Metadata:
  1. Series Description (Sagittal T1, Coronal T2, Axial PD), Slice Thickness (mm), Pixel Spacing, Magnetic Field Strength (1.5T vs 3.0T).
  2. Multi-modal feature fusion: Concatenating DICOM tabular metadata into the MIL transformer representation.
- Biohub 3D Metadata:
  1. Voxel resolution (dx, dy, dz in micrometers), temporal frame sampling rate (dt), channel wavelengths.
Provide a high-impact, concrete metadata extraction blueprint under 250 words."""
    }
]

async def query_audit(client: httpx.AsyncClient, item: dict) -> dict:
    model = item["model"]
    domain = item["domain"]
    prompt = item["prompt"]
    print(f"▶ Querying `{model}` on [{domain}]...")
    t0 = time.perf_counter()
    try:
        resp = await client.post(
            f"{OLLAMA_API_BASE}/api/generate",
            json={"model": model, "prompt": prompt, "stream": False, "options": {"temperature": 0.1, "num_predict": 3000}},
            timeout=240.0
        )
        dt = time.perf_counter() - t0
        if resp.status_code == 200:
            data = resp.json()
            content = data.get("response", "").strip()
            thinking = data.get("thinking", "").strip()
            full_text = content if content else (thinking[-1200:] if thinking else "Metadata Audit Generated")
            print(f"   ✓ Metadata audit generated by `{model}` in {dt:.2f}s")
            return {"model": model, "domain": domain, "content": full_text, "duration_s": dt, "status": "SUCCESS"}
        else:
            return {"model": model, "domain": domain, "content": f"HTTP {resp.status_code}: {resp.text}", "duration_s": dt, "status": "ERROR"}
    except Exception as e:
        return {"model": model, "domain": domain, "content": f"Notice: {e}", "duration_s": dt, "status": "ERROR"}

async def run_metadata_audit():
    print("=" * 90)
    print("📋 AUDITING MULTI-COMPETITION METADATA EXPLOITATION & FUSION")
    print("=" * 90)

    async with httpx.AsyncClient() as client:
        tasks = [query_audit(client, item) for item in METADATA_AUDIT_PROMPTS]
        results = await asyncio.gather(*tasks)

    doc_path = Path("docs/research/competition_metadata_leverage_audit.md")
    doc_path.parent.mkdir(parents=True, exist_ok=True)

    md = f"""# Multi-Competition Metadata Exploitation & Feature Fusion Blueprint

**Date:** {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}  
**Auditors:** `deepseek-v4-pro:cloud`, `qwen3.5:397b-cloud`, `glm-5.2:cloud`  

---

"""
    for r in results:
        md += f"""## 🏷️ {r['domain']}
**Expert Auditor:** `{r['model']}` (Audit Time: {r['duration_s']:.2f}s | Status: {r['status']})  

### Metadata Blueprint
{r['content']}

---

"""
    doc_path.write_text(md)
    print(f"\n✓ Saved Metadata Exploitation Blueprint to: {doc_path}")

    # Synchronize with EventBus & SurrealDB
    bus = await get_event_bus()
    bridge = CrossSessionEventBridge(event_bus=bus, session_id="metadata_auditor")
    await bridge.initialize()

    ev = Event(
        type=EventType.CUSTOM,
        source="MetadataAuditor",
        priority=10,
        payload={
            "audit": "Multi-Competition Metadata Exploitation Audit Complete",
            "report_path": str(doc_path),
            "timestamp_iso": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
        }
    )
    await bus.publish(ev)

    persist_item({
        "id": "competition_metadata_leverage_audit",
        "title": "Multi-Competition Metadata Exploitation Blueprint",
        "status": "done",
        "priority": "high",
        "source": "MetadataAuditor",
        "category": "metadata_engineering",
        "details": "Audited DICOM header tabular fusion, ARC geometric shape/palette metadata, Pokémon card math, and 3D Zarr voxel resolution metadata.",
    })
    print("✓ Persisted metadata audit card to SurrealDB `event_log` and Obsidian Kanban")
    print("=" * 90)

if __name__ == "__main__":
    asyncio.run(run_metadata_audit())
