#!/bin/bash
#
# Weekly Security Report Generator
# Run via cron: 0 9 * * 1 /path/to/weekly_security_report.sh

set -e

cd "$(dirname "$0")/../.."

REPO="manderson240/cohezion"
REPORT_DIR="reports/security"
DATE=$(date +%Y-%m-%d)

echo "🔒 Cohezion Weekly Security Report"
echo "=================================="
echo ""

# Create report directory
mkdir -p "$REPORT_DIR"

REPORT_FILE="$REPORT_DIR/weekly-security-$DATE.md"

# Generate report header
cat > "$REPORT_FILE" << EOF
# Weekly Security Report

**Week**: $DATE  
**Repository**: $REPO  
**Generated**: $(date)

## Executive Summary

EOF

# Get code scanning alerts
echo "📊 Analyzing CodeQL alerts..."
CODEQL_COUNT=$(gh api "/repos/$REPO/code-scanning/alerts" -X GET -f state=open --jq 'length' 2>/dev/null || echo "0")
echo "- CodeQL Alerts: $CODEQL_COUNT"

# Get dependabot alerts  
echo "📊 Analyzing Dependabot alerts..."
DEPS_COUNT=$(gh api "/repos/$REPO/dependabot/alerts" -X GET -f state=open --jq 'length' 2>/dev/null || echo "0")
echo "- Dependabot Alerts: $DEPS_COUNT"

# Get open Dependabot PRs
echo "📊 Checking Dependabot PRs..."
DEPS_PRS=$(gh pr list --author "dependabot[bot]" --state open --json number --jq 'length' 2>/dev/null || echo "0")
echo "- Dependabot PRs: $DEPS_PRS"

# Get recent workflow runs
echo "📊 Checking workflow status..."
WORKFLOW_STATUS=$(gh run list --workflow=codeql.yml --limit 1 --json conclusion --jq '.[0].conclusion' 2>/dev/null || echo "unknown")
echo "- Latest CodeQL Run: $WORKFLOW_STATUS"

# Write summary
cat >> "$REPORT_FILE" << EOF
| Metric | Count | Status |
|--------|-------|--------|
| CodeQL Alerts | $CODEQL_COUNT | $([ "$CODEQL_COUNT" -eq 0 ] && echo "✅ Clean" || echo "📝 Review") |
| Dependabot Alerts | $DEPS_COUNT | $([ "$DEPS_COUNT" -eq 0 ] && echo "✅ Clean" || echo "📝 Review") |
| Dependabot PRs | $DEPS_PRS | $([ "$DEPS_PRS" -eq 0 ] && echo "✅ Clean" || echo "🔧 Action") |
| Latest CodeQL Run | $WORKFLOW_STATUS | $([ "$WORKFLOW_STATUS" = "success" ] && echo "✅ Pass" || echo "❌ Check") |

## Detailed Analysis

### CodeQL Alerts

EOF

# Get detailed code scanning data
gh api "/repos/$REPO/code-scanning/alerts" -X GET -f state=open --jq '
  group_by(.rule.security_severity_level) |
  map({
    severity: .[0].rule.security_severity_level,
    count: length,
    rules: map(.rule.id) | unique
  }) |
  sort_by(.severity)
' 2>/dev/null | jq -r '
  .[] |
  "#### \(.severity | ascii_upcase) (\(.count))\n\n" +
  "Rules:\n" +
  (.rules | map("- " + .) | join("\n"))
' >> "$REPORT_FILE" || echo "*No CodeQL alerts found*" >> "$REPORT_FILE"

# Add Dependabot section
cat >> "$REPORT_FILE" << EOF

### Dependabot Alerts

EOF

gh api "/repos/$REPO/dependabot/alerts" -X GET -f state=open --jq '
  group_by(.security_advisory.severity) |
  map({
    severity: .[0].security_advisory.severity,
    count: length,
    packages: map(.dependency.package.name) | unique
  }) |
  sort_by(.severity)
' 2>/dev/null | jq -r '
  .[] |
  "#### \(.severity | ascii_upcase) (\(.count))\n\n" +
  "Packages:\n" +
  (.packages | map("- " + .) | join("\n"))
' >> "$REPORT_FILE" || echo "*No Dependabot alerts found*" >> "$REPORT_FILE"

# Add recommendations
cat >> "$REPORT_FILE" << EOF

## Recommendations

EOF

if [ "$CODEQL_COUNT" -gt 0 ]; then
  echo "- [ ] Review and triage $CODEQL_COUNT CodeQL alerts" >> "$REPORT_FILE"
fi

if [ "$DEPS_COUNT" -gt 0 ]; then
  echo "- [ ] Address $DEPS_COUNT Dependabot security alerts" >> "$REPORT_FILE"
fi

if [ "$DEPS_PRS" -gt 0 ]; then
  echo "- [ ] Review and merge $DEPS_PRS Dependabot PRs" >> "$REPORT_FILE"
fi

cat >> "$REPORT_FILE" << EOF

## Security Metrics

### Trend Analysis

Track these metrics over time:
- Time to fix critical alerts: Target < 24 hours
- Time to fix high alerts: Target < 72 hours
- Average time to merge Dependabot PRs: Target < 7 days
- False positive rate: Target < 10%

### Compliance Status

- OWASP Top 10: Monitoring via CodeQL
- CWE Coverage: CodeQL default + custom queries
- SLSA Level 1: ✅ (Dependency tracking via Dependabot)
- SLSA Level 2: ⏳ (Future: Signed attestations)

---

*Report generated by Cohezion Security Automation*
EOF

echo ""
echo "✅ Weekly report generated: $REPORT_FILE"
