"""ShadowScripter — Autonomous Test Generation (Story 5.2, FR7).

Generates test specifications from skill refinements and Vanguard
discoveries. Validates generated tests before committing — broken
tests are quarantined and flagged for Ouroboros refinement.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from enum import Enum


logger = logging.getLogger(__name__)


class TestGenStatus(Enum):
    GENERATED = "generated"
    VALIDATED = "validated"
    QUARANTINED = "quarantined"


@dataclass
class GeneratedTest:
    """A test specification generated by ShadowScripter."""

    test_name: str
    test_code: str
    source_skill: str
    status: TestGenStatus = TestGenStatus.GENERATED
    error: str | None = None
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> dict:
        return {
            "test_name": self.test_name,
            "test_code": self.test_code,
            "source_skill": self.source_skill,
            "status": self.status.value,
            "error": self.error,
            "timestamp": self.timestamp,
        }


class ShadowScripter:
    """Generates and validates test specifications autonomously.

    Flow:
    1. Skill refinement triggers test generation
    2. Generated test is syntax-checked
    3. Valid tests are marked for commit
    4. Invalid tests are quarantined
    """

    def __init__(self) -> None:
        self._generated: list[GeneratedTest] = []
        self._quarantine: list[GeneratedTest] = []

    @property
    def generated_tests(self) -> list[GeneratedTest]:
        return list(self._generated)

    @property
    def quarantined_tests(self) -> list[GeneratedTest]:
        return list(self._quarantine)

    def generate(
        self,
        test_name: str,
        test_code: str,
        source_skill: str,
    ) -> GeneratedTest:
        """Generate a test specification and validate it."""
        test = GeneratedTest(
            test_name=test_name,
            test_code=test_code,
            source_skill=source_skill,
        )

        if self._validate_syntax(test_code):
            test.status = TestGenStatus.VALIDATED
            self._generated.append(test)
            logger.info("ShadowScripter: test %s validated", test_name)
        else:
            test.status = TestGenStatus.QUARANTINED
            test.error = "Syntax validation failed"
            self._quarantine.append(test)
            logger.warning("ShadowScripter: test %s quarantined", test_name)

        return test

    def _validate_syntax(self, code: str) -> bool:
        """Check if generated test code is syntactically valid Python."""
        try:
            compile(code, "<shadow_scripter>", "exec")
            return True
        except SyntaxError:
            return False

    def get_committable_tests(self) -> list[GeneratedTest]:
        """Return tests that passed validation and can be committed."""
        return [t for t in self._generated if t.status == TestGenStatus.VALIDATED]

    def get_quarantine_report(self) -> list[dict]:
        """Export quarantined tests for Ouroboros refinement."""
        return [t.to_dict() for t in self._quarantine]
