"""Tests for src/cohezion/compound/batch_executor.py.

Generated by cohezion.tools.test_generator.
Covers 4 classes, 0 functions.
"""

from __future__ import annotations

import inspect
from unittest.mock import MagicMock, patch

import pytest

from cohezion.compound.batch_executor import (
    BatchableExecutor,
    BatchCompoundResult,
    BatchExecutorFactory,
    CompoundTask,
)
from cohezion.compound.executor import CompoundExecutor, ExecutionResult


class TestCompoundTask:
    """[P0] Unit tests for CompoundTask class."""

    def test_initialization(self):
        """[P0] Should initialize CompoundTask."""
        task = CompoundTask(task_id="test-1", prompt="test prompt")
        assert task.task_id == "test-1"
        assert task.prompt == "test prompt"
        assert task.model == "claude-3-5-sonnet"


class TestBatchCompoundResult:
    """[P0] Unit tests for BatchCompoundResult class."""

    def test_initialization(self):
        """[P0] Should initialize BatchCompoundResult."""
        result = BatchCompoundResult(
            success=True, tasks_executed=1, tasks_failed=0, total_duration_seconds=1.0
        )
        assert result.success is True
        assert result.tasks_executed == 1


class TestBatchableExecutor:
    """[P0] Unit tests for BatchableExecutor class."""

    @pytest.fixture
    def mock_executor(self):
        return MagicMock()

    @pytest.fixture
    def mock_mcp_client(self):
        return MagicMock()

    @pytest.fixture
    def batchable_executor(self, mock_executor, mock_mcp_client):
        with patch("cohezion.compound.batch_executor.get_batch_size_predictor"):
            return BatchableExecutor(
                executor=mock_executor,
                mcp_client=mock_mcp_client,
                batch_size=4,
                enable_adaptive_batch_sizing=False,
            )

    @pytest.mark.asyncio
    async def test_execute_batch_empty(self, batchable_executor):
        """[P0] Should handle empty task list."""
        result = await batchable_executor.execute_batch([])
        assert result.success is True
        assert result.tasks_executed == 0

    @pytest.mark.asyncio
    async def test_execute_batch_basic(self, batchable_executor, mock_executor):
        """[P0] Should execute execute_batch with tasks."""
        # Arrange
        tasks = [
            CompoundTask(task_id="t1", prompt="p1"),
            CompoundTask(task_id="t2", prompt="p2"),
        ]

        # CompoundExecutor.execute_task is SYNCHRONOUS — mock it as such so the
        # real (non-awaited) call contract is exercised, not masked by AsyncMock.
        mock_executor.execute_task = MagicMock(
            return_value=ExecutionResult(
                success=True,
                output="test output",
                metrics={"tokens_used": 10},
                duration_seconds=0.5,
            )
        )

        # Act
        result = await batchable_executor.execute_batch(tasks)

        # Assert
        assert result.success is True
        assert result.tasks_executed == 2
        assert len(result.results) == 2
        assert mock_executor.execute_task.call_count == 2
        # Regression guard: the call must use the real execute_task signature.
        _, kwargs = mock_executor.execute_task.call_args
        assert set(kwargs) == {"task_description", "skill_name", "operation_type"}

    @pytest.mark.asyncio
    async def test_execute_batch_deduplication(self, batchable_executor, mock_executor):
        """[P0] Should deduplicate identical tasks."""
        # Arrange
        tasks = [
            CompoundTask(task_id="t1", prompt="identical"),
            CompoundTask(task_id="t2", prompt="identical"),
        ]

        mock_executor.execute_task = MagicMock(
            return_value=ExecutionResult(
                success=True, output="test output", metrics={}, duration_seconds=0.5
            )
        )

        # Act
        result = await batchable_executor.execute_batch(tasks)

        # Assert
        assert result.tasks_executed == 2
        assert mock_executor.execute_task.call_count == 1

    def test_sequential_call_binds_real_execute_task_signature(self):
        """[P0] The kwargs BatchableExecutor sends must bind to the REAL
        CompoundExecutor.execute_task signature. This is the structural guard the
        AsyncMock-based tests lacked — it fails loudly on future signature drift
        instead of silently swallowing a TypeError as success=False."""
        sig = inspect.signature(CompoundExecutor.execute_task)
        # Bound with a placeholder self; raises TypeError if the call is invalid.
        sig.bind(
            None,
            task_description="p",
            skill_name="t1",
            operation_type="generate",
        )


class TestBatchExecutorFactory:
    """[P0] Unit tests for BatchExecutorFactory class."""

    def test_create(self):
        """[P0] Should create BatchableExecutor via factory."""
        mock_executor = MagicMock()
        mock_mcp_client = MagicMock()

        with patch("cohezion.compound.batch_executor.get_batch_size_predictor"):
            executor = BatchExecutorFactory.create(
                executor=mock_executor, mcp_client=mock_mcp_client
            )

        assert isinstance(executor, BatchableExecutor)
        assert executor.executor == mock_executor
