"""Integration tests for compound executor with context system.

Generated by TEA testarch-automate workflow.
Tests compound executor loading and using unified context system.
"""

from __future__ import annotations

import json
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

from cohezion.compound.context_integration import (
    ContextCoherenceError,
    ContextManager,
)
from cohezion.compound.executor import CompoundExecutor, ExecutionResult
from cohezion.core.mcp_client import MCPClient


class TestCompoundExecutorContextIntegration:
    """[P0] Integration tests for CompoundExecutor with context system."""

    @pytest.fixture()
    def temp_context_structure(self, tmp_path):
        """Create temporary context structure."""
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "core").mkdir()
        (ctx_dir / "traceability").mkdir()
        (ctx_dir / "skills").mkdir()

        # Create manifest
        manifest = {
            "version": "1.0.0",
            "core_files": [
                {
                    "path": "core/syntax-rules.md",
                    "token_budget": 200,
                    "coherence_threshold": 0.5,
                    "sources": [{"file": "AGENTS.md", "commit": "abc123"}],
                }
            ],
            "skills": {
                "compound-engineering": {
                    "context_file": "skills/compound-engineering/context.yaml",
                    "token_budget": 150,
                }
            },
        }
        with open(ctx_dir / "traceability" / "manifest.json", "w") as f:
            json.dump(manifest, f)

        # Create core file
        (ctx_dir / "core" / "syntax-rules.md").write_text(
            "# Syntax Rules\n\nTest content for executor.", encoding="utf-8"
        )

        return tmp_path

    @pytest.fixture()
    def mock_mcp(self):
        """Create mock MCP client."""
        return MagicMock(spec=MCPClient)

    def test_executor_can_initialize_with_context(self, temp_context_structure, mock_mcp):
        """[P0] Should initialize executor with context manager."""
        with patch.object(Path, "cwd", return_value=temp_context_structure):
            executor = CompoundExecutor(mcp_client=mock_mcp)

            assert executor is not None
            assert executor.mcp_client == mock_mcp

    def test_executor_context_loading_on_first_execution(self, temp_context_structure, mock_mcp):
        """[P0] Should load context when first execution happens."""
        with patch.object(Path, "cwd", return_value=temp_context_structure):
            executor = CompoundExecutor(mcp_client=mock_mcp)

            # Mock VaultLogger
            executor.logger = MagicMock()
            executor.logger.get_experience_guidance.return_value = {}

            # Execute task - should trigger context loading
            result = executor.execute_task(
                task_description="Test task",
                skill_name="test-skill",
                operation_type="generate",
                execute_fn=lambda guidance: ("output", {"metric": 1.0}),
            )

            assert isinstance(result, ExecutionResult)
            assert result.success is True

    def test_executor_handles_context_coherence_error(self, temp_context_structure, mock_mcp):
        """[P0] Should handle context coherence errors gracefully."""
        with patch.object(Path, "cwd", return_value=temp_context_structure):
            executor = CompoundExecutor(mcp_client=mock_mcp)

            # Mock context manager to return low coherence
            with patch.object(
                ContextManager,
                "load_core_context",
                side_effect=ContextCoherenceError("Low coherence"),
            ):
                # Should still work even if context loading fails
                executor.logger = MagicMock()
                executor.logger.get_experience_guidance.return_value = {}

                # Execution should proceed despite context error
                result = executor.execute_task(
                    task_description="Test task",
                    skill_name="test-skill",
                    operation_type="generate",
                    execute_fn=lambda guidance: ("output", {}),
                )

                assert result.success is True

    def test_executor_tracks_context_in_metrics(self, temp_context_structure, mock_mcp):
        """[P1] Should track context state in execution metrics."""
        with patch.object(Path, "cwd", return_value=temp_context_structure):
            executor = CompoundExecutor(mcp_client=mock_mcp)
            executor.logger = MagicMock()
            executor.logger.get_experience_guidance.return_value = {}

            result = executor.execute_task(
                task_description="Test task",
                skill_name="test-skill",
                operation_type="generate",
                execute_fn=lambda guidance: ("output", {"context_loaded": True}),
            )

            assert result.metrics is not None
            assert result.success is True


class TestContextWithMetricsCollector:
    """[P1] Integration tests for context with metrics collection."""

    @pytest.fixture()
    def temp_context_with_manifest(self, tmp_path):
        """Create context structure with manifest."""
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "core").mkdir()
        (ctx_dir / "traceability").mkdir()

        manifest = {
            "version": "1.0.0",
            "core_files": [
                {
                    "path": "core/compound-patterns.md",
                    "token_budget": 300,
                    "coherence_threshold": 0.5,
                    "sources": [],
                }
            ],
            "skills": {},
        }
        with open(ctx_dir / "traceability" / "manifest.json", "w") as f:
            json.dump(manifest, f)

        (ctx_dir / "core" / "compound-patterns.md").write_text(
            "# Compound Patterns\n\nHIHO threshold: 0.5", encoding="utf-8"
        )

        return tmp_path

    def test_context_tracks_token_usage(self, temp_context_with_manifest):
        """[P0] Should track token usage after loading."""
        with patch.object(Path, "cwd", return_value=temp_context_with_manifest):
            mgr = ContextManager()
            mgr.load_core_context()

            summary = mgr.get_context_summary()

            assert summary["token_usage"] > 0
            assert summary["token_budget"] == 1000
            assert summary["core_loaded"] is True

    def test_context_coherence_state_tracked(self, temp_context_with_manifest):
        """[P1] Should track coherence state."""
        with patch.object(Path, "cwd", return_value=temp_context_with_manifest):
            mgr = ContextManager()
            mgr.load_core_context()

            assert mgr.coherence_state == 1.0
            assert mgr.check_coherence(0.5) is True
            assert mgr.check_coherence(0.9) is True

    def test_context_loaded_files_tracked(self, temp_context_with_manifest):
        """[P1] Should track which files are loaded."""
        with patch.object(Path, "cwd", return_value=temp_context_with_manifest):
            mgr = ContextManager()
            mgr.load_core_context()

            assert len(mgr.loaded_files) == 1
            assert "compound-patterns.md" in mgr.loaded_files[0]


class TestContextWithSkillLoading:
    """[P1] Integration tests for skill-specific context loading."""

    @pytest.fixture()
    def temp_context_with_skills(self, tmp_path):
        """Create context structure with skill configs."""
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "core").mkdir()
        (ctx_dir / "traceability").mkdir()
        (ctx_dir / "skills" / "compound-engineering").mkdir(parents=True)

        # Core manifest
        manifest = {
            "version": "1.0.0",
            "core_files": [],
            "skills": {
                "compound-engineering": {
                    "context_file": "skills/compound-engineering/context.yaml",
                    "auto_load": False,
                    "triggers": ["compound", "skill refinement"],
                }
            },
        }
        with open(ctx_dir / "traceability" / "manifest.json", "w") as f:
            json.dump(manifest, f)

        # Skill context
        skill_config = {
            "skill": "compound-engineering",
            "description": "Context for compound engineering",
            "entry_point": "src/cohezion/compound/executor.py",
            "token_budget": 150,
        }
        import yaml

        with open(ctx_dir / "skills" / "compound-engineering" / "context.yaml", "w") as f:
            yaml.dump(skill_config, f)

        return tmp_path

    def test_skill_context_loaded_on_demand(self, temp_context_with_skills):
        """[P0] Should load skill context when requested."""

        with patch.object(Path, "cwd", return_value=temp_context_with_skills):
            mgr = ContextManager()

            # Load skill context on demand
            config = mgr.load_skill_context("compound-engineering")

            assert config is not None
            assert config["skill"] == "compound-engineering"
            assert config["token_budget"] == 150

    def test_skill_context_not_found_returns_none(self, temp_context_with_skills):
        """[P1] Should return None for unknown skill."""
        with patch.object(Path, "cwd", return_value=temp_context_with_skills):
            mgr = ContextManager()

            config = mgr.load_skill_context("unknown-skill")

            assert config is None

    def test_skill_context_without_manifest_entry(self, temp_context_with_skills):
        """[P1] Should handle skill not in manifest."""
        with patch.object(Path, "cwd", return_value=temp_context_with_skills):
            mgr = ContextManager()

            # Modify manifest to remove skill entry
            manifest_path = temp_context_with_skills / ".context" / "traceability" / "manifest.json"
            manifest = json.loads(manifest_path.read_text())
            manifest["skills"] = {}
            manifest_path.write_text(json.dumps(manifest))

            config = mgr.load_skill_context("compound-engineering")

            assert config is None


class TestContextSessionIntegration:
    """[P1] Integration tests for context with session tracking."""

    def test_session_state_tracks_context(self):
        """[P0] Should track context in session state."""
        from cohezion.compound.session_manager import CompoundSessionManager

        # Session manager should work with context
        mgr = CompoundSessionManager()

        assert mgr is not None

    def test_session_with_context_coherence(self):
        """[P1] Should check context coherence before session operations."""
        # This would integrate with context coherence checking
        pass


class TestContextErrorRecovery:
    """[P1] Integration tests for context error handling."""

    def test_context_recover_from_corrupted_manifest(self, tmp_path):
        """[P0] Should handle corrupted manifest gracefully."""
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "traceability").mkdir()

        # Write corrupted JSON
        with open(ctx_dir / "traceability" / "manifest.json", "w") as f:
            f.write('{"corrupted json')

        with patch.object(Path, "cwd", return_value=tmp_path):
            mgr = ContextManager()

            with pytest.raises(Exception) as exc_info:
                mgr.load_manifest()

            assert "JSON" in str(exc_info.value) or "manifest" in str(exc_info.value).lower()

    def test_context_handles_missing_manifest(self, tmp_path):
        """[P0] Should raise error when manifest missing."""
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "traceability").mkdir()
        # Don't create manifest file

        with patch.object(Path, "cwd", return_value=tmp_path):
            mgr = ContextManager()

            with pytest.raises(Exception) as exc_info:
                mgr.load_manifest()

            assert (
                "not found" in str(exc_info.value).lower()
                or "manifest" in str(exc_info.value).lower()
            )

    def test_context_handles_missing_core_file(self, tmp_path, caplog):
        """[P1] Should handle missing core file gracefully (warn, don't raise).

        Manifest entries can drift from the filesystem. The executor's other
        helpers (degradation, journey, bioelectric) all warn-and-continue;
        load_core_context must follow the same contract so a stale manifest
        doesn't crash every execution.
        """
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "core").mkdir()
        (ctx_dir / "traceability").mkdir()

        # Manifest references non-existent file
        manifest = {
            "version": "1.0.0",
            "core_files": [
                {
                    "path": "core/nonexistent.md",
                    "token_budget": 100,
                    "coherence_threshold": 0.5,
                    "sources": [],
                }
            ],
            "skills": {},
        }
        with open(ctx_dir / "traceability" / "manifest.json", "w") as f:
            json.dump(manifest, f)

        with patch.object(Path, "cwd", return_value=tmp_path):
            mgr = ContextManager()

            # Must not raise; must log a warning naming the missing file
            with caplog.at_level("WARNING"):
                mgr.load_core_context()

            assert any(
                "nonexistent.md" in record.message and "Skipping" in record.message
                for record in caplog.records
            ), f"Expected warning naming missing file; got: {[r.message for r in caplog.records]}"


class TestContextWithCompoundWorkflow:
    """[P1] End-to-end integration tests for context in compound workflow."""

    @pytest.mark.fast
    def test_full_context_workflow(self, tmp_path):
        """[P0] Should demonstrate complete context workflow."""
        # Setup context structure
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "core").mkdir()
        (ctx_dir / "traceability").mkdir()

        manifest = {
            "version": "1.0.0",
            "core_files": [
                {
                    "path": "core/test-rules.md",
                    "token_budget": 100,
                    "coherence_threshold": 0.5,
                    "sources": [{"file": "AGENTS.md", "commit": "abc123"}],
                }
            ],
            "skills": {},
        }
        with open(ctx_dir / "traceability" / "manifest.json", "w") as f:
            json.dump(manifest, f)

        (ctx_dir / "core" / "test-rules.md").write_text(
            "# Test Rules\n\nAsync/await required.", encoding="utf-8"
        )

        with patch.object(Path, "cwd", return_value=tmp_path):
            # Initialize context manager
            mgr = ContextManager()

            # Load core context
            loaded = mgr.load_core_context()
            assert len(loaded) == 1

            # Check coherence
            assert mgr.check_coherence(0.5) is True

            # Get summary
            summary = mgr.get_context_summary()
            assert summary["token_usage"] == 100
            assert summary["core_loaded"] is True

            # Verify file loaded
            assert len(mgr.loaded_files) == 1

    @pytest.mark.fast
    def test_context_coherence_threshold_enforcement(self, tmp_path):
        """[P0] Should enforce coherence thresholds."""
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "core").mkdir()
        (ctx_dir / "traceability").mkdir()

        manifest = {
            "version": "1.0.0",
            "core_files": [
                {
                    "path": "core/rules.md",
                    "token_budget": 100,
                    "coherence_threshold": 0.8,  # High threshold
                    "sources": [],
                }
            ],
            "skills": {},
        }
        with open(ctx_dir / "traceability" / "manifest.json", "w") as f:
            json.dump(manifest, f)

        (ctx_dir / "core" / "rules.md").write_text("# Rules", encoding="utf-8")

        with patch.object(Path, "cwd", return_value=tmp_path):
            mgr = ContextManager()
            mgr.coherence_state = 0.5  # Below threshold

            with pytest.raises(ContextCoherenceError):
                mgr.load_core_context()


class TestContextPersistence:
    """[P1] Integration tests for context persistence."""

    def test_context_state_preserved_across_operations(self, tmp_path):
        """[P1] Should maintain state across operations."""
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "core").mkdir()
        (ctx_dir / "traceability").mkdir()

        manifest = {
            "version": "1.0.0",
            "core_files": [],
            "skills": {},
        }
        with open(ctx_dir / "traceability" / "manifest.json", "w") as f:
            json.dump(manifest, f)

        with patch.object(Path, "cwd", return_value=tmp_path):
            mgr = ContextManager()

            # Modify state
            mgr.coherence_state = 0.85
            mgr.token_usage = 500

            # State should be preserved
            assert mgr.coherence_state == 0.85
            assert mgr.token_usage == 500

    def test_context_double_load_prevention(self, tmp_path):
        """[P1] Should prevent double loading of core context."""
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "core").mkdir()
        (ctx_dir / "traceability").mkdir()

        manifest = {
            "version": "1.0.0",
            "core_files": [
                {
                    "path": "core/rules.md",
                    "token_budget": 100,
                    "coherence_threshold": 0.5,
                    "sources": [],
                }
            ],
            "skills": {},
        }
        with open(ctx_dir / "traceability" / "manifest.json", "w") as f:
            json.dump(manifest, f)

        (ctx_dir / "core" / "rules.md").write_text("# Rules", encoding="utf-8")

        with patch.object(Path, "cwd", return_value=tmp_path):
            mgr = ContextManager()

            # First load
            loaded1 = mgr.load_core_context()
            assert len(loaded1) == 1

            # Second load should return empty (already loaded)
            loaded2 = mgr.load_core_context()
            assert len(loaded2) == 0

            # Token usage shouldn't double
            assert mgr.token_usage == 100
