"""Tests for compound context integration.

Generated by TEA testarch-automate workflow.
Step 3b: Backend Test Generation
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest

from cohezion.compound.context_integration import (
    CompoundContextMixin,
    ContextCoherenceError,
    ContextLoadError,
    ContextManager,
)


class TestContextManager:
    """[P0] Unit tests for ContextManager."""

    @pytest.fixture()
    def temp_context_dir(self, tmp_path: Path):
        """Create temporary context structure."""
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "core").mkdir()
        (ctx_dir / "traceability").mkdir()
        (ctx_dir / "skills").mkdir()

        # Create manifest
        manifest = {
            "version": "1.0.0",
            "core_files": [
                {
                    "path": "core/test-rules.md",
                    "token_budget": 100,
                    "coherence_threshold": 0.5,
                    "sources": [{"file": "AGENTS.md", "commit": "abc123"}],
                }
            ],
            "skills": {
                "test-skill": {
                    "context_file": "skills/test-skill/context.yaml",
                    "token_budget": 50,
                }
            },
        }
        with open(ctx_dir / "traceability" / "manifest.json", "w") as f:
            json.dump(manifest, f)

        # Create core file
        (ctx_dir / "core" / "test-rules.md").write_text("# Test Rules\n\nTest content.")

        return ctx_dir

    def test_find_project_root(self, tmp_path: Path):
        """[P0] Should detect project root by finding .context directory."""
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()

        with patch.object(Path, "cwd", return_value=tmp_path):
            mgr = ContextManager()
            assert mgr.project_root == tmp_path

    def test_find_project_root_not_found(self, tmp_path: Path):
        """[P1] Should raise ContextLoadError when project root not found."""
        with patch.object(Path, "cwd", return_value=tmp_path), pytest.raises(ContextLoadError):
            ContextManager()

    def test_load_manifest(self, temp_context_dir):
        """[P0] Should load and parse manifest.json."""
        mgr = ContextManager(temp_context_dir.parent)
        manifest = mgr.load_manifest()

        assert manifest is not None
        assert manifest["version"] == "1.0.0"
        assert len(manifest["core_files"]) == 1

    def test_load_manifest_not_found(self, tmp_path: Path):
        """[P1] Should raise ContextLoadError when manifest missing."""
        mgr = ContextManager(tmp_path)
        with pytest.raises(ContextLoadError):
            mgr.load_manifest()

    def test_load_core_context(self, temp_context_dir):
        """[P0] Should load all core context files within token budget."""
        mgr = ContextManager(temp_context_dir.parent)
        loaded = mgr.load_core_context()

        assert len(loaded) == 1
        assert loaded[0]["tokens"] == 100
        assert mgr.token_usage == 100

    def test_load_core_context_coherence_failure(self, temp_context_dir):
        """[P0] Should raise ContextCoherenceError when coherence below threshold."""
        mgr = ContextManager(temp_context_dir.parent)
        mgr.coherence_state = 0.3  # Below threshold

        with pytest.raises(ContextCoherenceError):
            mgr.load_core_context()

    def test_load_core_context_already_loaded(self, temp_context_dir):
        """[P1] Should skip loading if core already loaded."""
        mgr = ContextManager(temp_context_dir.parent)
        mgr.load_core_context()

        # Second load should return empty
        loaded = mgr.load_core_context()
        assert len(loaded) == 0

    def test_get_context_summary(self, temp_context_dir):
        """[P1] Should return current context state."""
        mgr = ContextManager(temp_context_dir.parent)
        mgr.load_core_context()

        summary = mgr.get_context_summary()
        assert summary["token_usage"] == 100
        assert summary["token_budget"] == 1000
        assert summary["core_loaded"] is True

    def test_check_coherence(self):
        """[P1] Should check coherence against HIHO threshold."""
        mgr = ContextManager(Path(tempfile.gettempdir()))
        mgr.coherence_state = 0.7

        assert mgr.check_coherence(0.5) is True
        assert mgr.check_coherence(0.8) is False


class TestCompoundContextMixin:
    """[P0] Unit tests for CompoundContextMixin."""

    def test_init_context(self):
        """[P0] Should initialize context manager on mixin."""

        class TestClass(CompoundContextMixin):
            def __init__(self):
                self.__init_context__()

        obj = TestClass()
        assert obj._context_manager is not None
        assert obj._context_loaded is False

    @patch.object(ContextManager, "load_core_context")
    def test_load_execution_context(self, mock_load):
        """[P0] Should load core context before execution."""

        class TestClass(CompoundContextMixin):
            def __init__(self):
                self.__init_context__()

        obj = TestClass()
        obj.load_execution_context()

        assert obj._context_loaded is True
        mock_load.assert_called_once()

    @patch.object(ContextManager, "load_core_context")
    def test_load_execution_context_coherence_failure(self, mock_load):
        """[P0] Should propagate ContextCoherenceError."""
        mock_load.side_effect = ContextCoherenceError("Low coherence")

        class TestClass(CompoundContextMixin):
            def __init__(self):
                self.__init_context__()

        obj = TestClass()
        with pytest.raises(ContextCoherenceError):
            obj.load_execution_context()

    def test_get_context_state(self):
        """[P1] Should return context state for metrics."""

        class TestClass(CompoundContextMixin):
            def __init__(self):
                self.__init_context__()

        obj = TestClass()
        state = obj.get_context_state()

        assert "token_usage" in state
        assert "coherence_state" in state


class TestContextIntegrationWithExecutor:
    """[P1] Integration tests for context with compound executor."""

    @pytest.mark.fast
    def test_context_manager_integration(self, tmp_path: Path):
        """[P1] Should integrate with existing project context structure."""
        # Create real .context structure
        ctx_dir = tmp_path / ".context"
        ctx_dir.mkdir()
        (ctx_dir / "core").mkdir()
        (ctx_dir / "traceability").mkdir()

        manifest = {
            "version": "1.0.0",
            "core_files": [
                {
                    "path": "core/syntax-rules.md",
                    "token_budget": 200,
                    "coherence_threshold": 0.5,
                    "sources": [{"file": "AGENTS.md", "commit": "d2f7129f"}],
                }
            ],
            "skills": {},
        }
        with open(ctx_dir / "traceability" / "manifest.json", "w") as f:
            json.dump(manifest, f)

        (ctx_dir / "core" / "syntax-rules.md").write_text("# Syntax Rules")

        mgr = ContextManager(tmp_path)
        loaded = mgr.load_core_context()

        assert len(loaded) == 1
        assert mgr.coherence_state == 1.0
