"""Tests for compound/executor.py.

Generated by TEA testarch-automate workflow.
Covers CompoundExecutor and ExecutionResult.
"""

from __future__ import annotations

from unittest.mock import MagicMock

import pytest

from cohezion.compound.executor import (
    CompoundExecutor,
    ExecutionResult,
)


class TestExecutionResult:
    """[P0] Unit tests for ExecutionResult dataclass."""

    def test_result_creation(self):
        """[P0] Should create execution result."""
        result = ExecutionResult(
            success=True,
            output="test output",
            metrics={"key": "value"},
            duration_seconds=1.5,
        )

        assert result.success is True
        assert result.output == "test output"
        assert result.metrics == {"key": "value"}
        assert result.duration_seconds == 1.5

    def test_result_with_vault_paths(self):
        """[P1] Should accept vault paths."""
        result = ExecutionResult(
            success=True,
            output="output",
            metrics={},
            duration_seconds=1.0,
            vault_experiment_path="/path/to/experiment",
            vault_decision_paths=["/path/to/decision"],
        )

        assert result.vault_experiment_path == "/path/to/experiment"
        assert result.vault_decision_paths == ["/path/to/decision"]


class TestCompoundExecutorInitialization:
    """[P0] Unit tests for CompoundExecutor initialization."""

    @pytest.fixture()
    def mock_mcp(self):
        """Create mock MCP client."""
        return MagicMock()

    def test_initialization(self, mock_mcp):
        """[P0] Should initialize with MCP client."""
        executor = CompoundExecutor(mcp_client=mock_mcp)

        assert executor.mcp_client == mock_mcp

    def test_initialization_with_optional_components(self, mock_mcp):
        """[P0] Should accept optional components."""
        mock_token_client = MagicMock()
        mock_guardrail = MagicMock()

        executor = CompoundExecutor(
            mcp_client=mock_mcp,
            token_client=mock_token_client,
            guardrail_pipeline=mock_guardrail,
        )

        assert executor.token_client == mock_token_client


class TestCompoundExecutorExecution:
    """[P0] Unit tests for task execution."""

    @pytest.fixture()
    def mock_mcp(self):
        """Create mock MCP client."""
        return MagicMock()

    @pytest.fixture()
    def executor(self, mock_mcp):
        """Create executor with mocked components."""
        executor = CompoundExecutor(mcp_client=mock_mcp)
        executor.logger = MagicMock()
        executor.logger.get_experience_guidance.return_value = {}
        return executor

    def test_execute_task_success(self, executor):
        """[P0] Should execute task successfully."""
        result = executor.execute_task(
            task_description="Test task",
            skill_name="test-skill",
            operation_type="generate",
            execute_fn=lambda: ("output", {"metric": 1.0}),
        )

        assert isinstance(result, ExecutionResult)

    def test_execute_task_with_guidance(self, executor):
        """[P0] Should use guidance for execution."""
        executor.logger.get_experience_guidance.return_value = {
            "suggested_model": "sonnet",
            "estimated_tokens": 1000,
        }

        result = executor.execute_task(
            task_description="Test task",
            skill_name="test-skill",
            operation_type="generate",
            execute_fn=lambda: ("output", {}),
        )

        assert isinstance(result, ExecutionResult)


class TestCompoundExecutorSkillRefinement:
    """[P0] Unit tests for skill refinement."""

    @pytest.fixture()
    def mock_mcp(self):
        """Create mock MCP client."""
        return MagicMock()

    @pytest.fixture()
    def executor(self, mock_mcp):
        """Create executor with skill refiner."""
        mock_refiner = MagicMock()
        executor = CompoundExecutor(
            mcp_client=mock_mcp,
            skill_refiner=mock_refiner,
        )
        executor.logger = MagicMock()
        executor.logger.get_experience_guidance.return_value = {}
        return executor

    def test_skill_refiner_integration(self, executor):
        """[P0] Should integrate with skill refiner."""
        result = executor.execute_task(
            task_description="Test task",
            skill_name="test-skill",
            operation_type="generate",
            execute_fn=lambda: ("output", {}),
        )

        assert isinstance(result, ExecutionResult)


class TestCompoundExecutorIntegration:
    """[P1] Integration tests for CompoundExecutor."""

    @pytest.mark.fast
    def test_end_to_end_execution(self):
        """[P0] Should demonstrate complete execution flow."""
        mock_mcp = MagicMock()
        executor = CompoundExecutor(mcp_client=mock_mcp)
        executor.logger = MagicMock()
        executor.logger.get_experience_guidance.return_value = {}

        # Execute a simple task
        result = executor.execute_task(
            task_description="Generate a Python function",
            skill_name="code-generation",
            operation_type="generate",
            execute_fn=lambda: ("def hello(): pass", {"tokens": 100}),
        )

        assert isinstance(result, ExecutionResult)
        assert result.duration_seconds > 0


class TestCompoundExecutorAutoCreation:
    """[P0] Tests for auto-creation of coherence components."""

    @pytest.fixture()
    def mock_mcp(self):
        return MagicMock()

    def test_alignment_analyzer_auto_created(self, mock_mcp):
        """Alignment analyzer should be auto-created when enabled (now default)."""
        executor = CompoundExecutor(mcp_client=mock_mcp)
        assert executor._alignment_analyzer is not None
        assert type(executor._alignment_analyzer).__name__ == "RequestAlignmentAnalyzer"

    def test_alignment_analyzer_disabled(self, mock_mcp):
        """Alignment analyzer should be None when explicitly disabled."""
        executor = CompoundExecutor(mcp_client=mock_mcp, enable_alignment_analysis=False)
        assert executor._alignment_analyzer is None

    def test_degradation_detector_auto_created(self, mock_mcp):
        """Degradation detector should be auto-created by default."""
        executor = CompoundExecutor(mcp_client=mock_mcp)
        assert executor._degradation_detector is not None
        assert type(executor._degradation_detector).__name__ == "DegradationDetector"

    def test_degradation_detector_uses_config_threshold(self, mock_mcp):
        """Auto-created detector should use CoherenceConfig threshold."""
        from cohezion.compound.coherence_config import DEFAULT_CONFIG

        executor = CompoundExecutor(mcp_client=mock_mcp)
        assert (
            executor._degradation_detector.coherence_threshold
            == DEFAULT_CONFIG.degradation_coherence
        )

    def test_skill_health_tracker_auto_created(self, mock_mcp):
        """Skill health tracker should be auto-created by default."""
        executor = CompoundExecutor(mcp_client=mock_mcp)
        assert executor._skill_health_tracker is not None
        assert type(executor._skill_health_tracker).__name__ == "SkillHealthTracker"

    def test_degradation_mode_initially_false(self, mock_mcp):
        """Degradation mode should start as False."""
        executor = CompoundExecutor(mcp_client=mock_mcp)
        assert executor._degradation_mode is False
