-- ───────────────────────────────────────────────────────────────────────────────
-- Agent Context Schema for SurrealDB
-- Tracks agent execution context from entire.io
-- ───────────────────────────────────────────────────────────────────────────────

-- ═══════════════════════════════════════════════════════════════════════════════
-- TABLES: Core Node Types
-- ═══════════════════════════════════════════════════════════════════════════════

-- Session: Top-level agent execution session
CREATE TABLE IF NOT EXISTS session SCHEMALESS;

DEFINE FIELD id ON TABLE session TYPE string;
DEFINE FIELD timestamp ON TABLE session TYPE datetime;
DEFINE FIELD duration_ms ON TABLE session TYPE number;
DEFINE FIELD agent_names ON TABLE session TYPE array;
DEFINE FIELD status ON TABLE session TYPE string;  -- running | completed | error
DEFINE FIELD error_message ON TABLE session TYPE string;
DEFINE FIELD model_used ON TABLE session TYPE string;  -- haiku | sonnet | opus
DEFINE FIELD total_turns ON TABLE session TYPE number;
DEFINE FIELD total_functions ON TABLE session TYPE number;
DEFINE FIELD created_at ON TABLE session TYPE datetime DEFAULT time::now();
DEFINE FIELD updated_at ON TABLE session TYPE datetime DEFAULT time::now();

-- Decision: Critical decision point during execution
CREATE TABLE IF NOT EXISTS decision SCHEMALESS;

DEFINE FIELD id ON TABLE decision TYPE string;
DEFINE FIELD session_id ON TABLE decision TYPE string;
DEFINE FIELD timestamp ON TABLE decision TYPE datetime;
DEFINE FIELD title ON TABLE decision TYPE string;
DEFINE FIELD context ON TABLE decision TYPE string;  -- Why was this decision needed?
DEFINE FIELD reasoning ON TABLE decision TYPE string;  -- How was decision made?
DEFINE FIELD alternatives ON TABLE decision TYPE array;  -- [alt1, alt2, ...]
DEFINE FIELD chosen_path ON TABLE decision TYPE string;  -- Which was chosen?
DEFINE FIELD confidence ON TABLE decision TYPE number;  -- 0.0 - 1.0
DEFINE FIELD reversible ON TABLE decision TYPE bool;  -- Can it be undone?
DEFINE FIELD created_at ON TABLE decision TYPE datetime DEFAULT time::now();

-- Action: Specific function call or tool invocation
CREATE TABLE IF NOT EXISTS action SCHEMALESS;

DEFINE FIELD id ON TABLE action TYPE string;
DEFINE FIELD session_id ON TABLE action TYPE string;
DEFINE FIELD timestamp ON TABLE action TYPE datetime;
DEFINE FIELD tool_name ON TABLE action TYPE string;  -- read, write, bash, etc
DEFINE FIELD input_params ON TABLE action TYPE object;  -- Sanitized inputs
DEFINE FIELD output ON TABLE action TYPE string;  -- Truncated output
DEFINE FIELD duration_ms ON TABLE action TYPE number;
DEFINE FIELD status ON TABLE action TYPE string;  -- success | error | timeout
DEFINE FIELD error_details ON TABLE action TYPE string;  -- If status=error
DEFINE FIELD created_at ON TABLE action TYPE datetime DEFAULT time::now();

-- Outcome: Final result(s) of a session
CREATE TABLE IF NOT EXISTS outcome SCHEMALESS;

DEFINE FIELD id ON TABLE outcome TYPE string;
DEFINE FIELD session_id ON TABLE outcome TYPE string;
DEFINE FIELD timestamp ON TABLE outcome TYPE datetime;
DEFINE FIELD status ON TABLE outcome TYPE string;  -- success | partial | failed
DEFINE FIELD summary ON TABLE outcome TYPE string;  -- Human-readable result
DEFINE FIELD metrics ON TABLE outcome TYPE object;
  -- {
  --   total_turns: number,
  --   total_functions: number,
  --   errors: number,
  --   recovery_attempts: number
  -- }
DEFINE FIELD artifacts ON TABLE outcome TYPE array;  -- Files created, notes written, etc
DEFINE FIELD vault_notes_created ON TABLE outcome TYPE array;  -- [[note]] links
DEFINE FIELD created_at ON TABLE outcome TYPE datetime DEFAULT time::now();

-- Lesson: Extracted learning from session (links to vault/lessons/)
CREATE TABLE IF NOT EXISTS lesson SCHEMALESS;

DEFINE FIELD id ON TABLE lesson TYPE string;
DEFINE FIELD session_id ON TABLE lesson TYPE string;
DEFINE FIELD title ON TABLE lesson TYPE string;
DEFINE FIELD severity ON TABLE lesson TYPE string;  -- CRITICAL | HIGH | MEDIUM | LOW
DEFINE FIELD description ON TABLE lesson TYPE string;
DEFINE FIELD linked_lesson_path ON TABLE lesson TYPE string;  -- lessons/2026-02-11-*.md
DEFINE FIELD auto_extracted ON TABLE lesson TYPE bool;  -- Generated by system or human?
DEFINE FIELD created_at ON TABLE lesson TYPE datetime DEFAULT time::now();

-- ═══════════════════════════════════════════════════════════════════════════════
-- TABLES: Relationship/Edge Tables
-- ═══════════════════════════════════════════════════════════════════════════════

-- Decisions linked to session
CREATE TABLE IF NOT EXISTS has_decisions SCHEMALESS;
DEFINE FIELD in ON TABLE has_decisions TYPE string;  -- session id
DEFINE FIELD out ON TABLE has_decisions TYPE string;  -- decision id
DEFINE FIELD count ON TABLE has_decisions TYPE number;  -- Ordinal position
DEFINE FIELD created_at ON TABLE has_decisions TYPE datetime DEFAULT time::now();

-- Actions linked to session
CREATE TABLE IF NOT EXISTS has_actions SCHEMALESS;
DEFINE FIELD in ON TABLE has_actions TYPE string;  -- session id
DEFINE FIELD out ON TABLE has_actions TYPE string;  -- action id
DEFINE FIELD count ON TABLE has_actions TYPE number;  -- Sequence number
DEFINE FIELD created_at ON TABLE has_actions TYPE datetime DEFAULT time::now();

-- Outcomes linked to session
CREATE TABLE IF NOT EXISTS has_outcomes SCHEMALESS;
DEFINE FIELD in ON TABLE has_outcomes TYPE string;  -- session id
DEFINE FIELD out ON TABLE has_outcomes TYPE string;  -- outcome id
DEFINE FIELD created_at ON TABLE has_outcomes TYPE datetime DEFAULT time::now();

-- Decisions that informed which actions
CREATE TABLE IF NOT EXISTS informs_actions SCHEMALESS;
DEFINE FIELD in ON TABLE informs_actions TYPE string;  -- decision id
DEFINE FIELD out ON TABLE informs_actions TYPE string;  -- action id
DEFINE FIELD created_at ON TABLE informs_actions TYPE datetime DEFAULT time::now();

-- Outcomes validated by lessons
CREATE TABLE IF NOT EXISTS validates_lesson SCHEMALESS;
DEFINE FIELD in ON TABLE validates_lesson TYPE string;  -- outcome id
DEFINE FIELD out ON TABLE validates_lesson TYPE string;  -- lesson id
DEFINE FIELD created_at ON TABLE validates_lesson TYPE datetime DEFAULT time::now();

-- Sessions that relate to vault papers
CREATE TABLE IF NOT EXISTS relates_to_paper SCHEMALESS;
DEFINE FIELD in ON TABLE relates_to_paper TYPE string;  -- session id
DEFINE FIELD out ON TABLE relates_to_paper TYPE string;  -- paper id
DEFINE FIELD context ON TABLE relates_to_paper TYPE string;  -- How related?
DEFINE FIELD created_at ON TABLE relates_to_paper TYPE datetime DEFAULT time::now();

-- Decisions derived from research
CREATE TABLE IF NOT EXISTS derives_from_research SCHEMALESS;
DEFINE FIELD in ON TABLE derives_from_research TYPE string;  -- decision id
DEFINE FIELD out ON TABLE derives_from_research TYPE string;  -- paper id
DEFINE FIELD source_type ON TABLE derives_from_research TYPE string;  -- paper | concept
DEFINE FIELD created_at ON TABLE derives_from_research TYPE datetime DEFAULT time::now();

-- ═══════════════════════════════════════════════════════════════════════════════
-- INDEXES: For Query Performance
-- ═══════════════════════════════════════════════════════════════════════════════

-- Session indexes
CREATE INDEX IF NOT EXISTS idx_session_timestamp ON TABLE session COLUMNS timestamp DESC;
CREATE INDEX IF NOT EXISTS idx_session_status ON TABLE session COLUMNS status;
CREATE INDEX IF NOT EXISTS idx_session_agent_names ON TABLE session COLUMNS agent_names;

-- Decision indexes
CREATE INDEX IF NOT EXISTS idx_decision_session ON TABLE decision COLUMNS session_id;
CREATE INDEX IF NOT EXISTS idx_decision_timestamp ON TABLE decision COLUMNS timestamp DESC;
CREATE INDEX IF NOT EXISTS idx_decision_reversible ON TABLE decision COLUMNS reversible;

-- Action indexes
CREATE INDEX IF NOT EXISTS idx_action_session ON TABLE action COLUMNS session_id;
CREATE INDEX IF NOT EXISTS idx_action_tool ON TABLE action COLUMNS tool_name;
CREATE INDEX IF NOT EXISTS idx_action_status ON TABLE action COLUMNS status;

-- Outcome indexes
CREATE INDEX IF NOT EXISTS idx_outcome_session ON TABLE outcome COLUMNS session_id;
CREATE INDEX IF NOT EXISTS idx_outcome_status ON TABLE outcome COLUMNS status;

-- Lesson indexes
CREATE INDEX IF NOT EXISTS idx_lesson_session ON TABLE lesson COLUMNS session_id;
CREATE INDEX IF NOT EXISTS idx_lesson_severity ON TABLE lesson COLUMNS severity;
CREATE INDEX IF NOT EXISTS idx_lesson_linked_path ON TABLE lesson COLUMNS linked_lesson_path;

-- Edge table indexes
CREATE INDEX IF NOT EXISTS idx_has_decisions_session ON TABLE has_decisions COLUMNS in;
CREATE INDEX IF NOT EXISTS idx_has_actions_session ON TABLE has_actions COLUMNS in;
CREATE INDEX IF NOT EXISTS idx_has_outcomes_session ON TABLE has_outcomes COLUMNS in;
CREATE INDEX IF NOT EXISTS idx_informs_actions_decision ON TABLE informs_actions COLUMNS in;
CREATE INDEX IF NOT EXISTS idx_validates_lesson_outcome ON TABLE validates_lesson COLUMNS in;
CREATE INDEX IF NOT EXISTS idx_relates_to_paper_session ON TABLE relates_to_paper COLUMNS in;
CREATE INDEX IF NOT EXISTS idx_derives_from_research_decision ON TABLE derives_from_research COLUMNS in;

-- ═══════════════════════════════════════════════════════════════════════════════
-- QUERY PATTERNS (Reference)
-- ═══════════════════════════════════════════════════════════════════════════════

-- Query 1: Research Lineage (session → decisions → papers)
-- Find all papers that informed decisions made during a session
-- SELECT DISTINCT paper FROM (
--   SELECT DISTINCT decision:out FROM has_decisions WHERE in = $session_id
-- ) -> derives_from_research -> paper;

-- Query 2: Lesson Validation (action → outcome → lesson)
-- Find lessons validated by session outcomes
-- SELECT lesson FROM (
--   SELECT outcome FROM has_outcomes WHERE in = $session_id
-- ) -> validates_lesson -> lesson;

-- Query 3: Cascading Impact (decision → actions → outcomes)
-- Trace how a decision impacts downstream actions and outcomes
-- SELECT action, outcome FROM (
--   SELECT decision:out FROM has_decisions WHERE in = $session_id
-- ) -> informs_actions -> action -> action:out;
-- THEN action -> outcome (via has_outcomes indirect);
