"""Tests for swarm/ollama_resilience.py.

Generated by TEA testarch-automate workflow.
Covers ResilientOllamaClient with circuit breaker, retry, and fallback.
"""

from __future__ import annotations

import httpx
import pytest

from cohezion.swarm.ollama_resilience import ResilientOllamaClient


class TestResilientOllamaClientInitialization:
    """[P0] Unit tests for ResilientOllamaClient initialization."""

    def test_default_initialization(self):
        """[P0] Should initialize with default parameters."""
        client = ResilientOllamaClient()

        assert client.model == "phi3:mini"
        assert client.base_url == "http://localhost:11434"
        assert client.max_retries == 2
        assert client.circuit is not None
        assert client.monitor is not None

    def test_custom_initialization(self):
        """[P0] Should accept custom parameters."""
        client = ResilientOllamaClient(
            model="qwen3-coder:30b",
            base_url="http://custom:11434",
            failure_threshold=5,
            recovery_timeout=60.0,
            max_retries=3,
        )

        assert client.model == "qwen3-coder:30b"
        assert client.base_url == "http://custom:11434"
        assert client.max_retries == 3

    def test_circuit_breaker_configured(self):
        """[P0] Should configure circuit breaker."""
        client = ResilientOllamaClient(failure_threshold=3, recovery_timeout=30.0)

        assert client.circuit is not None


class TestResilientOllamaClientClientProperty:
    """[P0] Unit tests for client property."""

    def test_client_lazy_initialization(self):
        """[P0] Should lazy-initialize HTTP client."""
        client = ResilientOllamaClient()

        # Initially None
        assert client._client is None

        # Access property creates client
        http_client = client.client
        assert http_client is not None
        assert isinstance(http_client, httpx.AsyncClient)

    def test_client_reuses_instance(self):
        """[P0] Should reuse client instance."""
        client = ResilientOllamaClient()

        http_client_1 = client.client
        http_client_2 = client.client

        assert http_client_1 is http_client_2


class TestResilientOllamaClientFallback:
    """[P0] Unit tests for fallback mechanism."""

    def test_fallback_returns_simple_response(self):
        """[P0] Should return fallback response."""
        client = ResilientOllamaClient()

        result = client._fallback("Test prompt")

        assert "unavailable" in result.lower() or "circuit breaker" in result.lower()

    def test_fallback_includes_prompt_info(self):
        """[P1] Should include prompt in fallback."""
        client = ResilientOllamaClient()

        result = client._fallback("Specific prompt text")

        assert "Specific prompt text" in result


class TestResilientOllamaClientIntegration:
    """[P1] Integration tests for ResilientOllamaClient."""

    @pytest.mark.fast
    def test_client_lifecycle(self):
        """[P0] Should manage client lifecycle."""
        client = ResilientOllamaClient()

        # Initially no client
        assert client._client is None

        # Access creates client
        _ = client.client
        assert client._client is not None

    @pytest.mark.fast
    @pytest.mark.asyncio
    async def test_close_releases_client(self):
        """[P0] Should close HTTP client."""
        client = ResilientOllamaClient()

        # Create client
        _ = client.client
        assert client._client is not None

        # Close should set to None
        await client.close()
        assert client._client is None

    @pytest.mark.fast
    def test_circuit_state_tracking(self):
        """[P0] Should track circuit state."""
        client = ResilientOllamaClient()

        # Circuit should allow requests initially
        assert client.circuit.allow_request() is True

    @pytest.mark.fast
    def test_monitor_integration(self):
        """[P0] Should integrate with resource monitor."""
        client = ResilientOllamaClient()

        assert client.monitor is not None

    @pytest.mark.fast
    def test_default_parameters(self):
        """[P1] Should have sensible defaults."""
        client = ResilientOllamaClient()

        assert client.max_retries == 2
        assert client.model == "phi3:mini"
        assert "localhost" in client.base_url
