"""Tests for swarm/team_orchestrator.py.

Generated by TEA testarch-automate workflow.
Covers TeamOrchestrator, AgentSpec, TaskSpec, TeamPlan.
"""

from __future__ import annotations

from unittest.mock import MagicMock, patch

import pytest

from cohezion.swarm.team_orchestrator import (
    AgentSpec,
    TaskSpec,
    TeamOrchestrator,
    TeamPlan,
)


class TestAgentSpec:
    """[P1] Unit tests for AgentSpec dataclass."""

    def test_default_initialization(self):
        """[P0] Should initialize with default values."""
        spec = AgentSpec(name="test-agent", description="A test agent")

        assert spec.name == "test-agent"
        assert spec.description == "A test agent"
        assert spec.tools == ["Read", "Glob", "Grep", "Bash", "Edit", "Write"]
        assert spec.disallowed_tools == []
        assert spec.model == "sonnet"
        assert spec.instructions == ""
        assert spec.ollama_model is None

    def test_custom_initialization(self):
        """[P0] Should accept custom values."""
        spec = AgentSpec(
            name="custom-agent",
            description="Custom agent",
            tools=["Read"],
            disallowed_tools=["Bash"],
            model="opus",
            instructions="Be helpful",
            ollama_model="qwen3-coder:30b",
        )

        assert spec.name == "custom-agent"
        assert spec.tools == ["Read"]
        assert spec.disallowed_tools == ["Bash"]
        assert spec.model == "opus"
        assert spec.instructions == "Be helpful"
        assert spec.ollama_model == "qwen3-coder:30b"


class TestTaskSpec:
    """[P1] Unit tests for TaskSpec dataclass."""

    def test_task_creation(self):
        """[P0] Should create task specification."""
        task = TaskSpec(
            id="task-001",
            subject="Implement feature",
            description="Implement the core feature",
            assigned_to="agent-1",
            blocked_by=["task-000"],
            tags=["code", "urgent"],
        )

        assert task.id == "task-001"
        assert task.subject == "Implement feature"
        assert task.description == "Implement the core feature"
        assert task.assigned_to == "agent-1"
        assert task.blocked_by == ["task-000"]
        assert task.tags == ["code", "urgent"]

    def test_task_with_defaults(self):
        """[P0] Should use defaults for optional fields."""
        task = TaskSpec(id="task-002", subject="Simple task", description="Just do it")

        assert task.assigned_to == ""
        assert task.blocked_by == []
        assert task.tags == []


class TestTeamPlan:
    """[P0] Unit tests for TeamPlan dataclass."""

    def test_plan_creation(self):
        """[P0] Should create team plan."""
        plan = TeamPlan(name="test-plan", intent="Test the system")

        assert plan.name == "test-plan"
        assert plan.intent == "Test the system"
        assert plan.agents == []
        assert plan.tasks == []
        assert plan.dependencies == {}

    def test_plan_with_agents_and_tasks(self):
        """[P0] Should include agents and tasks."""
        agent = AgentSpec(name="agent-1", description="First agent")
        task = TaskSpec(id="task-1", subject="Do work", description="Work description")

        plan = TeamPlan(
            name="full-plan",
            intent="Complete task",
            agents=[agent],
            tasks=[task],
            dependencies={"task-1": []},
        )

        assert len(plan.agents) == 1
        assert len(plan.tasks) == 1
        assert plan.dependencies == {"task-1": []}

    def test_plan_summary(self):
        """[P0] Should generate readable summary."""
        agent = AgentSpec(name="coder", description="Code writer", model="sonnet")
        task = TaskSpec(id="t1", subject="Write code", description="Write some code")

        plan = TeamPlan(name="code-plan", intent="Write code", agents=[agent], tasks=[task])

        summary = plan.summary

        assert "Team: code-plan" in summary
        assert "Intent: Write code" in summary
        assert "Agents (1):" in summary
        assert "Tasks (1):" in summary
        assert "[t1] Write code" in summary

    def test_plan_summary_with_blocked_tasks(self):
        """[P1] Should show blocked_by in summary."""
        task = TaskSpec(id="t2", subject="Deploy", description="Deploy app", blocked_by=["t1"])

        plan = TeamPlan(name="deploy-plan", intent="Deploy", tasks=[task])
        summary = plan.summary

        assert "[blocked by: t1]" in summary


class TestTeamOrchestratorInitialization:
    """[P0] Unit tests for TeamOrchestrator initialization."""

    def test_orchestrator_initialization(self):
        """[P0] Should initialize orchestrator."""
        orchestrator = TeamOrchestrator()

        assert orchestrator._registry is None
        assert orchestrator._engine is None

    @patch("cohezion.registry.capability_registry.CapabilityRegistry")
    def test_registry_lazy_load(self, mock_registry_class):
        """[P0] Should lazy-load registry."""
        mock_registry = MagicMock()
        mock_registry_class.return_value = mock_registry

        orchestrator = TeamOrchestrator()

        # Access registry property
        registry = orchestrator.registry

        assert registry is mock_registry
        mock_registry_class.assert_called_once()

    @patch("cohezion.core.template_engine.TemplateEngine")
    def test_engine_lazy_load(self, mock_engine_class):
        """[P0] Should lazy-load template engine."""
        mock_engine = MagicMock()
        mock_engine_class.return_value = mock_engine

        orchestrator = TeamOrchestrator()

        # Access engine property
        engine = orchestrator.engine

        assert engine is mock_engine
        mock_engine_class.assert_called_once()


class TestTeamOrchestratorPlanTeam:
    """[P0] Unit tests for plan_team method."""

    @pytest.fixture()
    def orchestrator_with_mock_registry(self):
        """Create orchestrator with mock registry."""
        orchestrator = TeamOrchestrator()
        mock_registry = MagicMock()
        orchestrator._registry = mock_registry
        return orchestrator, mock_registry

    def test_plan_team_basic(self, orchestrator_with_mock_registry):
        """[P0] Should create basic team plan."""
        orchestrator, mock_registry = orchestrator_with_mock_registry

        # Setup mock capabilities
        mock_cap = MagicMock()
        mock_cap.name = "code-skill"
        mock_cap.type = "skill"
        mock_cap.tags = ["code"]
        mock_cap.metadata = {"role": "developer"}
        mock_registry.find.return_value = [mock_cap]

        plan = orchestrator.plan_team("Implement a feature", max_agents=4)

        assert isinstance(plan, TeamPlan)
        assert plan.name == "implement-a-feature"
        assert plan.intent == "Implement a feature"

    def test_plan_team_with_multiple_agents(self, orchestrator_with_mock_registry):
        """[P0] Should create plan with multiple agents."""
        orchestrator, mock_registry = orchestrator_with_mock_registry

        cap1 = MagicMock()
        cap1.name = "code-cap"
        cap1.type = "skill"
        cap1.tags = ["code"]

        cap2 = MagicMock()
        cap2.name = "test-cap"
        cap2.type = "skill"
        cap2.tags = ["test"]

        mock_registry.find.return_value = [cap1, cap2]

        plan = orchestrator.plan_team("Build and test", max_agents=4)

        assert len(plan.agents) == 2

    def test_plan_team_respects_max_agents(self, orchestrator_with_mock_registry):
        """[P0] Should respect max_agents limit."""
        orchestrator, mock_registry = orchestrator_with_mock_registry

        mock_caps = []
        for i in range(10):
            cap = MagicMock()
            cap.name = f"skill-{i}"
            cap.type = "skill"
            cap.tags = []
            mock_caps.append(cap)

        mock_registry.find.return_value = mock_caps

        plan = orchestrator.plan_team("Big project", max_agents=3)

        assert len(plan.agents) <= 3

    def test_plan_team_creates_tasks(self, orchestrator_with_mock_registry):
        """[P0] Should generate tasks."""
        orchestrator, mock_registry = orchestrator_with_mock_registry

        mock_cap = MagicMock()
        mock_cap.name = "coding-skill"
        mock_cap.type = "skill"
        mock_cap.tags = []
        mock_registry.find.return_value = [mock_cap]

        orchestrator = TeamOrchestrator()
        plan = orchestrator.plan_team("Implement feature")

        assert len(plan.tasks) > 0

    def test_plan_team_empty_intent(self, orchestrator_with_mock_registry):
        """[P1] Should handle empty intent."""
        orchestrator, mock_registry = orchestrator_with_mock_registry
        mock_registry.find.return_value = []

        plan = orchestrator.plan_team("")

        assert isinstance(plan, TeamPlan)
        assert plan.name == "agent"  # Empty intent falls back to "agent"


class TestTeamOrchestratorGenerateAgentSpec:
    """[P0] Unit tests for generate_agent_spec_from_capability."""

    def test_generate_agent_spec_basic(self):
        """[P0] Should generate agent spec from capability."""
        mock_cap = MagicMock()
        mock_cap.name = "test-skill"
        mock_cap.description = "Test skill description"
        mock_cap.tags = ["code", "test"]

        orchestrator = TeamOrchestrator()
        spec = orchestrator.generate_agent_spec_from_capability(mock_cap, "developer")

        assert isinstance(spec, AgentSpec)
        assert spec.name == "test-skill"
        assert spec.description == "Test skill description"

    def test_generate_agent_spec_uses_claude_model(self):
        """[P0] Should map to Claude model."""
        mock_cap = MagicMock()
        mock_cap.name = "test"
        mock_cap.description = "Test"
        mock_cap.tags = []

        orchestrator = TeamOrchestrator()
        spec = orchestrator.generate_agent_spec_from_capability(mock_cap, "code")

        # Should have valid Claude model
        assert spec.model in ["haiku", "sonnet", "opus"]


class TestTeamOrchestratorRoleInference:
    """[P1] Unit tests for _infer_role method."""

    def test_infer_role_tester_from_name(self):
        """[P1] Should infer tester role from test keywords."""
        orchestrator = TeamOrchestrator()

        role = orchestrator._infer_role("test-cap", [])
        assert role == "tester"

    def test_infer_role_tester_from_tags(self):
        """[P1] Should infer tester role from test tags."""
        orchestrator = TeamOrchestrator()

        role = orchestrator._infer_role("any-cap", ["test", "verify"])
        assert role == "tester"

    def test_infer_role_reviewer(self):
        """[P1] Should infer reviewer role from review keywords."""
        orchestrator = TeamOrchestrator()

        role = orchestrator._infer_role("security-audit", [])
        assert role == "reviewer"

    def test_infer_role_researcher(self):
        """[P1] Should infer researcher role from research keywords."""
        orchestrator = TeamOrchestrator()

        role = orchestrator._infer_role("scout-skill", ["explore"])
        assert role == "researcher"

    def test_infer_role_default(self):
        """[P1] Should return implementer role as default."""
        orchestrator = TeamOrchestrator()

        role = orchestrator._infer_role("unknown", [])
        assert role == "implementer"


class TestTeamOrchestratorSlugify:
    """[P1] Unit tests for _slugify method."""

    def test_slugify_basic(self):
        """[P1] Should convert text to kebab-case slug."""
        orchestrator = TeamOrchestrator()

        slug = orchestrator._slugify("Hello World")
        assert slug == "hello-world"

    def test_slugify_special_chars(self):
        """[P1] Should remove special characters and use hyphens."""
        orchestrator = TeamOrchestrator()

        slug = orchestrator._slugify("Test@#$%^&*()Name")
        assert "@" not in slug
        assert "$" not in slug
        assert slug == "test-name"

    def test_slugify_multiple_spaces(self):
        """[P1] Should handle multiple spaces with hyphens."""
        orchestrator = TeamOrchestrator()

        slug = orchestrator._slugify("Multiple   Spaces")
        assert slug == "multiple-spaces"

    def test_slugify_removes_prime_suffix(self):
        """[P1] Should remove _PRIME suffix."""
        orchestrator = TeamOrchestrator()

        slug = orchestrator._slugify("MySkill_PRIME")
        assert slug == "myskill"

    def test_slugify_lowercase(self):
        """[P1] Should convert to lowercase."""
        orchestrator = TeamOrchestrator()

        slug = orchestrator._slugify("UPPERCASE")
        assert slug == "uppercase"


class TestTeamOrchestratorIntegration:
    """[P1] Integration tests for team orchestration."""

    def _create_orchestrator_with_mock_registry(self, capabilities):
        """Helper to create orchestrator with mock registry."""
        orchestrator = TeamOrchestrator()
        mock_registry = MagicMock()
        mock_registry.find.return_value = capabilities
        orchestrator._registry = mock_registry
        return orchestrator

    @pytest.mark.fast
    def test_end_to_end_team_planning(self):
        """[P0] Should demonstrate complete team planning workflow."""
        # Create mock capabilities
        cap1 = MagicMock()
        cap1.name = "frontend-skill"
        cap1.type = "skill"
        cap1.description = "Frontend development"
        cap1.tags = ["code", "implement"]

        cap2 = MagicMock()
        cap2.name = "backend-skill"
        cap2.type = "skill"
        cap2.description = "Backend development"
        cap2.tags = ["code", "implement"]

        orchestrator = self._create_orchestrator_with_mock_registry([cap1, cap2])
        plan = orchestrator.plan_team("Build a web application", max_agents=4)

        # Verify plan structure
        assert plan.name == "build-a-web-application"
        assert len(plan.agents) == 2
        assert len(plan.tasks) > 0

        # Verify summary
        summary = plan.summary
        assert "frontend-skill" in summary or "frontend" in summary.lower()
        assert "backend-skill" in summary or "backend" in summary.lower()

    @pytest.mark.fast
    def test_team_with_dependencies(self):
        """[P1] Should create tasks with dependencies."""
        mock_cap = MagicMock()
        mock_cap.name = "build-skill"
        mock_cap.type = "skill"
        mock_cap.description = "Build skill"
        mock_cap.tags = []

        orchestrator = self._create_orchestrator_with_mock_registry([mock_cap])
        plan = orchestrator.plan_team("Build project")

        # Check dependencies were created
        assert len(plan.dependencies) > 0 or len(plan.tasks) > 0

    @pytest.mark.fast
    def test_team_planning_with_limit(self):
        """[P1] Should respect agent limit."""
        # Many capabilities
        # Many capabilities with proper string names
        caps = []
        for i in range(20):
            cap = MagicMock()
            cap.name = f"skill-{i}"
            cap.type = "skill"
            cap.tags = []
            caps.append(cap)

        orchestrator = self._create_orchestrator_with_mock_registry(caps)
        plan = orchestrator.plan_team("Big project", max_agents=2)

        assert len(plan.agents) <= 2
