"""Tests for validation/agent_schema.py.

Generated by TEA testarch-automate workflow.
Covers AgentFileSchema, extract_frontmatter, validate_agent_file.
"""

from __future__ import annotations

import contextlib
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest
from pydantic import ValidationError

from cohezion.validation.agent_schema import (
    AgentFileSchema,
    AgentFileValidationError,
    extract_frontmatter,
    generate_agent_frontmatter,
    validate_agent_file,
    validate_all_agent_files,
)


class TestAgentFileSchema:
    """[P0] Unit tests for AgentFileSchema Pydantic model."""

    def test_schema_with_required_fields(self):
        """[P0] Should create schema with required fields only."""
        schema = AgentFileSchema(
            name="test-agent",
            description="A test agent for validation.",
        )

        assert schema.name == "test-agent"
        assert schema.description == "A test agent for validation."
        assert schema.tools is None
        assert schema.disallowedTools is None
        assert schema.model is None

    def test_schema_with_all_fields(self):
        """[P0] Should create schema with all optional fields."""
        schema = AgentFileSchema(
            name="full-agent",
            description="A fully configured agent.",
            tools=["read_file", "write_file"],
            disallowedTools=["bash"],
            model="sonnet",
        )

        assert schema.name == "full-agent"
        assert schema.description == "A fully configured agent."
        assert schema.tools == ["read_file", "write_file"]
        assert schema.disallowedTools == ["bash"]
        assert schema.model == "sonnet"

    def test_name_validation_kebab_case(self):
        """[P0] Should validate name is lowercase kebab-case."""
        # Valid names - all with descriptions >= 10 chars
        for name in ["test-agent", "my-agent-123", "agent", "a-b-c"]:
            schema = AgentFileSchema(name=name, description="A valid description")
            assert schema.name == name

    def test_name_validation_rejects_invalid_formats(self):
        """[P0] Should reject invalid name formats."""
        invalid_names = [
            "Test-Agent",  # Uppercase
            "test_agent",  # Underscore
            "123-agent",  # Starts with number
            "test agent",  # Space
            "test--agent",  # Double dash
            "-test-agent",  # Starts with dash
            "test-agent-",  # Ends with dash
        ]

        for name in invalid_names:
            with pytest.raises(ValidationError):
                AgentFileSchema(name=name, description="Test")

    def test_description_minimum_length(self):
        """[P0] Should enforce minimum description length of 10."""
        # Valid descriptions
        AgentFileSchema(name="test", description="1234567890")  # Exactly 10
        AgentFileSchema(name="test", description="A longer description here.")

        # Invalid
        with pytest.raises(ValidationError):
            AgentFileSchema(name="test", description="Too short")

    def test_extra_fields_forbidden(self):
        """[P0] Should reject extra fields."""
        with pytest.raises(ValidationError):
            AgentFileSchema(
                name="test",
                description="A valid description here.",
                extra_field="not allowed",
            )

    def test_tools_can_be_none(self):
        """[P1] Should accept None for tools."""
        schema = AgentFileSchema(name="test", description="Description", tools=None)
        assert schema.tools is None

    def test_disallowed_tools_can_be_none(self):
        """[P1] Should accept None for disallowedTools."""
        schema = AgentFileSchema(name="test", description="Description", disallowedTools=None)
        assert schema.disallowedTools is None

    def test_model_can_be_none(self):
        """[P1] Should accept None for model."""
        schema = AgentFileSchema(name="test", description="Description", model=None)
        assert schema.model is None


class TestExtractFrontmatter:
    """[P0] Unit tests for extract_frontmatter function."""

    def test_extracts_valid_frontmatter(self):
        """[P0] Should extract YAML frontmatter from markdown."""
        text = """---
name: test-agent
description: A test agent
---

# Agent Content

Here is the agent definition.
"""
        result = extract_frontmatter(text)

        assert result["name"] == "test-agent"
        assert result["description"] == "A test agent"

    def test_extracts_with_optional_fields(self):
        """[P0] Should extract frontmatter with optional fields."""
        text = """---
name: full-agent
description: A full agent
tools:
  - read_file
  - write_file
disallowedTools:
  - bash
model: sonnet
---

Content here.
"""
        result = extract_frontmatter(text)

        assert result["name"] == "full-agent"
        assert result["tools"] == ["read_file", "write_file"]
        assert result["disallowedTools"] == ["bash"]
        assert result["model"] == "sonnet"

    def test_returns_empty_dict_no_frontmatter(self):
        """[P0] Should return empty dict when no frontmatter."""
        text = """# Just Content

No frontmatter here.
"""
        result = extract_frontmatter(text)
        assert result == {}

    def test_returns_empty_dict_no_closing_delimiter(self):
        """[P0] Should return empty dict when closing --- missing."""
        text = """---
name: test-agent
description: Test

No closing delimiter.
"""
        result = extract_frontmatter(text)
        assert result == {}

    def test_returns_empty_dict_empty_frontmatter(self):
        """[P1] Should return empty dict when frontmatter is empty."""
        text = """---
---

Content here.
"""
        result = extract_frontmatter(text)
        assert result == {}

    def test_returns_empty_dict_invalid_yaml(self):
        """[P1] Should handle invalid YAML gracefully."""
        text = """---
name: test-agent
  invalid yaml here:
    - unclosed
---

Content.
"""
        # Invalid YAML raises exception - handled by caller.
        # Expected behavior for invalid YAML.
        with contextlib.suppress(Exception):
            result = extract_frontmatter(text)
            # If it doesn't raise, should at least return a dict
            assert isinstance(result, dict)

    def test_handles_frontmatter_not_at_start(self):
        """[P1] Should require frontmatter at start of file."""
        text = """# Header

---
name: test-agent
---

Content.
"""
        result = extract_frontmatter(text)
        assert result == {}

    def test_extracts_complex_frontmatter(self):
        """[P1] Should handle complex nested frontmatter."""
        text = """---
name: complex-agent
description: A complex agent with metadata
tools:
  - tool1
  - tool2
model: advanced
---

## Agent Definition

Complex content here.
"""
        result = extract_frontmatter(text)

        assert result["name"] == "complex-agent"
        assert len(result["tools"]) == 2


class TestValidateAgentFile:
    """[P0] Unit tests for validate_agent_file function."""

    @pytest.fixture()
    def valid_agent_content(self):
        """Create valid agent file content."""
        return """---
name: valid-agent
description: A valid test agent with proper description length
---

# Valid Agent

This is a valid agent definition.
"""

    @pytest.fixture()
    def temp_agent_file(self, tmp_path, valid_agent_content):
        """Create temporary agent file."""
        agent_file = tmp_path / "test-agent.md"
        agent_file.write_text(valid_agent_content, encoding="utf-8")
        return agent_file

    def test_validates_correct_file(self, temp_agent_file):
        """[P0] Should validate correct agent file."""
        result = validate_agent_file(temp_agent_file)

        assert isinstance(result, AgentFileSchema)
        assert result.name == "valid-agent"

    def test_raises_error_missing_frontmatter(self, tmp_path):
        """[P0] Should raise error when frontmatter missing."""
        agent_file = tmp_path / "bad-agent.md"
        agent_file.write_text("No frontmatter here.", encoding="utf-8")

        with pytest.raises(AgentFileValidationError) as exc_info:
            validate_agent_file(agent_file)

        assert "frontmatter" in str(exc_info.value).lower()
        assert exc_info.value.path == agent_file

    def test_raises_error_invalid_schema(self, tmp_path):
        """[P0] Should raise error when schema validation fails."""
        agent_file = tmp_path / "invalid-agent.md"
        agent_file.write_text(
            """---
name: INVALID_NAME
description: Short
---

Content.
""",
            encoding="utf-8",
        )

        with pytest.raises(AgentFileValidationError) as exc_info:
            validate_agent_file(agent_file)

        assert exc_info.value.path == agent_file

    def test_raises_error_file_not_found(self):
        """[P1] Should raise error when file not found."""
        with pytest.raises(AgentFileValidationError) as exc_info:
            validate_agent_file("/nonexistent/path/agent.md")

        assert "cannot read" in str(exc_info.value).lower()

    def test_accepts_string_path(self, temp_agent_file):
        """[P1] Should accept string path."""
        result = validate_agent_file(str(temp_agent_file))

        assert isinstance(result, AgentFileSchema)
        assert result.name == "valid-agent"


class TestValidateAllAgentFiles:
    """[P0] Unit tests for validate_all_agent_files function."""

    @pytest.fixture()
    def temp_agents_dir(self, tmp_path):
        """Create temporary agents directory with files."""
        agents_dir = tmp_path / ".claude" / "agents"
        agents_dir.mkdir(parents=True)

        # Create valid agent files
        (agents_dir / "agent1.md").write_text(
            """---
name: agent-one
description: First test agent here
---

Content 1.
""",
            encoding="utf-8",
        )

        (agents_dir / "agent2.md").write_text(
            """---
name: agent-two
description: Second test agent here
---

Content 2.
""",
            encoding="utf-8",
        )

        return agents_dir

    def test_validates_all_files_in_directory(self, temp_agents_dir):
        """[P0] Should validate all .md files in directory."""
        results = validate_all_agent_files(temp_agents_dir)

        assert len(results) == 2
        names = {r.name for r in results}
        assert names == {"agent-one", "agent-two"}

    def test_raises_error_empty_directory(self, tmp_path):
        """[P0] Should raise error when no .md files found."""
        empty_dir = tmp_path / "empty"
        empty_dir.mkdir()

        with pytest.raises(AgentFileValidationError) as exc_info:
            validate_all_agent_files(empty_dir)

        assert "no .md files" in str(exc_info.value).lower()

    def test_raises_error_invalid_file_in_directory(self, temp_agents_dir):
        """[P0] Should raise error when any file is invalid."""
        # Add invalid file
        (temp_agents_dir / "invalid.md").write_text(
            """---
name: INVALID
description: Short
---

Content.
""",
            encoding="utf-8",
        )

        with pytest.raises(AgentFileValidationError) as exc_info:
            validate_all_agent_files(temp_agents_dir)

        assert "invalid" in str(exc_info.value).lower()

    def test_collects_all_errors(self, temp_agents_dir):
        """[P1] Should collect errors from all invalid files."""
        # Add multiple invalid files
        (temp_agents_dir / "invalid1.md").write_text(
            """---
name: BAD1
description: X
---
""",
            encoding="utf-8",
        )

        (temp_agents_dir / "invalid2.md").write_text(
            """---
name: BAD2
description: Y
---
""",
            encoding="utf-8",
        )

        with pytest.raises(AgentFileValidationError) as exc_info:
            validate_all_agent_files(temp_agents_dir)

        error_str = str(exc_info.value).lower()
        assert "invalid1.md" in error_str or "invalid2.md" in error_str

    @patch("cohezion.validation.agent_schema.subprocess.run")
    def test_uses_git_root_when_no_directory(self, mock_run, tmp_path):
        """[P1] Should detect git root when directory not specified."""
        mock_run.return_value = MagicMock(returncode=0, stdout=str(tmp_path) + "\n")

        # Create .claude/agents structure
        agents_dir = tmp_path / ".claude" / "agents"
        agents_dir.mkdir(parents=True)
        (agents_dir / "agent.md").write_text(
            """---
name: git-agent
description: Agent found via git root
---

Content.
""",
            encoding="utf-8",
        )

        results = validate_all_agent_files()

        assert len(results) == 1
        assert results[0].name == "git-agent"

    @patch("cohezion.validation.agent_schema.subprocess.run")
    def test_raises_error_git_command_fails(self, mock_run):
        """[P1] Should raise error when git command fails."""
        mock_run.return_value = MagicMock(returncode=1, stderr="Not a git repository")

        with pytest.raises(AgentFileValidationError) as exc_info:
            validate_all_agent_files()

        assert "cannot determine git root" in str(exc_info.value).lower()


class TestGenerateAgentFrontmatter:
    """[P0] Unit tests for generate_agent_frontmatter function."""

    def test_generates_basic_frontmatter(self):
        """[P0] Should generate basic frontmatter with required fields."""
        result = generate_agent_frontmatter(
            name="test-agent",
            description="A test agent for generating frontmatter",
        )

        assert result.startswith("---\n")
        assert result.endswith("---\n")
        assert "name: test-agent" in result
        assert "description: A test agent for generating frontmatter" in result

    def test_generates_with_optional_fields(self):
        """[P0] Should generate frontmatter with optional fields."""
        result = generate_agent_frontmatter(
            name="full-agent",
            description="A fully featured agent",
            tools=["read_file", "write_file"],
            disallowed_tools=["bash", "exec"],
            model="sonnet",
        )

        assert "name: full-agent" in result
        assert "tools:" in result
        assert "- read_file" in result
        assert "disallowedTools:" in result
        assert "- bash" in result
        assert "model: sonnet" in result

    def test_generates_valid_yaml(self):
        """[P1] Should generate parseable YAML."""
        result = generate_agent_frontmatter(
            name="yaml-test",
            description="Testing YAML generation",
            tools=["tool1"],
        )

        # Should be valid YAML
        import yaml

        # Extract YAML between ---
        yaml_content = result.strip().strip("-").strip()
        parsed = yaml.safe_load(yaml_content)

        assert parsed["name"] == "yaml-test"
        assert parsed["description"] == "Testing YAML generation"

    def test_validates_generated_frontmatter(self):
        """[P0] Should validate generated frontmatter."""
        # This should not raise
        result = generate_agent_frontmatter(
            name="valid-agent",
            description="A valid description",
        )

        assert "---\n" in result

    def test_raises_error_invalid_name(self):
        """[P0] Should raise error when name is invalid."""
        with pytest.raises(AgentFileValidationError):
            generate_agent_frontmatter(
                name="INVALID_NAME",
                description="Valid description here",
            )

    def test_raises_error_short_description(self):
        """[P0] Should raise error when description too short."""
        with pytest.raises(AgentFileValidationError):
            generate_agent_frontmatter(
                name="test-agent",
                description="Short",
            )

    def test_omits_none_optional_fields(self):
        """[P1] Should not include None optional fields."""
        result = generate_agent_frontmatter(
            name="minimal-agent",
            description="Minimal agent description",
            tools=None,
            disallowed_tools=None,
            model=None,
        )

        # Should only have name and description
        assert "name: minimal-agent" in result
        assert "description:" in result
        assert "tools:" not in result
        assert "disallowedTools:" not in result
        assert "model:" not in result


class TestAgentFileValidationError:
    """[P1] Unit tests for AgentFileValidationError."""

    def test_error_with_path(self):
        """[P1] Should format error with path."""
        path = Path("/path/to/agent.md")
        errors = ["Name must be lowercase"]

        exc = AgentFileValidationError(path, errors)

        assert "/path/to/agent.md" in str(exc)
        assert "Name must be lowercase" in str(exc)
        assert exc.path == path
        assert exc.errors == errors

    def test_error_without_path(self):
        """[P1] Should format error without path."""
        errors = ["First error", "Second error"]

        exc = AgentFileValidationError(None, errors)

        assert exc.path is None
        assert "First error" in str(exc)
        assert "Second error" in str(exc)

    def test_multiple_errors_joined(self):
        """[P1] Should join multiple errors with semicolon."""
        errors = ["Error one", "Error two", "Error three"]

        exc = AgentFileValidationError(None, errors)

        assert str(exc) == "Error one; Error two; Error three"


class TestValidationIntegration:
    """[P1] Integration tests for validation workflow."""

    @pytest.mark.fast
    def test_full_validation_workflow(self, tmp_path):
        """[P1] Should demonstrate complete validation workflow."""
        # Create agent directory
        agents_dir = tmp_path / ".claude" / "agents"
        agents_dir.mkdir(parents=True)

        # Generate and save agent file
        frontmatter = generate_agent_frontmatter(
            name="integrated-agent",
            description="An agent for integration testing",
            tools=["read_file"],
            model="sonnet",
        )

        content = f"""{frontmatter}
# Integrated Agent

This agent demonstrates the full validation workflow.
"""
        agent_file = agents_dir / "integrated.md"
        agent_file.write_text(content, encoding="utf-8")

        # Validate the file
        result = validate_agent_file(agent_file)

        assert result.name == "integrated-agent"
        assert result.tools == ["read_file"]
        assert result.model == "sonnet"

        # Validate all files in directory
        all_results = validate_all_agent_files(agents_dir)

        assert len(all_results) == 1
        assert all_results[0].name == "integrated-agent"
