"""Ouroboros API — Immune system health, healing history, and self-improved rules.

Exposes the Ouroboros self-healing subsystem to the Genesis Engine webapp.
"""

from __future__ import annotations

import logging

from fastapi import APIRouter
from pydantic import BaseModel

from cohezion.physics.ouroboros_bridge import OuroborosBridge


logger = logging.getLogger(__name__)

ouroboros_router = APIRouter(prefix="/ouroboros", tags=["ouroboros"])

# Module-level singleton (lazy initialization pattern matching genesis.py)
_bridge: OuroborosBridge | None = None


def _get_bridge() -> OuroborosBridge:
    global _bridge
    if _bridge is None:
        _bridge = OuroborosBridge()
    return _bridge


class HealthResponse(BaseModel):
    status: str
    total_anomalies: int
    total_healings: int
    recent_anomalies: list[dict]
    ouroboros_rules: list[str]
    trigger_history: list[dict]


class HealingHistoryResponse(BaseModel):
    events: list[dict]
    count: int


class RulesResponse(BaseModel):
    rules: list[str]
    count: int


@ouroboros_router.get("/health", response_model=HealthResponse)
async def get_ouroboros_health() -> HealthResponse:
    """Get immune system health status.

    Returns anomaly counts, recent anomalies, and self-improved rules
    accumulated by the Ouroboros recursive self-improvement loop.
    """
    bridge = _get_bridge()
    summary = bridge.get_health_summary()
    return HealthResponse(**summary)


@ouroboros_router.get("/healing-history", response_model=HealingHistoryResponse)
async def get_healing_history() -> HealingHistoryResponse:
    """Get the history of healing events.

    Each event maps to a cosmogony phase — detection through stability.
    """
    bridge = _get_bridge()
    events = [e.to_dict() for e in bridge.healing_events]
    return HealingHistoryResponse(events=events, count=len(events))


@ouroboros_router.get("/rules", response_model=RulesResponse)
async def get_ouroboros_rules() -> RulesResponse:
    """Get accumulated self-improved rules.

    Rules are generated by the Ouroboros engine when it rewrites
    internal execution PRDs after detecting failure patterns.
    """
    bridge = _get_bridge()
    rules = bridge._engine.get_latest_system_rules()
    return RulesResponse(rules=rules, count=len(rules))
