import marimo as mo


app = mo.App(title="Cohezion: The Living Research Paper")


@app.cell
def __(mo):
    mo.md("""
    # 🌌 Cohezion: The Living Research Paper
    ## Fractal Nexus Convergence & 12D Latent Stability

    **Abstract**: This living document explores the emergence of stable reality manifolds through the co-evolution of agentic swarms and adversarial environment dynamics. We demonstrate the **0.5 HIHO Stability Rule** as a fundamental attractor for calibrated intelligence in 12D latent space.

    > [!NOTE]
    > **Reachability Note**: This page is served via a local Nginx proxy on Port 80 to ensure seamless WebSocket connectivity and Host Header stability.
    """)
    return


@app.cell
def __():
    from pathlib import Path

    import marimo as mo
    import numpy as np
    import pandas as pd
    import plotly.express as px
    import plotly.graph_objects as go

    return mo, pd, np, px, go, Path


@app.cell
def __(mo):
    # Updated assets path
    img_path = "assets/nano_manifold.png"
    audio_path = "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3"

    mo.md("## 🧬 1. The 12D Manifold Trajectory")

    return img_path, audio_path


@app.cell
def __(img_path, mo):
    # Display the stunning asset
    return mo.image(
        src=img_path,
        width=600,
        caption="Figure 1: 12D Latent Manifold Pulse Visualization",
    )


@app.cell
def __(np, pd):
    n_steps = 100
    t = np.linspace(0, 5, n_steps)

    # Generate 12D state vectors with different harmonics
    z_vectors = []
    for i in range(12):
        phase = (i / 12) * 2 * np.pi
        z_vectors.append(0.5 + 0.4 * np.sin(t * (0.5 + i / 5) + phase))

    z_df = pd.DataFrame(np.array(z_vectors).T, columns=[f"D{i + 1}" for i in range(12)])
    z_df["Step"] = np.arange(n_steps)
    z_df["Time"] = t
    z_df["Stability"] = 1.0 - (z_df["D1"] - 0.5) ** 2  # Simulated stability
    return n_steps, t, z_vectors, z_df


@app.cell
def __(px, z_df):
    # Stunning 3D Scatter with animation
    fig_traj = px.scatter_3d(
        z_df,
        x="D1",
        y="D2",
        z="D3",
        color="Stability",
        size="D4",
        opacity=0.7,
        title="12D Journey: Nexus Trajectory Animation",
        template="plotly_dark",
        animation_frame="Step",
        range_x=[0, 1],
        range_y=[0, 1],
        range_z=[0, 1],
    )
    fig_traj.update_layout(margin={"l": 0, "r": 0, "b": 0, "t": 30})
    return fig_traj


@app.cell
def __(fig_traj, mo):
    return mo.as_html(fig_traj)


@app.cell
def __(mo):
    mo.md("## ⚖️ 2. The 0.5 HIHO Stability Pulse")
    return


@app.cell
def __(mo):
    target_coherence = mo.ui.slider(0, 1, step=0.01, value=0.5, label="Target Coherence Rule (Interactive)")
    return (target_coherence,)


@app.cell
def __(audio_path, mo, target_coherence):
    # Calculate stability based on distance from 0.5
    coh_val = target_coherence.value
    stab = 1.0 - abs(coh_val - 0.5) * 2
    res_freq = 432 + (1.0 - stab) * 100

    # Display stats
    stats = mo.hstack(
        [
            mo.stat(label="Resonance Frequency", value=f"{res_freq:.1f} Hz"),
            mo.stat(label="Current Stability", value=f"{stab:.2f}"),
        ],
        justify="start",
    )

    # Audio pulse
    audio = mo.audio(src=audio_path, controls=True)

    return stats, audio


@app.cell
def __(audio, mo, stats):
    return mo.vstack([stats, mo.md("### 🔊 Listen to the Stability Pulse (432Hz Nexus)"), audio])


@app.cell
def __(go, mo, target_coherence):
    # Radar comparison based on slider
    val = target_coherence.value
    param_names = [
        "Awareness",
        "Space_1",
        "Space_2",
        "Space_3",
        "Tempic",
        "Electric",
        "Magnetic",
        "Spin_Rot",
        "Spin_Prec",
        "Charge",
        "Partic",
        "Precip",
    ]

    # Dynamic radar values
    r_live = [val, 0.5, 0.5, 0.5, 0.5, 0.5, val, 1 - val, 0.5, 0.5, 0.5, 0.5]
    r_nexus = [0.5] * 12

    fig_rd = go.Figure()
    fig_rd.add_trace(go.Scatterpolar(r=r_nexus, theta=param_names, fill="toself", name="Nexus Target (0.5)"))
    fig_rd.add_trace(
        go.Scatterpolar(
            r=r_live,
            theta=param_names,
            fill="toself",
            name="Current Alignment",
            line_color="cyan",
        )
    )

    fig_rd.update_layout(
        polar={"radialaxis": {"visible": True, "range": [0, 1]}},
        template="plotly_dark",
        showlegend=True,
        margin={"l": 40, "r": 40, "b": 20, "t": 40},
    )

    return mo.vstack([mo.md("### 📊 12D Parameter Balancing (Live Snapshot)"), mo.as_html(fig_rd)])


@app.cell
def __(mo):
    mo.md("""
    ## 🏁 3. Conclusion: The Living Paper
    This paper is powered by the **Cohezion Swarm**, which continuously mines new discoveries from the research lab and injects them into the knowledge graph. The reality you are viewing is a live-snapshot of the **Fractal Nexus Convergence**.

    ---
    *Generated by Cohezion Cloud Orchestrator | Hosted on cohezion.duckdns.org*
    """)
    return


if __name__ == "__main__":
    app.run()
