import asyncio
import logging
import re
from pathlib import Path

from cohezion.core.persistence.surreal_client import SurrealClient


logging.basicConfig(level=logging.INFO, format="%(asctime)s - [DIPLOMAT] - %(message)s")
logger = logging.getLogger("Diplomat")

WHITEPAPER_DIR = Path("data/whitepapers")


class Diplomat:
    """
    The Diplomat: Exports internal research as public Whitepapers.
    """

    def __init__(self):
        self.db = SurrealClient()
        WHITEPAPER_DIR.mkdir(parents=True, exist_ok=True)

    async def run_loop(self):
        logger.info("🕊️ Diplomat preparing briefcase...")

        while True:
            await self.publish_whitepapers()
            await asyncio.sleep(60)

    async def publish_whitepapers(self):
        try:
            # Find High Quality, Unplished Papers
            query = "SELECT * FROM universe_nodes WHERE node_type = 'research_paper' AND metadata.grade >= 0.9 AND metadata.verified = true AND metadata.published != true LIMIT 5"
            response = await self.db.query(query)

            papers = []
            if isinstance(response, list) and response and isinstance(response[0], dict):
                papers = response[0].get("result", [])

            if not papers:
                logger.info("zzz No papers ready for publication.")
                return

            for paper in papers:
                await self.publish(paper)

        except Exception as e:
            logger.error(f"Diplomatic Incident: {e}")

    async def publish(self, paper):
        meta = paper.get("metadata", {})
        topic = meta.get("topic", "Unknown Topic")
        content = paper.get("content", "")

        logger.info(f"📜 Publishing Whitepaper: {topic}")

        # Sanitize Filename
        safe_title = re.sub(r"[^a-zA-Z0-9_\-]", "_", topic)
        path = WHITEPAPER_DIR / f"{safe_title}.md"

        # Format Document
        doc = f"""---
title: "{topic}"
type: Research Whitepaper
grade: {meta.get("grade")}
id: {paper["id"]}
date: {paper.get("created_at")}
---

# {topic}

{content}

---
*Generated by Cohezion Swarm Intelligence*
"""
        path.write_text(doc)

        # Mark as Published
        await self.db.query(f"UPDATE {paper['id']} SET metadata.published = true")
        logger.info(f"✅ Published to {path}")


if __name__ == "__main__":

    async def main():
        dip = Diplomat()
        await dip.publish_whitepapers()  # One pass

    asyncio.run(main())
