#!/usr/bin/env python3
"""
Overnight Precipitation Mission 🌌
==================================
Runs a high-fidelity agentic swarm simulation for 8+ hours.
Enforces 96GB OOM guardrails and broadcasts hourly multimodal reports.

Reporting:
- Local: reports/hourly/snapshot_YYYYMMDD_HHMM.md
- Email: manderson240@gmail.com (Attempted)
- WebSocket: ws://localhost:8765 (Real-time)
"""

import asyncio
import importlib.util
import logging
import sys

# --- ROBUST MOCK DEPENDENCIES ---
import unittest.mock
from datetime import datetime, timedelta
from pathlib import Path


def mock_package(name):
    mock = unittest.mock.MagicMock()
    spec = importlib.util.spec_from_loader(name, loader=None)
    mock.__spec__ = spec
    sys.modules[name] = mock
    return mock


mock_package("pocket_tts")
mock_package("pocket_tts.modules.stateful_module")
mock_package("soundfile")
mock_package("transformers")

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

from cohezion.core.persistence.surreal_client import get_surreal_client
from cohezion.mcp.email_notifier import EmailNotifier, NotificationConfig
from cohezion.reliability.monitor import get_resource_monitor
from cohezion.simulation.fractal_universe import FractalSimulator
from cohezion.universe.engine import AxiomaticState, UniverseSimulationEngine


logger = logging.getLogger("OvernightMission")
logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(message)s")


class HourlyReporter:
    def __init__(self, recipient="manderson240@gmail.com"):
        self.recipient = recipient
        self.report_dir = Path("reports/hourly")
        self.report_dir.mkdir(parents=True, exist_ok=True)

        # Email setup
        config = NotificationConfig.from_env()
        config.recipient_email = recipient
        self.notifier = EmailNotifier(config=config)

    async def generate_snapshot(
        self, journey_id: str, step: int, axiomatic: AxiomaticState, phi: float
    ):
        timestamp = datetime.now().strftime("%Y%m%d_%H%M")
        h_score = 1.0 - abs(axiomatic.coherence_score() - 0.5) * 2

        # 1. Generate Markdown Report
        report = f"""# 🌌 COHEZION HOURLY SNAPSHOT: {timestamp}
**Journey:** `{journey_id}` | **Step:** `{step}`

## 💎 Manifold Vitals
- **Phi Score:** `{phi:.4f}`
- **HIHO Stability:** `{h_score:.4f}`
- **Coherence:** `{axiomatic.coherence_score():.4f}`

## 📐 4 Fabrics State
- **Space:** X:{axiomatic.spatial_x:+.2f} Y:{axiomatic.spatial_y:+.2f} Z:{axiomatic.spatial_z:+.2f}
- **Field:** TMP:{axiomatic.physics:.2f} ELE:{axiomatic.biology:.2f} MAG:{axiomatic.field:.2f}
- **Control:** ROT:{axiomatic.logic:.2f} PRE:{axiomatic.quantum:.2f} CHG:{axiomatic.control:.2f}
- **Precip:** AWA:{axiomatic.temporal:.2f} PAR:{axiomatic.novelty:.2f} VAL:{axiomatic.precipitation:.2f}

## 🔊 Sonification Chord
- **Fundamental:** 432Hz
- **Status:** {"Harmonious Triad" if phi > 0.8 else "Flux Dissonance"}

---
*Generated by Cohezion Sovereign Swarm*
"""
        # Save Locally
        report_path = self.report_dir / f"snapshot_{timestamp}.md"
        report_path.write_text(report)
        logger.info(f"💾 Local snapshot saved: {report_path}")

        # 2. Attempt Email
        if self.notifier.is_available:
            subject = f"🌌 COHEZION SNAPSHOT: {timestamp} (Phi: {phi:.2f})"
            html_body = report.replace("\n", "<br>")
            success = await self.notifier.send_email(subject, html_body, is_html=True)
            if success:
                logger.info(f"📧 Email report sent to {self.recipient}")
            else:
                logger.warning("❌ Email failed. Check .env credentials.")


async def run_overnight_mission(hours: int = 8):
    monitor = get_resource_monitor()
    db = get_surreal_client()
    await db.connect()

    engine = UniverseSimulationEngine(db_client=db)
    reporter = HourlyReporter()

    intent = "Overnight Sovereign Precipitation and Manifold Stabilization"
    journey = await engine.start_journey(agent_name="SovereignPrime", intent=intent)

    sim = FractalSimulator(num_agents=64)
    start_time = datetime.now()
    end_time = start_time + timedelta(hours=hours)

    logger.info(f"🚀 OVERNIGHT MISSION STARTED: {journey.id}")
    logger.info(f"⏰ Target End Time: {end_time}")

    step = 0
    last_report_hour = -1

    try:
        while datetime.now() < end_time:
            # 1. GUARDRAIL: Check System Pressure
            # Using 90GB (92160MB) as the hard ceiling
            current_mem = monitor.total_sandbox_memory_mb
            if current_mem > 90 * 1024:
                logger.warning(f"🚨 CRITICAL PRESSURE: {current_mem}MB. Dilation Active (0.001x)")
                await asyncio.sleep(60)  # Massive pause to let GC/OS breathe
                continue

            # 2. Step Simulation
            sim.step()

            if not sim.agents:
                logger.warning("Swarm collapsed. No agents remaining.")
                break

            leader = max(sim.agents, key=lambda a: a.cumulative_reward)

            # TOTAL REWARD: Sum of all agents cumulative reward (TDD Fix)
            total_reward = sum(a.cumulative_reward for a in sim.agents)

            # 3. Capture Trajectory
            point = await engine.evolve_trajectory(
                journey=journey,
                action=f"Overnight Stability Check ({step})",
                result=f"Swarm Reward: {total_reward:.2f}",
                phi_score=leader.coherence,
            )

            # 3.5 INFLECTION POINT: Trigger Solar Flare on High-Phi
            if leader.coherence > 0.9:
                engine.trigger_solar_flare(intensity=leader.coherence)
                logger.info(
                    f"✨ Breakthrough detected (Phi: {leader.coherence:.2f}). Solar Flare ignited."
                )

            # 4. Hourly Reporting
            current_hour = datetime.now().hour
            if current_hour != last_report_hour:
                await reporter.generate_snapshot(
                    journey.id, step, point.axiomatic, leader.coherence
                )
                last_report_hour = current_hour

            step += 1
            await asyncio.sleep(1.0)  # Balanced pacing for overnight stability

        # 6. Finalize Precipitation
        await engine.precipitate_reality(
            journey=journey,
            outputs={"mission_log": "Fractal Manifold Stabilized", "final_phi": leader.coherence},
            phi_score=leader.coherence,
        )

        # 7. Cinematic Mission Wrap-up (Gemini Pro Video)
        try:
            from cohezion.core.multimodal_bridge import LOCAL_MULTIMODAL_BRIDGE

            await LOCAL_MULTIMODAL_BRIDGE.schedule_asset(
                asset_type="video",
                priority=3,
                payload={
                    "storyboard": "The Great Precipitation (8-Hour Mission Archive)",
                    "journey_id": journey.id,
                },
            )
        except Exception:
            pass

        logger.info("✨ MISSION COMPLETE: 8-hour precipitation cycle successful.")

    except KeyboardInterrupt:
        logger.info("Mission stopped by coordinator.")
    finally:
        await db.close()


if __name__ == "__main__":
    asyncio.run(run_overnight_mission())
