"""Graph Reactor — pre-computes SurrealDB intelligence into vault markdown."""

import time
from datetime import datetime
from pathlib import Path

from .client import SurrealClient
from .config import VAULT_ROOT
from .helpers import content_hash, _writeback_paths

REACTOR_THROTTLE_SECS = 60
ALERTS_FILE = VAULT_ROOT / "metabolism" / "graph-alerts.md"
TODAY_FMT = "%Y-%m-%d"


class GraphReactor:
    """Pre-computes graph intelligence into vault files for Claude to read."""

    def __init__(self, db: SurrealClient):
        self.db = db
        self._last_run = 0.0
        self._last_hash = ""

    def maybe_react(self, changed_country: str = "") -> bool:
        now = time.time()
        if now - self._last_run < REACTOR_THROTTLE_SECS:
            return False
        self._last_run = now
        return self._run(changed_country)

    def _run(self, changed_country: str) -> bool:
        dark = self._query_dark_countries()
        orphans = self._query_orphan_neurons()
        resting = self._query_resting_notes()
        hiho = self._query_recent_hiho()
        gaps = self._query_synapse_gaps()

        today = datetime.now().strftime(TODAY_FMT)
        lines = [
            "---",
            "title: Graph Alerts — Live Dashboard",
            f"date: {today}",
            "tags: [metabolism, graph-reactor, auto-generated]",
            "aspect: connective",
            "---",
            "",
            "# Graph Alerts",
            "",
            f"> Auto-generated by GraphReactor on {today}.",
            "> Read by vault-keeper at session start. Do not edit manually.",
            "",
        ]

        # Dark Countries
        lines.append("## Dark Countries (health < 0.3)")
        lines.append("")
        if dark:
            lines.append("| Country | Health | Neurons | Action |")
            lines.append("|---------|--------|---------|--------|")
            for c in dark:
                lines.append(
                    f"| {c['name']} | {c['health']:.3f} | {c['neurons']} | "
                    f"Flesh out notes in `{c['name']}/` |"
                )
        else:
            lines.append("None. All countries above 0.3 threshold.")
        lines.append("")

        # Low Countries (0.3-0.5)
        low = self._query_low_countries()
        if low:
            lines.append("## Low Countries (0.3-0.5)")
            lines.append("")
            lines.append("| Country | Health | Neurons |")
            lines.append("|---------|--------|---------|")
            for c in low:
                lines.append(f"| {c['name']} | {c['health']:.3f} | {c['neurons']} |")
            lines.append("")

        # Orphan Neurons
        lines.append("## Orphan Neurons (0 inbound, high activation)")
        lines.append("")
        if orphans:
            for o in orphans[:10]:
                lines.append(
                    f"- `{o['path']}` (act={o['activation']:.3f}, "
                    f"out={o['synapse_out']}) — needs inbound links"
                )
        else:
            lines.append("None. All active neurons have inbound synapses.")
        lines.append("")

        # Resting Notes
        lines.append("## Resting Notes (activation < 0.2)")
        lines.append("")
        if resting:
            for r in resting[:10]:
                lines.append(f"- `{r['path']}` (act={r['activation']:.3f}, stage={r['stage']})")
            lines.append("")
            lines.append("Consider: renew with fresh content, or compost if obsolete.")
        else:
            lines.append("None. All notes above resting threshold.")
        lines.append("")

        # Synapse Gaps
        lines.append("## Synapse Gaps (should-be-connected pairs)")
        lines.append("")
        if gaps:
            for g in gaps[:8]:
                lines.append(f"- [[{g['a_stem']}]] and [[{g['b_stem']}]] "
                             f"share {g['shared_tags']} tags but no synapse")
        else:
            lines.append("No obvious gaps detected.")
        lines.append("")

        # Recent HIHO
        lines.append("## Recent HIHO Fusion Events")
        lines.append("")
        if hiho:
            lines.append("| Date | Country | Coherence |")
            lines.append("|------|---------|-----------|")
            for h in hiho[:5]:
                lines.append(f"| {h['date'][:10]} | {h['country']} | {h['score']:.3f} |")
        else:
            lines.append("No recent fusion events.")
        lines.append("")

        # Summary
        lines.append("## Summary")
        lines.append("")
        lines.append(f"- Dark countries: {len(dark)}")
        lines.append(f"- Orphan neurons: {len(orphans)}")
        lines.append(f"- Resting notes: {len(resting)}")
        lines.append(f"- Synapse gaps: {len(gaps)}")
        lines.append(f"- HIHO events (7d): {len(hiho)}")
        lines.append("")

        content = "\n".join(lines)
        chash = content_hash(content)

        if chash == self._last_hash:
            return False

        self._last_hash = chash
        ALERTS_FILE.parent.mkdir(parents=True, exist_ok=True)
        ALERTS_FILE.write_text(content, encoding="utf-8")
        _writeback_paths.add(str(ALERTS_FILE.relative_to(VAULT_ROOT)))
        return True

    def _query_dark_countries(self) -> list[dict]:
        rows = self.db.query_result(
            "SELECT * FROM country WHERE health < 0.3 ORDER BY health ASC;"
        )
        return [{"name": r.get("name", "?"), "health": r.get("health", 0),
                 "neurons": r.get("neuron_count", 0)} for r in rows]

    def _query_low_countries(self) -> list[dict]:
        rows = self.db.query_result(
            "SELECT * FROM country WHERE health >= 0.3 AND health < 0.5 "
            "ORDER BY health ASC;"
        )
        return [{"name": r.get("name", "?"), "health": r.get("health", 0),
                 "neurons": r.get("neuron_count", 0)} for r in rows]

    def _query_orphan_neurons(self) -> list[dict]:
        rows = self.db.query_result(
            "SELECT path, activation, synapse_out FROM neuron "
            "WHERE synapse_in = 0 AND activation > 0.5 "
            "ORDER BY activation DESC LIMIT 15;"
        )
        return [{"path": r.get("path", "?"), "activation": r.get("activation", 0),
                 "synapse_out": r.get("synapse_out", 0)} for r in rows]

    def _query_resting_notes(self) -> list[dict]:
        rows = self.db.query_result(
            "SELECT path, activation, stage FROM neuron "
            "WHERE activation < 0.2 ORDER BY activation LIMIT 15;"
        )
        return [{"path": r.get("path", "?"), "activation": r.get("activation", 0),
                 "stage": r.get("stage", "?")} for r in rows]

    def _query_recent_hiho(self) -> list[dict]:
        rows = self.db.query_result("SELECT * FROM hiho_event ORDER BY date DESC LIMIT 10;")
        return [{"date": str(r.get("date", "")), "country": r.get("country", "?"),
                 "score": r.get("coherence_score", 0)} for r in rows]

    def _query_synapse_gaps(self) -> list[dict]:
        """Find pairs of neurons sharing 2+ tags but no synapse."""
        rows = self.db.query_result(
            "SELECT id, path, tags FROM neuron WHERE cluster_id = 'cortex' "
            "AND array::len(tags) > 1 LIMIT 200;"
        )
        if not rows:
            return []

        neuron_tags: dict[str, set[str]] = {}
        neuron_stem: dict[str, str] = {}
        tag_to_nids: dict[str, list[str]] = {}

        for r in rows:
            nid = str(r["id"])
            tags = r.get("tags", [])
            if not isinstance(tags, list):
                continue
            neuron_tags[nid] = set(tags)
            neuron_stem[nid] = Path(r.get("path", "?")).stem
            for t in tags:
                tag_to_nids.setdefault(t, []).append(nid)

        seen: set[tuple[str, str]] = set()
        gaps: list[dict] = []

        for tag, nids in tag_to_nids.items():
            for i, a_id in enumerate(nids):
                for b_id in nids[i + 1:]:
                    pair = (min(a_id, b_id), max(a_id, b_id))
                    if pair in seen:
                        continue
                    seen.add(pair)

                    shared = len(neuron_tags[a_id] & neuron_tags[b_id])
                    if shared >= 2:
                        check = self.db.query_result(
                            f"SELECT count() FROM synapse WHERE "
                            f"(in = {a_id} AND out = {b_id}) OR "
                            f"(in = {b_id} AND out = {a_id}) GROUP ALL;"
                        )
                        count = check[0]["count"] if check else 0
                        if count == 0:
                            gaps.append({
                                "a_stem": neuron_stem[a_id],
                                "b_stem": neuron_stem[b_id],
                                "shared_tags": shared,
                            })
                            if len(gaps) >= 15:
                                return gaps
        return gaps
