#!/usr/bin/env python3
import json
import os
import yaml
from pathlib import Path

# Single Source of Truth
CONFIG_PATH = Path("src/cohezion/swarm/specialist_agents_config.json")
# Target Directories
TARGETS = {
    "claude": Path(".claude/agents/"),
    "gemini": Path(".gemini/agents/"),
    "opencode": Path(".opencode/agents/"),
    "pi": Path(".pi/agents/")
}
# SSOT Markdown for the .agent/ directory
AGENTS_MD_PATH = Path(".agent/AGENTS.md")

def load_config():
    with open(CONFIG_PATH, "r") as f:
        return json.load(f)

def generate_markdown(agent):
    name = agent["name"]
    role = agent["role"]
    expertise = agent["expertise"]
    prompt_template = agent["prompt_template"]
    review_focus = agent.get("review_focus", [])
    
    # Frontmatter
    frontmatter = {
        "name": name,
        "description": f"{name} ({role}) specialized in {', '.join(expertise[:3])}..."
    }
    
    # Build content
    content = f"---\n{yaml.dump(frontmatter, sort_keys=False)}---\n\n"
    content += f"# {name} Agent ({role.upper()})\n\n"
    content += f"{prompt_template}\n\n"
    
    content += "## Domain Expertise\n"
    for item in expertise:
        content += f"- {item}\n"
    content += "\n"
    
    if review_focus:
        content += "## Review Focus\n"
        for item in review_focus:
            content += f"- {item}\n"
        content += "\n"
        
    return content

def sync_agents():
    print(f"Loading configuration from {CONFIG_PATH}...")
    config = load_config()
    agents = config.get("agents", [])
    
    # Ensure directories exist
    for target_dir in TARGETS.values():
        target_dir.mkdir(parents=True, exist_ok=True)
        print(f"Synchronizing {target_dir}...")
        
    # Generate per-agent files
    for agent in agents:
        role = agent["role"]
        filename = f"{role}.md"
        content = generate_markdown(agent)
        
        for target_dir in TARGETS.values():
            file_path = target_dir / filename
            with open(file_path, "w") as f:
                f.write(content)
            # Set executable bit for good measure if it were a script, but these are MD
            
    # Synchronize .agent/AGENTS.md
    print(f"Synchronizing {AGENTS_MD_PATH}...")
    AGENTS_MD_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    agents_summary = "# Specialist Agent Registry\n\n"
    agents_summary += "This file is autogenerated from `src/cohezion/swarm/specialist_agents_config.json` via `make agent-guard`.\n\n"
    agents_summary += "| Role | Name | Model | Expertise |\n"
    agents_summary += "|------|------|-------|-----------|\n"
    
    for agent in agents:
        role = agent["role"]
        name = agent["name"]
        model = agent["model"]
        expertise_short = ", ".join(agent["expertise"][:3])
        agents_summary += f"| {role} | {name} | {model} | {expertise_short} |\n"
        
    with open(AGENTS_MD_PATH, "w") as f:
        f.write(agents_summary)
    
    print("Synchronization complete.")

if __name__ == "__main__":
    sync_agents()
