#!/usr/bin/env python3
"""Generate Cohezion status report — kernel optimization + system health.

Queries SurrealDB for kernel runs, training history, health checks.
Optionally emails via SMTP (requires COHEZION_SMTP_* env vars).
Always writes to --output file.

Usage:
    .venv/bin/python scripts/generate_status_report.py --output report.txt
    .venv/bin/python scripts/generate_status_report.py --email manderson240@gmail.com
"""

from __future__ import annotations

import argparse
import json
import os
import smtplib
import sys
import urllib.request
from base64 import b64encode
from datetime import datetime
from email.mime.text import MIMEText
from pathlib import Path

SURREAL_URL = "http://localhost:8001/sql"
SURREAL_HEADERS = {
    "Accept": "application/json",
    "surreal-ns": "cohezion",
    "surreal-db": "cohezion",
    "Authorization": "Basic " + b64encode(b"root:root").decode(),
}

KERNEL_LEADERS = {"gemm": 4.3, "mla": 33.0, "moe": 109.8}


def surreal_query(sql: str) -> list:
    try:
        req = urllib.request.Request(
            SURREAL_URL, data=sql.encode(), headers=SURREAL_HEADERS, method="POST"
        )
        resp = urllib.request.urlopen(req, timeout=5)
        return json.loads(resp.read())
    except Exception:
        return []


def get_kernel_summary() -> str:
    lines = ["=== Kernel Optimization Status ===\n"]
    for kernel, leader in KERNEL_LEADERS.items():
        results = surreal_query(
            f"SELECT math::min(time_us) as best, count() as total "
            f"FROM kernel_run WHERE kernel = '{kernel}' GROUP ALL;"
        )
        best = 999999.0
        total = 0
        if results and results[0].get("status") == "OK" and results[0].get("result"):
            row = results[0]["result"][0]
            best = row.get("best", 999999.0) or 999999.0
            total = row.get("total", 0) or 0

        gap = best / leader if leader > 0 else 0
        lines.append(
            f"  {kernel.upper():5s}  best={best:8.1f}us  leader={leader:.1f}us  gap={gap:.1f}x  runs={total}"
        )

        # Recent runs (last hour)
        recent = surreal_query(
            f"SELECT approach, time_us, status, created FROM kernel_run "
            f"WHERE kernel = '{kernel}' AND created > time::now() - 1h ORDER BY created DESC LIMIT 5;"
        )
        if recent and recent[0].get("status") == "OK" and recent[0].get("result"):
            for r in recent[0]["result"]:
                lines.append(
                    f"    {r.get('approach', '?')[:30]:30s} {r.get('time_us', 0):8.1f}us [{r.get('status', '?')}]"
                )
    return "\n".join(lines)


def get_system_health() -> str:
    lines = ["\n=== System Health ===\n"]

    # SurrealDB table counts
    for table in ["kernel_run", "training_run", "learning", "health_check", "retrospection"]:
        results = surreal_query(f"SELECT count() as n FROM {table} GROUP ALL;")
        n = 0
        if results and results[0].get("status") == "OK" and results[0].get("result"):
            n = results[0]["result"][0].get("n", 0) or 0
        lines.append(f"  SurrealDB {table}: {n} records")

    # Test suite status
    try:
        import subprocess

        result = subprocess.run(
            ["uv", "run", "pytest", "tests/", "-q", "--tb=no", "-o", "addopts="],
            capture_output=True,
            text=True,
            timeout=120,
            cwd=str(Path(__file__).parent.parent),
        )
        # Parse "X passed, Y warnings" from last line
        for line in result.stdout.strip().split("\n")[-3:]:
            if "passed" in line or "failed" in line:
                lines.append(f"  Tests: {line.strip()}")
                break
    except Exception as e:
        lines.append(f"  Tests: could not run ({e})")

    return "\n".join(lines)


def get_recent_learnings() -> str:
    lines = ["\n=== Recent Learnings (last 2h) ===\n"]
    results = surreal_query(
        "SELECT content, category, created FROM learning "
        "WHERE created > time::now() - 2h ORDER BY created DESC LIMIT 5;"
    )
    if results and results[0].get("status") == "OK" and results[0].get("result"):
        for r in results[0]["result"]:
            content = (r.get("content") or "")[:80]
            cat = r.get("category", "?")
            lines.append(f"  [{cat}] {content}")
    else:
        lines.append("  No new learnings in last 2 hours")
    return "\n".join(lines)


def generate_report() -> str:
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    deadline = "April 6, 2026 11:59 PM PST"

    header = f"""Cohezion Status Report — {now}
Deadline: {deadline}
{"=" * 60}
"""
    kernel_summary = get_kernel_summary()
    health = get_system_health()
    learnings = get_recent_learnings()

    footer = f"""
{"=" * 60}
Generated by scripts/generate_status_report.py
Next report in ~1 hour
"""
    return header + kernel_summary + health + learnings + footer


def send_email(report: str, recipient: str) -> bool:
    """Send email via SMTP. Requires env vars for SMTP config."""
    smtp_host = os.environ.get("COHEZION_SMTP_HOST", "")
    smtp_port = int(os.environ.get("COHEZION_SMTP_PORT", "587"))
    smtp_user = os.environ.get("COHEZION_SMTP_USER", "")
    smtp_pass = os.environ.get("COHEZION_SMTP_PASS", "")

    if not smtp_host or not smtp_user:
        print(
            "SMTP not configured (set COHEZION_SMTP_HOST, COHEZION_SMTP_USER, COHEZION_SMTP_PASS)"
        )
        return False

    msg = MIMEText(report)
    msg["Subject"] = f"Cohezion Kernel Status — {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    msg["From"] = smtp_user
    msg["To"] = recipient

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
        print(f"Email sent to {recipient}")
        return True
    except Exception as e:
        print(f"Email failed: {e}")
        return False


def is_substantial(report: str) -> bool:
    """Check if report has substantial content worth sending."""
    # Always send if there are new kernel runs in last hour
    if "success" in report.lower() and "runs=" in report:
        return True
    # Always send if there are new learnings
    if "No new learnings" not in report:
        return True
    # Send anyway as heartbeat (but could be made conditional)
    return True


def main():
    parser = argparse.ArgumentParser(description="Generate Cohezion status report")
    parser.add_argument("--output", help="Output file path")
    parser.add_argument("--email", help="Email recipient")
    parser.add_argument("--force", action="store_true", help="Send even if not substantial")
    args = parser.parse_args()

    report = generate_report()

    # Write to file
    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(report)
        print(f"Report written to {args.output}")

    # Print to stdout
    print(report)

    # Email if configured and substantial
    if args.email:
        if args.force or is_substantial(report):
            send_email(report, args.email)
        else:
            print("No substantial updates — skipping email")


if __name__ == "__main__":
    main()
