#!/usr/bin/env python3
"""Batch-digest salvaged Claude Code sessions on local silicon ($0).

Runs session_salvage (deterministic) -> session_digest (local Gemma-4-26B via :13305)
over every main-session transcript, writing one vault note per session.

Usage:
    uv run python scripts/salvage_digest_batch.py [--subagents] [--limit N]

Idempotent: a session whose note already exists is skipped, so the batch can be
interrupted and resumed. Sessions with no real evidence are skipped entirely rather
than sent to the model — no point spending inference to summarize nothing.
"""

from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

from cohezion.observability.session_digest import digest_session
from cohezion.observability.session_salvage import (
    is_ephemeral,
    is_subagent_transcript,
    iter_transcripts,
    load_session,
    unique_writes,
)

OUT = Path.home() / "vaults/cohezion-vault/reports/salvage-20260718/digests"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--subagents", action="store_true", help="include subagent transcripts")
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()

    OUT.mkdir(parents=True, exist_ok=True)
    paths = [
        p
        for p in iter_transcripts()
        if args.subagents or not is_subagent_transcript(p)
    ]
    if args.limit:
        paths = paths[: args.limit]

    done = skipped = failed = 0
    t0 = time.time()
    for i, p in enumerate(paths, 1):
        note = OUT / f"{p.stem}.md"
        if note.exists():
            skipped += 1
            continue
        art = load_session(p)
        real_writes = [w for w in art.file_writes if not is_ephemeral(w.path)]
        if not art.user_prompts and not real_writes:
            skipped += 1
            continue

        text = digest_session(art)
        if not text:
            failed += 1
            print(f"[{i}/{len(paths)}] FAILED (model returned nothing) {p.name}", flush=True)
            continue

        uniq = unique_writes(art)
        note.write_text(
            f"""---
type: session-digest
session_id: {art.session_id or p.stem}
cwd: {art.cwd}
first_seen: {art.first_ts}
last_seen: {art.last_ts}
transcript: {p.name}
kind: {"subagent" if is_subagent_transcript(p) else "session"}
prompts: {len(art.user_prompts)}
file_writes: {len(art.file_writes)}
unique_writes: {len(uniq)}
bash_commands: {len(art.bash_commands)}
generated_by: session_digest / Gemma-4-26B-A4B (local, $0)
---

# Session digest — {art.last_ts[:16]}

{text}

## Evidence

- **Working dir:** `{art.cwd or "unknown"}`
- **Files written:** {len(real_writes)} non-ephemeral
- **Writes differing from disk today:** {len(uniq)}
- **Commands run:** {len(art.bash_commands)}

> Digest generated by a local model from transcript evidence only. Claims are bounded by
> what the transcript recorded; absence of a detail here is not evidence it did not happen.
""",
            encoding="utf-8",
        )
        done += 1
        el = time.time() - t0
        print(
            f"[{i}/{len(paths)}] {p.name[:12]} -> {len(text)}c "
            f"({done} done, {el / 60:.1f}m elapsed)",
            flush=True,
        )

    print(f"\ndone={done} skipped={skipped} failed={failed} in {(time.time() - t0) / 60:.1f}m")
    print(f"notes -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
