"""KV cost must follow the model ARCHITECTURE, not an all-layers-GQA assumption.

Oracle: real GGUF headers (src/cohezion/inference/gguf_kv_profiles.json, regenerated by
scripts/ops/gguf_kv_profiles.py). Expected values are hand-derived from those headers.
"""

import pytest

from cohezion.inference import hotswap
from cohezion.inference import kv_budget as kb


GB = 2**30
MB = 2**20


def _kv(model, seq, dtype="q4_0"):
    return kb.kv_bytes_from_profile(kb.profile_for(model), seq_len=seq, cache_dtype=dtype)


def test_kv1_hybrid_gdn_caches_only_the_full_attention_layers():
    # Qwen3-Coder-Next: 48 layers, interval 4 -> 12 attn layers x 2 kv heads x (256+256) elems.
    p = kb.profile_for("Qwen3-Coder-Next-GGUF")
    assert p.global_elems_per_token == 12 * 2 * 512
    # ...NOT 48 layers: the all-GQA assumption is 4x too high (discriminating).
    naive = kb.kv_cache_bytes(
        num_layers=48, num_kv_heads=2, head_dim=256, seq_len=32768, cache_dtype="q4_0"
    )
    assert _kv("Qwen3-Coder-Next-GGUF", 32768) - p.fixed_state_bytes < naive / 3


def test_kv2_recurrent_state_is_fixed_and_context_independent():
    p = kb.profile_for("Qwen3-Coder-Next-GGUF")
    assert p.fixed_state_bytes == 36 * 4096 * 128 * 4  # 36 recurrent layers, fp32
    assert _kv("Qwen3-Coder-Next-GGUF", 1) >= p.fixed_state_bytes  # state is paid even at ~0 ctx


def test_kv3_mamba_hybrid_counts_only_nonzero_kv_head_layers():
    # Nemotron-3-Nano: 52 layers, 6 with attention, 2 kv heads... derived from the head list.
    p = kb.profile_for("Nemotron-3-Nano-30B-A3B-GGUF")
    assert 0 < p.global_elems_per_token <= 6 * 8 * 256
    assert _kv("Nemotron-3-Nano-30B-A3B-GGUF", 131072) < 0.5 * GB


def test_kv4_sliding_window_layers_stop_growing_at_the_window():
    m = "Gemma-4-31B-it-GGUF"
    p = kb.profile_for(m)
    assert p.swa_window == 1024 and p.swa_elems_per_token > 0
    grow = _kv(m, 131072) - _kv(m, 65536)  # only GLOBAL layers grow past the window
    assert grow == pytest.approx(p.global_elems_per_token * 65536 * 0.5, rel=1e-9)


def test_kv5_mla_stores_one_latent_per_layer():
    p = kb.profile_for("GLM-4.7-Flash-GGUF")
    assert p.global_elems_per_token == 47 * 576 and p.swa_elems_per_token == 0


def test_kv6_ctx_cap_scales_with_kv_cost_and_unknown_models_keep_the_floor():
    budget = 4 * GB
    hybrid = kb.ctx_cap_for("Qwen3.6-35B-A3B-MTP-GGUF", floor=16384, budget_bytes=budget)
    dense = kb.ctx_cap_for("Devstral-Small-2507-GGUF", floor=16384, budget_bytes=budget)
    assert hybrid == 131072 and 16384 < dense < hybrid
    assert kb.ctx_cap_for("never-surveyed-model", floor=16384, budget_bytes=budget) == 16384
    # a profiled model never falls below the caller's floor, even on a tiny budget
    assert kb.ctx_cap_for("Devstral-Small-2507-GGUF", floor=16384, budget_bytes=1) == 16384


def _stub(monkeypatch, weights_gb):
    monkeypatch.setattr(hotswap, "resident_models", lambda: [])
    monkeypatch.setattr(
        hotswap, "_catalog_sizes", lambda: {"M": weights_gb, "Devstral-Small-2507-GGUF": weights_gb}
    )
    monkeypatch.setattr(hotswap, "free_gb", lambda: 100.0)
    posted = {}

    def _post(path, body, timeout):
        posted.update(body)
        return 200, "ok"

    monkeypatch.setattr(hotswap, "_post", _post)
    return posted


def test_kv7_ensure_resident_consumes_the_cap_only_when_opted_in(monkeypatch):
    # CONSUMPTION: the ctx that reaches /api/v1/load is the per-model cap, and off by default.
    monkeypatch.setattr(hotswap, "_catalog_sizes", lambda: {"Qwen3.6-35B-A3B-MTP-GGUF": 22.0})
    monkeypatch.setattr(hotswap, "resident_models", lambda: [])
    monkeypatch.setattr(hotswap, "free_gb", lambda: 100.0)
    for opt_in, want in ((False, hotswap.MAX_CTX), (True, 131072)):
        posted = {}
        monkeypatch.setattr(
            hotswap, "_post", lambda p, b, t, _s=posted: _s.update(b) or (200, "ok")
        )
        hotswap.ensure_resident("Qwen3.6-35B-A3B-MTP-GGUF", ctx_size=131072, kv_aware_ctx=opt_in)
        assert posted.get("ctx_size") == want, (opt_in, posted)


def test_kv8_overhead_is_never_looser_than_the_flat_guess():
    for m in ("Qwen3-Coder-Next-GGUF", "Gemma-4-31B-it-GGUF", "Devstral-Small-2507-GGUF"):
        for w in (5.0, 20.0):
            assert hotswap._kv_overhead_gb(w, m, 131072) >= hotswap._kv_overhead_gb(w)
    assert hotswap._kv_overhead_gb(20.0, "Devstral-Small-2507-GGUF", 131072) > 3.0  # dense@128k
