# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AuditLeaderboardNextAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SubmissionStrategy:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AuditLeaderboardNextAction", llm_response=llm_response, mode="request")
        return typing.cast(types.SubmissionStrategy, __result__)

    def ClassifyTaskIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TaskClassificationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyTaskIntent", llm_response=llm_response, mode="request")
        return typing.cast(types.TaskClassificationResult, __result__)

    def DecideHardwareRouting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.RoutingDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecideHardwareRouting", llm_response=llm_response, mode="request")
        return typing.cast(types.RoutingDecision, __result__)

    def DeriveTaskInvariants(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TaskInvariants:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DeriveTaskInvariants", llm_response=llm_response, mode="request")
        return typing.cast(types.TaskInvariants, __result__)

    def EvaluateHarmonicSheaf(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.SheafDirichletState:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateHarmonicSheaf", llm_response=llm_response, mode="request")
        return typing.cast(types.SheafDirichletState, __result__)

    def ExtractVaultGraph(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.VaultGraphExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractVaultGraph", llm_response=llm_response, mode="request")
        return typing.cast(types.VaultGraphExtraction, __result__)

    def RecommendNextStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.NextStep:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RecommendNextStep", llm_response=llm_response, mode="request")
        return typing.cast(types.NextStep, __result__)

    def SynthesizeCodeHarness(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.CodeHarness:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeCodeHarness", llm_response=llm_response, mode="request")
        return typing.cast(types.CodeHarness, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AuditLeaderboardNextAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SubmissionStrategy:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AuditLeaderboardNextAction", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SubmissionStrategy, __result__)

    def ClassifyTaskIntent(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TaskClassificationResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyTaskIntent", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TaskClassificationResult, __result__)

    def DecideHardwareRouting(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.RoutingDecision:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DecideHardwareRouting", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.RoutingDecision, __result__)

    def DeriveTaskInvariants(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TaskInvariants:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DeriveTaskInvariants", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TaskInvariants, __result__)

    def EvaluateHarmonicSheaf(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.SheafDirichletState:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="EvaluateHarmonicSheaf", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.SheafDirichletState, __result__)

    def ExtractVaultGraph(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.VaultGraphExtraction:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractVaultGraph", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.VaultGraphExtraction, __result__)

    def RecommendNextStep(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.NextStep:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="RecommendNextStep", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.NextStep, __result__)

    def SynthesizeCodeHarness(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.CodeHarness:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeCodeHarness", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.CodeHarness, __result__)

    