# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def AuditLeaderboardNextAction(self, competition: str,leaderboard_snapshot: str,
        baml_options: BamlCallOptions = {},
    ) -> types.SubmissionStrategy:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.AuditLeaderboardNextAction(competition=competition,leaderboard_snapshot=leaderboard_snapshot,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="AuditLeaderboardNextAction", args={
                "competition": competition,"leaderboard_snapshot": leaderboard_snapshot,
            })
            return typing.cast(types.SubmissionStrategy, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def DeriveTaskInvariants(self, task_context: str,train_examples: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TaskInvariants:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.DeriveTaskInvariants(task_context=task_context,train_examples=train_examples,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="DeriveTaskInvariants", args={
                "task_context": task_context,"train_examples": train_examples,
            })
            return typing.cast(types.TaskInvariants, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def RecommendNextStep(self, context: str,candidates: str,
        baml_options: BamlCallOptions = {},
    ) -> types.NextStep:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.RecommendNextStep(context=context,candidates=candidates,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="RecommendNextStep", args={
                "context": context,"candidates": candidates,
            })
            return typing.cast(types.NextStep, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def SynthesizeCodeHarness(self, env_spec: str,failure_trace: str,
        baml_options: BamlCallOptions = {},
    ) -> types.CodeHarness:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.SynthesizeCodeHarness(env_spec=env_spec,failure_trace=failure_trace,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="SynthesizeCodeHarness", args={
                "env_spec": env_spec,"failure_trace": failure_trace,
            })
            return typing.cast(types.CodeHarness, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AuditLeaderboardNextAction(self, competition: str,leaderboard_snapshot: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.SubmissionStrategy, types.SubmissionStrategy]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="AuditLeaderboardNextAction", args={
            "competition": competition,"leaderboard_snapshot": leaderboard_snapshot,
        })
        return baml_py.BamlSyncStream[stream_types.SubmissionStrategy, types.SubmissionStrategy](
          __result__,
          lambda x: typing.cast(stream_types.SubmissionStrategy, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.SubmissionStrategy, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def DeriveTaskInvariants(self, task_context: str,train_examples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.TaskInvariants, types.TaskInvariants]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="DeriveTaskInvariants", args={
            "task_context": task_context,"train_examples": train_examples,
        })
        return baml_py.BamlSyncStream[stream_types.TaskInvariants, types.TaskInvariants](
          __result__,
          lambda x: typing.cast(stream_types.TaskInvariants, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TaskInvariants, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def RecommendNextStep(self, context: str,candidates: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.NextStep, types.NextStep]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="RecommendNextStep", args={
            "context": context,"candidates": candidates,
        })
        return baml_py.BamlSyncStream[stream_types.NextStep, types.NextStep](
          __result__,
          lambda x: typing.cast(stream_types.NextStep, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.NextStep, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SynthesizeCodeHarness(self, env_spec: str,failure_trace: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.CodeHarness, types.CodeHarness]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="SynthesizeCodeHarness", args={
            "env_spec": env_spec,"failure_trace": failure_trace,
        })
        return baml_py.BamlSyncStream[stream_types.CodeHarness, types.CodeHarness](
          __result__,
          lambda x: typing.cast(stream_types.CodeHarness, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.CodeHarness, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AuditLeaderboardNextAction(self, competition: str,leaderboard_snapshot: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AuditLeaderboardNextAction", args={
            "competition": competition,"leaderboard_snapshot": leaderboard_snapshot,
        }, mode="request")
        return __result__
    def DeriveTaskInvariants(self, task_context: str,train_examples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DeriveTaskInvariants", args={
            "task_context": task_context,"train_examples": train_examples,
        }, mode="request")
        return __result__
    def RecommendNextStep(self, context: str,candidates: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RecommendNextStep", args={
            "context": context,"candidates": candidates,
        }, mode="request")
        return __result__
    def SynthesizeCodeHarness(self, env_spec: str,failure_trace: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeCodeHarness", args={
            "env_spec": env_spec,"failure_trace": failure_trace,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AuditLeaderboardNextAction(self, competition: str,leaderboard_snapshot: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AuditLeaderboardNextAction", args={
            "competition": competition,"leaderboard_snapshot": leaderboard_snapshot,
        }, mode="stream")
        return __result__
    def DeriveTaskInvariants(self, task_context: str,train_examples: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="DeriveTaskInvariants", args={
            "task_context": task_context,"train_examples": train_examples,
        }, mode="stream")
        return __result__
    def RecommendNextStep(self, context: str,candidates: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="RecommendNextStep", args={
            "context": context,"candidates": candidates,
        }, mode="stream")
        return __result__
    def SynthesizeCodeHarness(self, env_spec: str,failure_trace: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="SynthesizeCodeHarness", args={
            "env_spec": env_spec,"failure_trace": failure_trace,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))