# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.CodeHarness": types.CodeHarness,
    "stream_types.CodeHarness": stream_types.CodeHarness,

    "types.NextStep": types.NextStep,
    "stream_types.NextStep": stream_types.NextStep,

    "types.SubmissionStrategy": types.SubmissionStrategy,
    "stream_types.SubmissionStrategy": stream_types.SubmissionStrategy,

    "types.TaskInvariants": types.TaskInvariants,
    "stream_types.TaskInvariants": stream_types.TaskInvariants,


}