#!/usr/bin/env python3
"""AutoHarness verification script for Cohezion.
Generated by autoharness-init. Updated by autoharness-update.

Usage: python .claude/rules/harness_check.py [files...]
       python .claude/rules/harness_check.py --fast  (format+lint only)
       python .claude/rules/harness_check.py --help
"""

import json
import subprocess
import sys
import time
from pathlib import Path
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
FAST_CHECKS = ["format", "lint-quick", "harness-bash"]
FULL_CHECKS = ["format", "lint", "typecheck", "fast-tests", "harness-bash"]
VALIDATE_CHECKS = ["validate-skills", "validate-registry"]

CHECKS: dict[str, dict[str, Any]] = {
    "format": {
        "cmd": ["ruff", "format", "--check", "src/", "tests/"],
        "desc": "Ruff format check",
        "timeout": 30,
    },
    "lint-quick": {
        "cmd": ["ruff", "check", "--select=F,E9,E501", "src/", "tests/"],
        "desc": "Ruff quick lint (syntax errors only)",
        "timeout": 30,
    },
    "lint": {
        "cmd": ["ruff", "check", "src/", "tests/"],
        "desc": "Ruff full lint",
        "timeout": 60,
    },
    "typecheck": {
        "cmd": ["mypy", "src/cohezion/", "--ignore-missing-imports"],
        "desc": "Mypy type check",
        "timeout": 90,
    },
    "fast-tests": {
        "cmd": [
            "uv",
            "run",
            "pytest",
            "tests/unit/",
            "--import-mode=append",
            "--tb=short",
            "-q",
            "-p",
            "no:warnings",
        ],
        "desc": "Fast unit tests",
        "timeout": 120,
    },
    "validate-skills": {
        "cmd": ["uv", "run", "python", "scripts/ci/validate_skills.py"],
        "desc": "Validate PRIME skills",
        "timeout": 60,
    },
    "validate-registry": {
        "cmd": ["uv", "run", "python", "scripts/ci/validate_registry.py"],
        "desc": "Validate skill registry",
        "timeout": 30,
    },
    "harness-bash": {
        "cmd": [],  # special-cased below
        "desc": "Verify deploy script sources safe-env.sh and the file exists (H3 invariant)",
        "timeout": 5,
    },
}


def _run_harness_bash_check(t0: float) -> dict:
    """H3 invariant: deploy script must source safe-env.sh; safe-env.sh must exist."""
    elapsed = time.perf_counter() - t0
    safe_env = Path.home() / ".config" / "cohezion" / "safe-env.sh"
    deploy_script = PROJECT_ROOT / "scripts" / "ci" / "deploy_harness_agents.sh"
    issues: list[str] = []
    if not safe_env.exists():
        issues.append(f"missing: {safe_env}")
    if not deploy_script.exists():
        issues.append(f"missing: {deploy_script}")
    elif "safe-env.sh" not in deploy_script.read_text():
        issues.append(f"deploy script does not source safe-env.sh")
    if issues:
        return {
            "check": "harness-bash",
            "description": CHECKS["harness-bash"]["desc"],
            "passed": False,
            "elapsed_s": round(elapsed, 3),
            "stderr": " | ".join(issues),
        }
    return {
        "check": "harness-bash",
        "description": CHECKS["harness-bash"]["desc"],
        "passed": True,
        "elapsed_s": round(elapsed, 3),
    }


def run_check(name: str, cfg: dict, files: list[str]) -> dict:
    cmd = cfg["cmd"]
    if files:
        cmd = cmd + files

    t0 = time.perf_counter()
    try:
        if name == "harness-bash":
            return _run_harness_bash_check(t0)
        result = subprocess.run(
            cmd,
            cwd=str(PROJECT_ROOT),
            capture_output=True,
            text=True,
            timeout=cfg["timeout"],
        )
        elapsed = time.perf_counter() - t0
        passed = result.returncode == 0
        return {
            "check": name,
            "description": cfg["desc"],
            "passed": passed,
            "elapsed_s": round(elapsed, 3),
            "exit_code": result.returncode,
            "stdout": result.stdout[:2000] if result.stdout else "",
            "stderr": result.stderr[:2000] if result.stderr else "",
        }
    except subprocess.TimeoutExpired:
        elapsed = time.perf_counter() - t0
        return {
            "check": name,
            "description": cfg["desc"],
            "passed": False,
            "elapsed_s": round(elapsed, 3),
            "error": f"Timed out after {cfg['timeout']}s",
        }
    except Exception as exc:
        elapsed = time.perf_counter() - t0
        return {
            "check": name,
            "description": cfg["desc"],
            "passed": False,
            "elapsed_s": round(elapsed, 3),
            "error": str(exc),
        }


def main() -> int:
    files = []
    check_names = FULL_CHECKS + VALIDATE_CHECKS

    if "--help" in sys.argv or "-h" in sys.argv:
        print(__doc__)
        print("Available checks:", ", ".join(CHECKS))
        return 0

    if "--fast" in sys.argv:
        check_names = FAST_CHECKS
        sys.argv.remove("--fast")

    # All remaining args are file paths
    files = sys.argv[1:]

    t0 = time.perf_counter()
    results = []
    failures = 0
    for name in check_names:
        if name not in CHECKS:
            continue
        r = run_check(name, CHECKS[name], files)
        results.append(r)
        status = "PASS" if r["passed"] else "FAIL"
        print(f"  [{status}] {r['description']} ({r.get('elapsed_s', 0):.1f}s)")
        if not r["passed"]:
            failures += 1
            if r.get("stderr"):
                print(f"    {r['stderr'][:200]}")

    total_elapsed = time.perf_counter() - t0
    passed = failures == 0
    output = {
        "passed": passed,
        "elapsed_s": round(total_elapsed, 3),
        "checks_ran": len(results),
        "checks_failed": failures,
        "results": results,
    }

    print(f"\n{'PASSED' if passed else 'FAILED'} ({failures} failures) in {total_elapsed:.1f}s")
    if output.get("export"):
        json_path = output.pop("export")
        Path(json_path).write_text(json.dumps(output, indent=2))

    return 0 if passed else 1


if __name__ == "__main__":
    sys.exit(main())
