#!/usr/bin/env bash
# restore_env.sh — Regenerate .env from Bitwarden vault.
#
# Usage: ./scripts/secrets/restore_env.sh [--output .env]
#
# Requires:
#   - Bitwarden CLI at ~/.local/bin/bw (or bw in PATH)
#   - An active, unlocked Bitwarden session (BW_SESSION must be set,
#     or the script will attempt an interactive unlock)
#
# If a secret is not found in Bitwarden, the entry is written as an empty
# string so you can identify what needs to be populated.

set -euo pipefail

OUTPUT="${1:-${OUTPUT_FILE:-.env}}"
BW="${BW_PATH:-${HOME}/.local/bin/bw}"

# Fall back to PATH if ~/.local/bin/bw is missing
if [[ ! -x "$BW" ]]; then
    BW="$(command -v bw 2>/dev/null || true)"
fi

if [[ -z "$BW" ]]; then
    echo "ERROR: Bitwarden CLI (bw) not found." >&2
    echo "Install it: https://bitwarden.com/help/cli/" >&2
    exit 1
fi

# Ensure vault is unlocked
STATUS=$("$BW" status 2>/dev/null | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('status','unknown'))" 2>/dev/null || echo "unknown")

if [[ "$STATUS" == "unauthenticated" ]]; then
    echo "You are not logged in to Bitwarden. Run: bw login" >&2
    exit 1
fi

if [[ "$STATUS" == "locked" ]]; then
    if [[ -n "${BW_SESSION:-}" ]]; then
        echo "Using BW_SESSION from environment."
    else
        echo "Vault is locked. Unlocking interactively..."
        BW_SESSION=$("$BW" unlock --raw)
        export BW_SESSION
    fi
fi

echo "Bitwarden vault is unlocked. Regenerating ${OUTPUT}..."

# Retrieve a secret (password field) by Bitwarden item name.
# Returns empty string if not found.
bw_get() {
    local name="$1"
    local result
    result=$("$BW" get item "$name" 2>/dev/null \
        | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('login',{}).get('password',''))" 2>/dev/null \
        || true)
    echo "${result:-}"
}

# Map: env variable name → Bitwarden item name
# Item names match what seed_bitwarden.sh creates.
declare -A SECRETS=(
    [ANTHROPIC_API_KEY]="cohezion/anthropic-api-key"
    [COHEZION_API_KEY]="cohezion/api-key"
    [COHEZION_SECRET_KEY]="cohezion/secret-key"
    [MCP_API_KEY]="cohezion/mcp-api-key"
    [CLOUD_VAULT_API_KEY]="cohezion/cloud-vault-api-key"
    [GOOGLE_EMAIL]="cohezion/google-email"
    [NOTIFICATION_PASSWORD]="cohezion/notification-password"
    [NGROK_API_KEY]="cohezion/ngrok-api-key"
    [SURREAL_PASSWORD]="cohezion/surreal-password"
    [SURREALDB_USERNAME]="cohezion/surrealdb-username"
    [SURREALDB_PASSWORD]="cohezion/surrealdb-password"
    [BW_SESSION]="cohezion/bw-session"
)

# Build .env content
{
    echo "# Generated by scripts/secrets/restore_env.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
    echo "# DO NOT COMMIT THIS FILE"
    echo ""

    for ENV_VAR in $(echo "${!SECRETS[@]}" | tr ' ' '\n' | sort); do
        ITEM="${SECRETS[$ENV_VAR]}"
        VALUE=$(bw_get "$ITEM")
        if [[ -z "$VALUE" ]]; then
            echo "WARN: '${ITEM}' not found in Bitwarden — ${ENV_VAR} will be empty" >&2
        fi
        echo "${ENV_VAR}=${VALUE}"
    done

    echo ""
    echo "# Non-secret configuration (safe defaults below)"
    echo "SURREALDB_URL=ws://localhost:8000"
    echo "SURREALDB_NAMESPACE=cohezion"
    echo "SURREALDB_DATABASE=vault"
    echo "MCP_HOST=127.0.0.1"
    echo "MCP_PORT=8360"
    echo "LOG_LEVEL=info"
    echo "OLLAMA_URL=http://localhost:11434"
    echo "GOOGLE_CLOUD_PROJECT="
} > "$OUTPUT"

echo "Done — written to ${OUTPUT}"
echo ""
echo "Next steps:"
echo "  source ${OUTPUT}"
echo "  uv run pytest tests/ -q"
